### ISSUE TITLE
Setup FsCheck organization and move repo there

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#100]
See #86 and #69 for discussions and rationale.

**Comment by kurtschelfthout** [comment]
Fitting that this is issue 100...

**Comment by ploeh** [comment]
The docs on https://fscheck.github.io/FsCheck still point to http://github.com/fsharp/FsCheck. Is the move complete?

**Comment by kurtschelfthout** [comment]
Mostly yes - I do indeed need to change some links in the docs, but GitHub redirects automatically so isn't a huge deal. Unless I'm missing something.

But you're right it makes sense to keep this issue open until that is done.
