### ISSUE TITLE
NUnit integration doesnt work

### ISSUE THREAD

**Issue by xkrt** [fscheck/FsCheck#117]
Hi!

I have installed FsCheck and FsCheck.NUnit (via NuGet) in my F# project and copy test from FsCheck examples:
```fsharp
[<Property>]
let revUnit (x:char) =
    List.rev [x] = [x]
```

Now I run test in GUI runner and got error:
```
Tests.revUnit:
Test method has non-void return type, but no result is expected
```

After that I have builded FsCheck solution and run this example in FsCheck.NUnit.Examples - it works  perfecty fine.
I see in your example project this:
```fsharp
[<NUnitAddin(Description = "FsCheck addin")>]
type FsCheckAddin() =        
    interface IAddin with
        override x.Install host = 
            let tcBuilder = new FsCheckTestCaseBuilder()
            host.GetExtensionPoint("TestCaseBuilders").Install(tcBuilder)
            true
```

This code relies on FsCheck.NUnit.Addin project. But there is FsCheck.NUnit.Addin in NuGet package FsCheck.NUnit.

NUnit 2.6.4
FsCheck 2.0.3
FsCheck.NUnit 2.0.3

**Comment by mausch** [comment]
Same issue as https://github.com/fscheck/FsCheck/issues/115 ?

**Comment by kurtschelfthout** [comment]
It turns out this is totally my fault, I changed the nuspec for the FsCheck.NUnit package and didn't include a bunch of stuff that is necessary! I am releasing 2.0.4 which should fix this.

Apologies!

**Comment by xkrt** [comment]
I confirm, with 2.0.4 everything ok

**Comment by kurtschelfthout** [comment]
Thanks!
