### ISSUE TITLE
Conflict with operator for Gen

### ISSUE THREAD

**Issue by paulyoung** [fscheck/FsCheck#120]
I have some tests that use custom operators, in particular `<*>`, which conflicts with the operator defined here: https://github.com/fscheck/FsCheck/blob/15b61f4a463691f7363b3dc71f022514c556867c/src/FsCheck/Gen.fs#L471

I followed [the advice of Tomas Petricek](http://stackoverflow.com/questions/19682432/global-operator-overloading-in-f/19683562#19683562) and defined mine as static members.

Do you know if doing the same would prevent the operator from `Gen` taking precedence? If so would you be open to a pull request that makes this change?

**Comment by kurtschelfthout** [comment]
Sure, if it works.

**Comment by kurtschelfthout** [comment]
Yes, 2.0.5 is out. If you get antsy, there is a NuGet feed on appveyor of every build. See the readme.
