### ISSUE TITLE
Question about function shrinkage

### ISSUE THREAD

**Issue by paulyoung** [fscheck/FsCheck#126]
Is there a way to enable this by default or via an attribute?

```fsharp
let foo (m: Result<int, exn>, f: int -> Result<int, exn>, g: int -> Result<int, exn>) =
  ...
```

is much more declarative than

```fsharp
let foo (m: Result<int, exn>, F (_: (int * Result<int, exn>) list ref, f), F (_: (int * Result<int, exn>) list ref, g)) =
  ...
```

**Comment by kurtschelfthout** [comment]
Not right now, maybe it's possible to wrap function automatically in a table so we can shrink them. Would be interesting to try.

Meanwhile, you can write the simpler:

    let foo (m: Result<int, exn>, F (_, f : int -> Result<int,exn>), F (_, g : int -> Result<int,exn>)) = 

which is not too bad.

**Comment by kurtschelfthout** [comment]
Actually, a nice solution is to have an active pattern:

    let (|Fun|) (f:Function<'a,'b>) = f.Value

That lets you write:

    let foo (m: Result<int, exn>, Fun (f : int -> Result<int,exn>), Fun (g : int -> Result<int,exn>)) = 

I think I'll add that.

**Comment by paulyoung** [comment]
If you're not opposed to a solution that would wrap functions I might look into that.

**Comment by kurtschelfthout** [comment]
Sure if you feel like it needs improvement, I'm happy with the active pattern for now.
