### ISSUE TITLE
Question about expecting exceptions

### ISSUE THREAD

**Issue by paulyoung** [fscheck/FsCheck#127]
Would it possible to expect exceptions via attributes?

Borrowing from NUnit, this might look like:

```fsharp
[<Property(ExpectedException="exn")>]
```

or

```fsharp
[<Property>]
[<ExpectedException("exn")>]
```

**Comment by paulyoung** [comment]
To clarify, this would allow:

```fsharp
[<Property(ExpectedException="exn")>]
let ``failure`` (e: exn) =
  Failure e |> dematerialize
```

vs

```fsharp
[<Property>]
let ``failure`` (e: exn) =
  Prop.throws<exn, _> (lazy (Failure e |> dematerialize))
```

**Comment by ploeh** [comment]
If this idea is the same as MSTest's `[ExpectedException]` attribute, everyone pretty much agrees that it was a bad idea. Here's one explanation: http://hadihariri.com/2008/10/17/testing-exceptions-with-xunit

I don't think it'd be a good idea to perpetuate a bad idea when there are better options around.

BTW, you should consider looking at [Unquote](http://www.swensensoftware.com/unquote) for expressing assertions.

**Comment by paulyoung** [comment]
Thanks @ploeh, I'll look into that.

I tried using Unquote but it had some limitations that meant it wasn't an option for me.

**Comment by ploeh** [comment]
BTW, I hope the above comment wasn't too crass. I was on my way out the door when I wrote it, but now that I reread it, I think it looks a little impolite. If so, please accept my apologies.

**Comment by paulyoung** [comment]
Not at all! Nice to hear from you.

**Comment by kurtschelfthout** [comment]
Yeah, not a fan of that suggestion either. Been bitten a few too many times by overly broad attribute-based ExpectedException mechanisms.

Most unit testing frameworks should have support for somethink like ``Assert.Throws<ArgumentException(fun () -> ...)`` nowadays anyway. If not, it's easy to write.
