### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by haf** [fscheck/FsCheck#132]
We're getting very long running-times for FsCheck, 5min+ where it previously only ran for 10-20 seconds.

Debugging and breaking randomly shows FsCheck code being executed.

Is there a timeout setting? I've browsed the code and docs but the only timeout seems to be in on the Outcome data in Property.fs and nothing in the config.

Running on OS X, Mono 4.0.2.

**Comment by kurtschelfthout** [comment]
There is no global timeout in fscheck itself. If you are using a runner that should have a timeout. 

Can you give more info, eg Fscheck versions where it works and doesn't, maybe repro etc. 

Though I won't be able to look until end of this week at the earliest.

**Comment by mausch** [comment]
Does this happen even with MaxNbOfTest = 1 ?

**Comment by lappkast** [comment]
Hi guys,
I'm working on the same codebase and there is no change when I'm trying it with MaxTest = 1.

**Comment by mausch** [comment]
Can you isolate this to a particular test? Is that particular test using some custom generator?

**Comment by kurtschelfthout** [comment]
I believe this may be related to #131 (i.e. my screwup). I have now reverted my changes and released v2.0.6. Please give that a try.

**Comment by kurtschelfthout** [comment]
Closing this assuming it's fixed in 2.0.6. Feel free to re-open with more info if not.
