### ISSUE TITLE
Time until next release?

### ISSUE THREAD

**Issue by pblasucci** [fscheck/FsCheck#135]
Hi, I don't mean to be a bother, but I'm curious if you have any sense of when you'll put out a new NuGet package. I'm giving a small presentation on FsCheck next week. And I want to know if I should leave time to update my code samples to the latest and greatest.

Thanks!

P.S. -- FsCheck is awesome!

**Comment by kurtschelfthout** [comment]
The last one 2.0.6 was about a week ago. Only change since then is the VB.NET extension method fix - are you after that?

**Comment by pblasucci** [comment]
If you could, that'd be awesome. But if not, it's totally cool (and I can get along). Thanks!

**Comment by kurtschelfthout** [comment]
Don't worry, I have magic powers (FAKE). All done: https://github.com/fscheck/FsCheck/releases/tag/2.0.7 (nuget might take a bit before they re-index, or something.)

**Comment by kurtschelfthout** [comment]
Oh, and one more thing - there is an appveyor nuget feed, so in principle you never have to wait for a release - every build builds a (prerelease) nuget package. You could have pulled the one after your PR...see readme for details.

(Of course I realize it's better to demo things that are "officially" released)

**Comment by pblasucci** [comment]
Awesome! Thanks so much!

And I didn't know about the AppVeyor feed... Very cool!

Paul Blasucci
