### ISSUE TITLE
FsCheck and the version of FSharp.Core

### ISSUE THREAD

**Issue by cognociente** [fscheck/FsCheck#136]
New to FsCheck - looks like it would be a great addition to my testing. Great work.

I noticed when adding the FsCheck nuget package to my project that it downgraded the version of FSharp.Core that I was using from 4.4 to 3.1.2.5

Firstly that just doesn't seem correct? If it is, what are the implications for this - as this looks like a really much older version of F#?

**Comment by mausch** [comment]
It's not as old as it might seem.

https://www.nuget.org/packages/FSharp.Core/3.1.2.5 corresponds to FSharp.Core 4.3.1.0 which is F# 3.1
https://www.nuget.org/packages/FSharp.Core/4.0.0.1 corresponds to FSharp.Core 4.4.0.0 which is F# 4.0

As explained in https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#fsharp-core-is-binary-compatible , FSharp.Core is binary compatible and "libraries should generally target the earliest, most portable version of FSharp.Core".

You might need a binding redirect, also explained in that same document.

**Comment by cognociente** [comment]
Thanks.

So if the binding redirects are set in an app.config file to "point to" 4.4 will the nuget installer "know" not to overwrite the FSharp.Core dll in my references already or does this work in some other manner?

**Comment by mausch** [comment]
NuGet is usually aware of binding redirects.
