### ISSUE TITLE
Convert a test in a properties based test in C#

### ISSUE THREAD

**Issue by gsscoder** [fscheck/FsCheck#137]
Given an XUnit test like this:
```csharp
[Theory]
[InlineData(new[] {"-123"}, -123L)]
[InlineData(new[] { "-1" }, -1L)]
[InlineData(new[] { "-9223372036854775807" }, -9223372036854775807)] // long.MaxValue * -1
public void Parse_negative_long_value(string[] arguments, long expected) {
  // Fixture setup in attributes
  // Exercize system 
  var result = InvokeBuild<Simple_Options>(arguments);
  // Verify outcome
  ((Parsed<Simple_Options>)result).Value.LongValue.ShouldBeEquivalentTo(expected);
  // Teardown
}
```

What I'd like to do is remove ``InlineData`` attribute and let **FsCheck** generate random data for me.

I've tried using `Prop.ForAll` and `Property` attribute, but still experiencing some difficulties.

Full test class source code: https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L62.

Maybe could be a simple solution add a new **F#** to the solution, explicitly targeted to properties based testing?

Thanks in advance and thanks for sharing this great tool.

**Comment by moodmosaic** [comment]
One way of doing that, is to create a new F# Class Library project, open the Package Manager Console in Visual Studio and execute:

```
install-package FsCheck.Xunit
```

Instead of `Theory` and `InlineData` just use `Property` to have FsCheck generate test cases for your test (or rather, *property*):

```f#
module Tests

open FsCheck.Xunit

[<Property>]
let ``Parse negative long value`` (arguments : string array) (expected : int) =
    // Define your test/property here.
    ()
```

**Comment by kurtschelfthout** [comment]
Pretty much everyhing that works in F# should work in C#. Personally I would use F# but really as far as FsCheck is concerned there are only syntactic differences. So it's your call.

I can't really comment specifically unless you tell me more about the actual problems.

The one shift you should make is that you now just encode a list of inputs with their corresponding expected outputs. With FsCheck, you should figure out the properties that hold based on random inputs, i.e. if you're going to just replace Theory and InlineAttribute with Property, then clearly things won't work because FsCheck will generate some random arguments, and some random and completely independent expected results, and so your test will fail unless you are _very_ lucky :)

Instead, for this particular property, I would (perhaps somewhat counter-intuitively) randomly generate the expected result (i.e. a negative int), then in the test convert that to string manually, let your arg parser parse it, and check that the result is the original int.

**Comment by ploeh** [comment]
+1 to all what @kurtschelfthout said.

Additionally, it looks like you're testing some parsing logic. In such cases, it'd be natural also having a function that goes the other way: from `long` to `string[]`.

A natural property, then, would be to establish that you can round-trip without loss of information.

For more inspiration, you may want to read @swlaschin's [introduction to property-based testing patterns](http://fsharpforfunandprofit.com/posts/property-based-testing-2).

**Comment by gsscoder** [comment]
@moodmosaic, @kurtschelfthout, @ploeh thanks for valuable information.

I'll try to _make the point_ my self and eventually post here.

**Comment by kurtschelfthout** [comment]
Ok, feel free to start new issues for questions..

**Comment by gsscoder** [comment]
@kurtschelfthout, thanks for detailed info.

I'll probably follow the suggestion of having FsCheck generating a random value, putting it in args sequence as string and re-parse it.

For keeping things simple.

I'll post when I start that experiment and eventually I'll open a new issue if I got a problem.

Thanks again to everyone in discussion. :smile: And thanks for sharing this great tool that helps build better software to others... :+1:

**Comment by gsscoder** [comment]
@kurtschelfthout, @ploeh, @moodmosaic,
to better understanding the concept of properties testing (_easy when reading docs, but another thing when writing code..._).

I've limited the creation of very simple **property test** from another project (from which CommandLineParser references some file via Paket source inclusion).

This is the test: https://github.com/gsscoder/CSharpx/blob/master/tests/CSharpx.Tests/MaybeTests.cs#L16.

A code review is simple are just few lines of **C#**. (I opted for **C#** test project in this case, but in CommandLineParser I'll add a new **F#** testing project, probably).

Thanks to everyone! :)

**Comment by kurtschelfthout** [comment]
Looks close. But your test will never fail as written, or rather, any failure will not be propagated to the test framework. Instead of `QuickCheck` use `QuickCheckThrowOnFailure`.

Alternatively, use `Property` instead of `Fact`, then you can take the int as an argument, and lose the `Prop.ForAll` and `QuickCheck` altogether.

**Comment by gsscoder** [comment]
@kurtschelfthout, thanks for suggestion... 

But it seems that every time I try to use `Property[Attribute]` the project won't compile. Am I missing something?

**Comment by gsscoder** [comment]
Can you point me to an example? Or explain here? Thanks in avance for everything... :)

**Comment by ploeh** [comment]
It ought to be straightforward to use `[Property]` in C#. This compiles, runs, and passes on my machine:

```C#
[Property]
public void MyProperty(int i, string txt)
{
    var actual = txt + i;
    Assert.NotNull(actual);
}
```

**Comment by gsscoder** [comment]
I've added a second property `MyProperty2` to capture VS error when mouse is over.
![propertydoesntcompile](https://cloud.githubusercontent.com/assets/1194228/9566155/2860e540-4ef8-11e5-9ee5-af67c09ceec8.png)
:(

**Comment by ploeh** [comment]
Which NuGet packages do you have installed?

**Comment by kurtschelfthout** [comment]
Use the full type name, Fscheck.Xunit.Property.

**Comment by gsscoder** [comment]
Sorry, I've already tested this path, but nothing... Here the proof:
![schermata 2015-08-30 alle 15 30 52](https://cloud.githubusercontent.com/assets/1194228/9567451/3060899c-4f2c-11e5-807c-161e083e13d8.png)
It's weird, isn't it?

**Comment by ploeh** [comment]
@gsscoder, I think everyone here would be happy to help, but I can't tell what the problem is based on incomplete screen shots. Can you describe a simple way to reproduce this behaviour?

**Comment by moodmosaic** [comment]
@gsscoder, similar to what @ploeh [wrote](https://github.com/fscheck/FsCheck/issues/137#issuecomment-136101235), do you have [FsCheck.Xunit](https://www.nuget.org/packages/FsCheck.Xunit/) installed?

If so, could you try to uninstall xUnit.net and FsCheck.Xunit and then install *only* FsCheck.Xunit? This installs the appropriate version of xUnit.net, just in case you're running into some versioning issue(s)...

**Comment by gsscoder** [comment]
@ploeh , @moodmosaic 
I've simply copy and pasted @ploeh sample to my test class of CSharpx, the problem is that no matter I define with full name or note, `PropertyAttribute` is not (I don't know how to say...) **recognized** by the compiler.

Just fork/clone CSharpx and try to add a simple test using `Property` attribute. I'm not able to do this...

Hope this helped. :)

@moodmosaic, I'll try what you say. For info I've installed it via Paket using also appropriate setting for handling common XUnit problems (see paket.references on root).

If I need to post more, please tell me.

Thanks again...

**Comment by gsscoder** [comment]
@ploeh, @moodmosaic:
all packages: https://github.com/gsscoder/CSharpx/blob/master/paket.dependencies
test project: https://github.com/gsscoder/CSharpx/blob/master/tests/CSharpx.Tests/paket.references

**Comment by ploeh** [comment]
Which NuGet *versions* do you actually have in the project?

**Comment by gsscoder** [comment]
From [paket.lock](https://github.com/gsscoder/CSharpx/blob/master/paket.lock):
**FsCheck:**
```
    FsCheck (2.0.7)
      FSharp.Core (>= 3.1.2.5)
    FsCheck.Xunit (2.0.7)
      FsCheck (>= 2.0.7)
      xunit (>= 1.9.2)
```
**Xunit**:
```
    xunit (2.0.0)
      xunit.assert (2.0.0)
      xunit.core (2.0.0)
    xunit.abstractions (2.0.0)
    xunit.assert (2.0.0)
    xunit.core (2.0.0)
      xunit.extensibility.core (2.0.0)
    xunit.extensibility.core (2.0.0)
      xunit.abstractions (2.0.0)
    xunit.runner.console (2.0.0)
    xunit.runner.visualstudio (2.0.1) - version_in_path: true
```

Can I post something else to help you help me? (Thanks for your patience and availability). :)

**Comment by ploeh** [comment]
Do you notice anything odd regarding the *FsCheck.Xunit* dependency requirements, in comparison with what you actually have?

**Comment by gsscoder** [comment]
@jhamm, thanks for informations. As first I'll try if lowering xunit will not affect test project, otherwise I can stay with current `Prop.ForAll`.

I'm not talking of CSharpx that test part is under development, but of CommandLineParser on which I want to use FsCheck but it has already a consolidated test code base.

I'll post here my results anyway.

Thanks to every person that helped! :)

**Comment by gsscoder** [comment]
@jhamm & other people who kindly helped,
I've created another branch with `xunit < 2.0` for enabling FsCheck integration, [fsc-xunit19](https://github.com/gsscoder/CSharpx/tree/fsc-xunit19).

[This](https://github.com/gsscoder/CSharpx/blob/fsc-xunit19/tests/CSharpx.Tests/MaybeTests.cs) is the direct link to altered source file, so you can check if the test was correctly implemented from `Prop.ForAll` to `Property` attribute version.

It lasts an issue (that maybe known to you)... Downgrading to xunit, removed Visual Studio test discovery.
However I was able to run tests form terminal using `build test`.

Now I'm asking myself if it could be better keep `Prop.ForAll` (without downgrading and without integration) at least until the use of FsCheck grows in an existing test project. In a second moment I could re-factor with downgrading xunit for fscheck integration.

Or maybe this is not a real issue and someone know how VS can discover tests when using `xunit < 2.0`.

Anyway I'm very glad I've done a lot of steps in my understanding of **FsCheck** and property based testing.

Thanks again! Looking forward for further comments. :)
