### ISSUE TITLE
Ad hoc way to get a random number in a range

### ISSUE THREAD

**Issue by ploeh** [fscheck/FsCheck#138]
Does FsCheck define an ad hoc way to get a random number in a range? Particularly, a way that works with *FsCheck.Xunit*?

Let's say that I want a randomly generated number in the range 1-100, or 1-8. While I could use a custom *Arbitrary*, this is sometimes too heavy-handed. Besides, a custom arbitrary affects *all* values of a particular type (`int`, `byte`, `float`, etc.), and that's sometimes undesirable, because I want most numbers to be unconstrained, except for one or two. A motivating example is described below.

If there's no current way to do this, I'd like to suggest a solution:

We could add a function that would take any number, and [map it to the corresponding number in the required range](http://stackoverflow.com/a/929107/126014).

It might look like this:

```F#
let y = Range.map Int32.MinValue Int32.MaxValue 1 100 x
```

This would take the 32-bit integer `x` and map it to a value in the range 1-100. This could be useful when FsCheck provides an unbounded `int` value.

The first two arguments are the original range from which `x` was drawn, in this case all 32-bit integers. The function can be partially applied so that it can be used in a more readable manner:

```F#
let y = x |> between 1 100
```

If there's no existing feature to address this requirement, and this suggestion sounds like an appropriate solution, I'll be happy to make a pull request.

# Motivating example

I often need to get a number in a predetermined range. One recent example that came up was that I was doing Conway's Game of Life, and I wanted to express the property that *Any live cell with more than three live neighbours dies*.

I already have a function that gives me all (8 of) the neighbouring cells of a cell, so in order to express this test case, I want to pick a number of neighbours from 4 to 8, and then select that number of neighbouring cells as live cells.

It'd be nice to be able to express that like this:

```F#
[<Property>]
let ``Any live cell with more than three live neighbours dies``
    (cell : int * int)
    (neighborCount : int) =
    let neighborCount = neighborCount |> between 4 8

    // The rest of the property goes here...
```

In this example, a custom *Arbitrary* is undesirable, because I want the integers in `cell` to be unconstrained.

**Comment by mausch** [comment]
It sounds like you're describing a [conditional property](https://fscheck.github.io/FsCheck/Properties.html). It will *discard* test cases that don't match the condition though, so it's easy to run out of test cases. But sometimes it's good enough for experimentation when writing an Arbitrary feels overkill as you describe.

Personally, I think it's not worth it... writing a Gen in F# can be just a couple of lines and avoid the problem of running out of test cases.

**Comment by ploeh** [comment]
I know about conditional properties, but they have exactly the problem that they often run out of test cases - particularly if the desired range is narrow.

> writing a Gen in F# can be just a couple of lines and avoids the problem of running out of test cases

How would you do this without affecting *all* values of the type that the Gen targets?

**Comment by kurtschelfthout** [comment]
It's not clear how it would work; in particular, wouldn't it be forced to either discard cases (in which case the type is different, because the result would be a Property) or skew the distribution greatly?

**Comment by ploeh** [comment]
It would work like [this](http://stackoverflow.com/a/929107/126014). Does that skew the distribution?

I suppose it depends on what the initial distribution is...

**Comment by mausch** [comment]
> How would you do this without affecting all values of the type that the Gen targets?

As described in "Quantified properties" in https://fscheck.github.io/FsCheck/Properties.html .

**Comment by kurtschelfthout** [comment]
@ploeh that wouldn't skew the distribution, except you don't know the "old range".

**Comment by kurtschelfthout** [comment]
Overall, it seems like this is better tackled using generators, but perhaps there should be an `Arbitrary` instance, i.e. gen + shrinker, that does this. Something like `Gen.choose`, i.e. `Arb.choose (low, high)`. Then use `Prop.forAll`.

I've also been thinking but have not put into practice, that in F# at least we can make properties a bit more syntactically pleasing by using active patterns. For example, you can imagine writing something like:

    [<Property>]
    let test(IntBetween (4,8) i, FloatBetween (5.0,8.5) f) = ...

Not 100% sure that can be made to work though; the active pattern would somehow have to be able to replace the arbitrary instance, perhaps by exposing some special type.

**Comment by ploeh** [comment]
@mausch, thank you, I didn't know about `Prop.forAll`. That turns out to address the issue elegantly and flexibly, even with *FsCheck.Xuni*:

```F#
[<Property>]
let ``Any live cell with more than three live neighbours dies``
    (cell : int * int) =

    let nc = Gen.elements [4..8] |> Arb.fromGen
    Prop.forAll nc (fun neighborCount ->
        let liveNeighbors =
            cell
            |> neighbors
            |> shuffle
            |> Seq.take neighborCount
            |> Seq.toList

        let actual = getNextState (cell::liveNeighbors) cell

        Dead =! actual)
```

This almost deserves a blog post, unless you think there's a good fit for it in the documentation somewhere!(?)

The only thing I'm not 100 % happy with is the extra indentation caused by the multi-line lambda function, but I *am* 95 % happy :smile: 

For my sake we can close the issue again.

**Comment by kurtschelfthout** [comment]
Ok. I guess it is in the documentation, though if anything should be clarified, feel free to PR for that.
