### ISSUE TITLE
Strong name sign the FsCheck assembly.

### ISSUE THREAD

**Issue by melun** [fscheck/FsCheck#143]
Lack of strong name sign makes the assembly unusable as-is in scenarios where the product/test assemblies are themselves strong name signed.

To support using the FsCheck assembly in these scenarios I would like to request strong naming it.

**Comment by mausch** [comment]
Please see https://github.com/fscheck/FsCheck/issues/73

**Comment by kurtschelfthout** [comment]
Yes, not happening I'm afraid.
