### ISSUE TITLE
Q: reading FsCheck error message, difference between "orginal" and "shrunk"

### ISSUE THREAD

**Issue by gsscoder** [fscheck/FsCheck#148]
When a test fail an error message like this is generated:
```
Falsifiable, after 1 test (1 shrink) (StdGen (54597187,296056740)):
Original:
NonNull ","
Shrunk:
NonNull ""
with exception: ...
```
What's the difference between **Original** and **Shrunk** generated data?

R. Giacomo

**Comment by ploeh** [comment]
["FsCheck also shrinks the counter example: it tries to find the minimal counter example that still fails the property."](https://fscheck.github.io/FsCheck/QuickStart.html)

**Comment by gsscoder** [comment]
Thanks, I missed it while reading docs. :+1:
