### ISSUE TITLE
Using NonNull<_> wrapper doesn't prevent null values to be generated

### ISSUE THREAD

**Issue by gsscoder** [fscheck/FsCheck#149]
```csharp
Prop.ForAll<NonNull<string>>(
  x =>  {
    var value = x.As<string>();
    // ...
  }).QuickCheckThrowOnFailure();
```
When debugging this code the first value I got is always `null`.

Thanks in adavance!
R. Giacomo

**Comment by mausch** [comment]
No idea where that `As` method comes from, but it doesn't seem to come from FsCheck... 

Use the `Get` method to get the underlying value from a NonNull:

```csharp
            Prop.ForAll<NonNull<string>>(
              x => {
                var value = x.Get;
                Assert.IsNotNull(value);
              }).QuickCheckThrowOnFailure();

```

**Comment by gsscoder** [comment]
@mausch, thanks again! It comes from fluent assertions.

Now the behaviour is correct as expected... My fault!

:)
