### ISSUE TITLE
Why add branch to prerelease build?

### ISSUE THREAD

**Issue by ctaggart** [fscheck/FsCheck#150]
Why is the branch being added to the prerelease build name?

https://ci.appveyor.com/project/kurtschelfthout/fscheck/history

![image](https://cloud.githubusercontent.com/assets/80104/9888882/7a885c84-5bac-11e5-87d0-493852f50619.png)

**Comment by kurtschelfthout** [comment]
I added the name in the release notes on a few branches because I find it convenient to figure out which version to install from the nuget UI.

**Comment by ctaggart** [comment]
ok
