### ISSUE TITLE
Run FsCheck tests from Visual Studio Test Explorer?

### ISSUE THREAD

**Issue by ctaggart** [fscheck/FsCheck#151]
Is it possible to run FsCheck tests from Visual Studio Test Explorer? Using xunit, I can do so by referencing `nuget xunit.runner.visualstudio version_in_path: true`. This doesn't appear to work for FsCheck.Xunit tests.

**Comment by ctaggart** [comment]
I found this already listed on stackoverflow.
http://stackoverflow.com/questions/24642026/properties-throw-off-xunit-and-the-test-explorer

Test discovery is failing silently without binding redirects. In my case, I just needed to redirect FSharp.Core by adding an `App.config` to the test project with:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Not as important, but worth mentioning that I am also trying out the latest build with xunit2 support by putting this in my `paket.dependencies`:
```
source https://ci.appveyor.com/nuget/fscheck

nuget FsCheck 2.1.0-xunit2-b312
nuget FsCheck.Xunit 2.1.0-xunit2-b312
```

**Comment by kurtschelfthout** [comment]
Yes. Suggestions welcome to make this more obvious. I actually thought nuget or even vs would insert redirects automatically.
