### ISSUE TITLE
Make the property-based tests easier to read

### ISSUE THREAD

**Issue by moodmosaic** [fscheck/FsCheck#163]
Now that we use Unquote (which is great!), we could make the property-based tests easier to read.

As @ploeh wrote in #162:

>With the built-in operators `=!` and `<>!`, the assertions become so terse that they almost 'drown' in the test. If we stick with these operators, I would recommend adopting this heuristic for formatting tests: http://blog.ploeh.dk/2013/06/24/a-heuristic-for-formatting-code-according-to-the-aaa-pattern

I could happily send a Pull Request during the next couple of days, if you'd like to follow this direction.

**Comment by ploeh** [comment]
Clearly I think this is a good idea, but I'll let @kurtschelfthout decide, as FsCheck is his code base.

**Comment by kurtschelfthout** [comment]
Sure, go for it.
