### ISSUE TITLE
Use paket to create NuGet packages

### ISSUE THREAD

**Issue by sideeffffect** [fscheck/FsCheck#168]
in light of https://github.com/fscheck/FsCheck/pull/166#issuecomment-147527064

**Comment by kurtschelfthout** [comment]
Thanks for creating the issue.

To be clear, we're talking about changing this target: https://github.com/fscheck/FsCheck/blob/master/build.fsx#L201-L219

to use Paket.Pack etc.

**Comment by sideeffffect** [comment]
started working on it

**Comment by sideeffffect** [comment]
being solved in the PR https://github.com/fscheck/FsCheck/pull/170
