### ISSUE TITLE
SmartCheck for FsCheck?

### ISSUE THREAD

**Issue by rassilon** [fscheck/FsCheck#177]
Has anyone thought about FsCheck generic shrinking in the context of Haskell's SmartCheck?

I'm fairly new to F# and not sure if similar things are possible.

Thoughts?

**Comment by mausch** [comment]
FWIW I've been *wanting* it for some time... though never badly enough to actually implement it myself :)

**Comment by kurtschelfthout** [comment]
Yeah it should be possible. Same as @mausch I've been toying with the idea and read the paper, but not axed enough to implement myself...

**Comment by moodmosaic** [comment]
This [could *probably* be easier through a (hypothetical) Jack integration](https://github.com/jystic/dotnet-jack/issues/47).
