### ISSUE TITLE
FSharp 3.1 => FSharp 4.0

### ISSUE THREAD

**Issue by xenocons** [fscheck/FsCheck#178]
Hello,

When installing FsCheck using nuget into a project that utilises F# 4.0, I get the following error in nuget:

Attempting to resolve dependencies for package 'FsCheck.2.2.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'FSharp.Core 4.0.0.1' is not compatible with 'FsCheck 2.2.0 constraint: FSharp.Core (≥ 3.1.2.5 && < 3.1.3)'.

Is there any particular reason why FsCheck forces this constraint? Paket seems to handle the constraint fine, now that I have moved to paket instead of nuget, but I am curious to find out why

**Comment by kurtschelfthout** [comment]
Sorry, this is my bad, we moved to paket for creating the NuGet packages and in the process I changed the constraints. I will fix and release 2.2.1 tonight.

Thanks for reporting.
