### ISSUE TITLE
Gen.fromArray: 'a array -> 'a seq

### ISSUE THREAD

**Issue by gdennie** [fscheck/FsCheck#182]
I was search for the following and was surprise that it does not appear to exists.

The idea is to permit the description a value as the permutation `(a1,...,aN)` of values from sets `(T1,...,TN)` sampled by corresponding arrays `(A1,...,AN)`.

Hence,

    let! a1 = Gen.fromArray A1
    let! a2 = Gen.fromArray A2
    ...
    let! aN = Gen.fromArray AN

    return (a1,...,aN)

    //for example string production:  return a1+a2+...+aN

Perhaps this is regressive in that it is just a more elaborate form of sample based testing?

**Comment by kurtschelfthout** [comment]
Is that equivalent to `Gen.arrayOf (Gen.elements a1)`?

**Comment by gdennie** [comment]
Actually, it is exactly `Gen.elements A1`.
:)

**Comment by kurtschelfthout** [comment]
OK :)
