### ISSUE TITLE
Errors when generating documentation on Linux/Mono

### ISSUE THREAD

**Issue by sideeffffect** [fscheck/FsCheck#185]
There is a non-fatal error when generating documentation: [`System.Exception: Cannot create directory '/home/travis/build/fscheck/FsCheck/docs/tools/../output/ja/.'`](https://travis-ci.org/fscheck/FsCheck/builds/91248000#L1777)
probably something to do with [`Literate.ProcessDirectory`](https://github.com/fscheck/FsCheck/blob/master/docs/tools/generate.ja.fsx#L71) (`replacements` parameter)
unfortunately I have no idea how to fix this

**Comment by kurtschelfthout** [comment]
As I said on the PR, there are a few other as well, and it does look fatal. Not sure if any docs are actually generated, but it looks like not much at best.

**Comment by sideeffffect** [comment]
the thing is there are indeed many html files generated -- for both en and jp. I can't say that those are all, but I suspect this part works.
Regarding the `.xml` documentation, yes that is missing. I know Mono can generate it, I've seen it in other F# projects on Mono. I just don't know how to make it so.

maybe @tpetricek would know since he's the author of `Literate.ProcessDirectory` (afaik)

**Comment by kurtschelfthout** [comment]
For the docs actually I think it's just a casing issue. fsc generates FsCheck.XML and it looks for FsCheck.xml. Perhaps just changing the case in FsCheck.fsproj works.

**Comment by kurtschelfthout** [comment]
And this:

`System.Exception: Cannot create directory '/home/travis/build/fscheck/FsCheck/docs/tools/../output/ja/.'`

is perhaps because the `.` at the end?

**Comment by kurtschelfthout** [comment]
Looks like that did it.
