### ISSUE TITLE
FsCheck installing FSharp.Core

### ISSUE THREAD

**Issue by gdennie** [fscheck/FsCheck#187]
This package, or the current version of it available from Nuget, is installing FSharp.Core v3.1.2.5. This process overwrites the provided VS version, in my case v4.4.0.0 of VS2015 Community Edition. The consequence is version conflicts causing execution failure at *runtime*. Fortunately, this occurred during unit tests.

The problem is resolved by replacing the referenced FSharp.Core with the VS provided version at: 
`%ProgramFiles(x86)%\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll`

**Comment by ploeh** [comment]
What happens if you do the following?

```
> Update-Package FSharp.Core
```

**Comment by gdennie** [comment]
It updates to v4.0.0.1, the latest version on Nuget.

**Comment by ploeh** [comment]
Hmm.... Perhaps we should look into publishing a newer version of *FSharp.Core* on NuGet...

/cc @forki @tpetricek

**Comment by forki** [comment]
There are newer versions? 
BTW: assembly version <> nuget package version 
Just to make it interesting ;-)

**Comment by ploeh** [comment]
I keep forgetting that :blush:

**Comment by kurtschelfthout** [comment]
No idea what to do about this. The version constraint is >= FSharp.Core is 3.1.2.5. That seems correct to me, as that is the lowest version FsCheck will work with, and newer versions of FSharp.Core should be backwards compatible.

We can add the dependency to the package which mostly works (except for this, apparently) and is convenient for C#/VB.NET users. Or we can remove it, in which case things become a lot less clear (i.e. users don't know about the dependency, or which version to depend on, manual app.config redirects are needed etc).

So unless you have any suggestions I don't really know what to do about this.

**Comment by forki** [comment]
nuget is installing the lowest matching transisitve dependency by default.
I don't think the issue is in FsCheck.

**Comment by ploeh** [comment]
> The version constraint is >= FSharp.Core is 3.1.2.5. That seems correct to me, as that is the lowest version FsCheck will work with

Completely agree :+1: 

FWIW, I've never had this problem - not even with a brand-new F# project on F# 4.0 on .NET 4.6 (I just tried).

Steps to repro?

**Comment by kurtschelfthout** [comment]
@gdennie are you installing FsCheck 2.2.2? In an earlier version of the package the constraint for FSharp.Core was wrong. That's the only thing I can think of...

**Comment by gdennie** [comment]
Yes, version 2.2.2.

The following is a package manager console log install of FsCheck on a F#
.Net Framework 4.6, F# 4.0 (FSharp.Core, 4.4.0.0) project:

    PM> install-package fscheck
    Attempting to gather dependencies information for package
'fscheck.2.2.2' with respect to project 'test4', targeting
'.NETFramework,Version=v4.6'
    Attempting to resolve dependencies for package 'fscheck.2.2.2'
with DependencyBehavior 'Lowest'
    Resolving actions to install package 'fscheck.2.2.2'
    Resolved actions to install package 'fscheck.2.2.2'
    Package 'FSharp.Core.3.1.2.5' already exists in folder
'C:\temp2\HtmlProvider\packages'
    Added package 'FSharp.Core.3.1.2.5' to 'packages.config'
    Successfully installed 'FSharp.Core 3.1.2.5' to test4
    Package 'FsCheck.2.2.2' already exists in folder
'C:\temp2\HtmlProvider\packages'
    Added package 'FsCheck.2.2.2' to 'packages.config'
    Successfully installed 'FsCheck 2.2.2' to test4
    PM>

**Comment by kurtschelfthout** [comment]
Yeah I have no problem reproducing. Just don't think there's anything we can do here.

**Comment by forki** [comment]
that's actually correct nuget behaviour. It doesn't know about your F# compiler version.

With paket it will install latest F# core which works also with older compilers.

**Comment by gdennie** [comment]
Other packages don't appear to create this effect. For example, XUnit, FSharp.Data, etc.

**Comment by forki** [comment]
Fsharp.data has no nuget dependency on fsharp.core. That creates other
issues

**Comment by kurtschelfthout** [comment]
@gdennie the guidance you reference there is to not add FSharp.Core as part of the nuget package, i.e. in the lib folder. That's not what FsCheck is doing.

Further down it talks about adding a dependency to the FSharp.Core _NuGet package_, which it seems somewhat more on the fence about. (" It is not yet normal to reference FSharp.Core via this package, though it is used by some F# library packages" -> not exactly guidance :) )

**Comment by gdennie** [comment]
The mystery of the mysterious FSharp.Core inclusion depends. :)

Fortunately the work around of forced singular removal of the inclusion with a manual reference to a more current dll, as noted above, exists.

**Comment by kurtschelfthout** [comment]
Yes, not ideal, but don't see a better solution unfortunately.

**Comment by mikhailshilkov** [comment]
When I replace the version of FsCore, the xUnit test runner (both VS and console) stops detecting the tests in solution. How do I work that around?

**Comment by kurtschelfthout** [comment]
Make sure all versions of FSharp.Core in your solution are the  same, and make sure the test assembly has an app.config with binding redirects for FSharp.Core to the latest version.

**Comment by mikhailshilkov** [comment]
Thank you @kurtschelfthout, binding redirect makes the trick
