### ISSUE TITLE
Verbose flag does not output anything

### ISSUE THREAD

**Issue by isaacabraham** [fscheck/FsCheck#188]
Using VS2015, latest version of XUnit and FSCheck, if I run some FSCheck tests using the ```PropertyAttribute``` with the ```Verbose``` flag set to true, I do not receive any output via the VS test runner.

**Comment by kurtschelfthout** [comment]
I seem to have hosed my VS, I can't even run simple facts with the VS test runner and xunit plugin. It just hangs indefinitely. I don't really have an idea on how to fix it. I'll give it a try on another machine later, perhaps I'll have more luck. (Gotta love it when you have to change the hardware to get some software to work.)

Are you are using xunit.runner.visualstudio 2.1.0?

**Comment by kurtschelfthout** [comment]
Ah, it magically started working again. How wonderful. Can repro.

**Comment by isaacabraham** [comment]
If you're using Paket make sure you tell it to specify paths for the XUnit dependency otherwise it won't work.

**Comment by kurtschelfthout** [comment]
I think I sort of understand what needs to happen - xunit needs to get the messages on its `IMessageBus`. Can't just write to `Console` anymore because of the async-ness. 

Luckily there are only a few possible options so it's easy to figure out which one to send - OH NOES there are at least thirty (three zero) possible message and none of them are a concrete class.

https://github.com/xunit/xunit/tree/fe8d78df7cfec55ddab93c29ea96b0032ca998a8/src/abstractions/xunit.abstractions/Messages

Sigh.

**Comment by isaacabraham** [comment]
@bradwilson can you save us some time and advise the one to use? Just need to know how to send some arbitrary text to VS test runner output.

**Comment by bradwilson** [comment]
Right, in v2 we don't capture anything that we used to (stdout, stderr, Debug, Trace, etc.).

The closest equivalent now is [`ITestOutputHelper`](https://github.com/xunit/xunit/blob/d73da9e98d5942145c6446657c67890e3e56f047/src/abstractions/xunit.abstractions/TestCases/ITestOutputHelper.cs). You take it as a constructor argument ([example](https://github.com/xunit/samples.xunit/blob/0dda91312e59162392833aff80623b4fa29904c1/TestOutputExample/Example.cs)), and you can use it in the ctor, in the test, and in the Dispose method.

**Comment by isaacabraham** [comment]
@bradwilson can that also be used by types that inherit from [<FactAttribute>]? This isn't needed for the developer writing the tests but for FsCheck's [<PropertyAttribute>]. It needs to send output to the test runner.

**Comment by kurtschelfthout** [comment]
Thanks for answering Brad. As Isaac explains, this is in an extension, it needs to basically send output to the test runner while the test is running. I got as far as "I need to queue a message on the IMessageBus" in the `RunAsync` override: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L116

But which message is appropriate?

**Comment by bradwilson** [comment]
The implementation [`TestOutputHelper`](https://github.com/xunit/xunit/blob/5e24b60013fa7c1783edb0f11f025624feaaad4e/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs#L59) creates an instance of `TestOutput`, which implements [`ITestOutput`](https://github.com/xunit/xunit/blob/5e24b60013fa7c1783edb0f11f025624feaaad4e/src/abstractions/xunit.abstractions/Messages/ITestOutput.cs).

**Comment by kurtschelfthout** [comment]
Thanks @bradwilson. I coudn't actually get the `QueueMessage` with `TestOutput` to work, so I used the `OutputHelper` directly to accumulate output then passed it to the finished messages. That seems to do the trick.
