### ISSUE TITLE
F# 4.0 support?

### ISSUE THREAD

**Issue by AnthonyLloyd** [fscheck/FsCheck#190]
I'm getting the following exception when switching to F# 4.0:

System.InvalidCastException : Unable to cast object of type 'Arrow@212-2[System.Int32,System.Boolean]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Boolean]]'.
      Stack Trace:
           at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
        C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs(275,0): at FsCheck.Runner.check[a](Config config, a p)
        C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs(401,0): at FsCheck.Check.QuickThrowOnFailure[Testable](Testable property)

Built in empty VS 2015 F# proj with following code. Tested with .Net 4.5 & 4.6.

    let f i = i - i = 0
    FsCheck.Check.QuickThrowOnFailure f

It works if I switch to F# 3.1.

Let me know anything else I can do to help

**Comment by kurtschelfthout** [comment]
If you put in the necessary bindingredirect it should work, given FSharp.Core is backwards compatible.

See e.g. here: https://github.com/fsprojects/Paket/issues/929

**Comment by AnthonyLloyd** [comment]
Thanks
