### ISSUE TITLE
Fscheck Xunit MaxTest property > 1 but running only once

### ISSUE THREAD

**Issue by kevnave** [fscheck/FsCheck#191]
Hello,

We have installed the following XUnit packages on our solution : 

`nuget xunit @= 2.1.0 framework: >= net45`
`nuget xunit.abstractions @= 2.0.0 framework: >= net45`
`nuget xunit.assert @= 2.1.0 framework: >= net45`
`nuget xunit.core @= 2.1.0 framework: >= net45`
`nuget xunit.extensibility.core @= 2.1.0 framework: >= net45`
`nuget xunit.extensibility.execution @= 2.1.0 framework: >= net45`
`nuget xunit.runner.visualstudio @= 2.1.0 framework: >= net45`

Since we want to run a given test several times with randomly generated value, we have set the property MaxTest to a value > 1, however, the test is run once and once only

`[<Property(MaxTest=10)>]`
`member this.mytest(param: Param)  =  ...`

Do you know what could be the issue ?

Cheers

**Comment by kurtschelfthout** [comment]
Not really from what you've told me. Can you give us the full code of what you're doing? Normally FsCheck runs each test a 100 times by default, so you shouldn't have to change any settings to get what you want.

**Comment by kevnave** [comment]
Hello,

I have just updated my previous post with more details. 
Do you know what could be missing or if there is some known issues with xunit.runner 2.1.0?

Thanks

**Comment by kurtschelfthout** [comment]
That should work. How are you determining the test runs only once?

**Comment by kevnave** [comment]
------ Run test started ------
[xUnit.net 00:00:00.4944520]   Starting:    CIServiceTests
[xUnit.net 00:00:09.6924293]   Finished:    CIServiceTests
========== Run test finished: 1 run (0:00:09.887896) ==========

**Comment by kurtschelfthout** [comment]
Sure, xunit only sees one test but it did call your method multiple times. Check the test output, for example, it'll tell you. Or set a breakpoint.

**Comment by kevnave** [comment]
You are right
Thank you
