### ISSUE TITLE
Error with FSharp.Core 4.4.0.0

### ISSUE THREAD

**Issue by nicolocodev** [fscheck/FsCheck#192]
Using VS2015 and Target F# Runtime: F# 4.0 (FSharp.Core, 4.4.0.0). I'm using the FsCheck.Xunit 2.2.3 package and running from xunit console runner I get the following exception: 

`      System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
      ---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
      -------- System.MissingMethodException : Method not found: 'FsCheck.Arbitrary'1<!!0> FsCheck.Arb.Filter(Microsoft.FSharp.Core.FSharpFunc'2<!!0,Boolean>, FsCheck.Arbitrary'1<!!0>)'.
      Stack Trace:
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
           at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   ...`
I found a [similar case on StackOverflow](http://stackoverflow.com/questions/14530385/exception-upon-using-fscheck). To fix this I created an `app.config` file and added the bindingredirect:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.3.1.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
</configuration>
```
Is this the best solution? am i missing something?

**Comment by kurtschelfthout** [comment]
That's it, see e.g. #190.
