### ISSUE TITLE
FsCheck Xunit runner fails at least one test VS2015

### ISSUE THREAD

**Issue by varon** [fscheck/FsCheck#195]
When running in VS2015 Community from the Resharper test runner, I receive the following warning for one of my tests using a custom generator.

```
System.Reflection.TargetInvocationException

Exception has been thrown by the target of an invocation.

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 318
   at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@127(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.Xunit\PropertyAttribute.fs:line 146

System.ArgumentException

An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 27
   at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 20
   at FsCheck.Testable.Arrow@212-2.FsCheck-Testable-Testable`1-Property(FSharpFunc`2 ) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 213
   at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275

```
*(My name isn't Kurt either)*

All other tests pass.

If i Disable this test, more tests (which previously passed) fail. It seems to be some kind of hash collision on the custom generator types.

Please let me know if you require any more information on this.

**Comment by kurtschelfthout** [comment]
Thanks for the report. Can you come up with a repro?

**Comment by varon** [comment]
I'll see if I can come up with a minimal example.

**Comment by varon** [comment]
Working through my code, it seems as though using `Arb.generate<string>` or Arb.Default.StringWithoutNullChars() in a generator seems to fail.

If I swap to this, it seems to solve the issue.
```
    Arb.generate<char>
    |> Gen.arrayOf
    |> Gen.map (fun a -> String(a))
```

This might be related to a strange phenomena I've noticed - when I define a custom type with a string generation function, it seems to replace the default one from Arb for that type.

How can I work around this?

**Comment by kurtschelfthout** [comment]
If you call `Arb.register` and register a custom Arbitrary<string> instance, it will indeed override the default string generator. If while defining such a custom Arbitrary instance you try to use `Arb.generate<string>` it will fail because it introduces a circularity. You can avoid that by using `Arb.Default.String()` instead.

Can't say much more without an actual repro.

**Comment by varon** [comment]
Thanks for the explanation. I'm not calling Arb.register, but I suspect it might be baked in as part of the [<Property>] for xUnit. Perhaps we need to add a reset to the default in the 'teardown' for the test?

Could you try the following? This seems to stackoverflow on the test runner and break, despite doing nothing unusual (as far as I can see).

```
namespace Test

open Xunit

module Tests2 = 
    open FsCheck
    open FsCheck.Xunit
    open System
    
    
    type RandomFloats = 
        static member String() = Arb.generate<single> |> Gen.suchThat (Single.IsNaN >> not) |> Gen.map string |> Arb.fromGen

    type BreakingTest = 
        static member String() = Arb.generate<string> |> Gen.map (fun s -> s.ToUpperInvariant()) |> Arb.fromGen

        
    [<Property(Arbitrary = [| typeof<RandomFloats> |])>]
    let psingle (s:String) = Single.Parse s |> ignore
    
    [<Property(Arbitrary = [| typeof<BreakingTest> |])>]
    let ``broken example`` (s : String) = (s = s.ToUpper())
```

**Comment by varon** [comment]
Here's the minimal repro:
```
module MinimalExample
    open Xunit
    open FsCheck
    open FsCheck.Xunit
    open System
    
    let gen = Arb.generate<string>

    type BreakingTest = 
        static member String() = gen |> Arb.fromGen
    
    [<Property(Arbitrary = [| typeof<BreakingTest> |])>]
    let ``broken example`` (s : String) = (s = s)
```

**Comment by kurtschelfthout** [comment]
So looks like the problem in both of those is that you're defining an `Arbitrary` instance for string in terms of itself, because you're calling `Arb.generate<string>`. Instead call `Arb.Default.String()`.

Related to #109 .

**Comment by varon** [comment]
I'm not quite sure it's the same thing. Here's an example without using `Arb.generate`:
```fsharp
module MinimalExample2

open Xunit
open FsCheck
open FsCheck.Xunit
open System
    

let intStr = Arb.Default.Int32() |> Arb.toGen |> Gen.map string

// commenting out this line resolves the issue.
let breaksIt = Arb.Default.StringWithoutNullChars() |> ignore

type BrokenGen = 
    static member String() = intStr |> Arb.fromGen

[<Property(Arbitrary = [| typeof<BrokenGen> |])>]
let ``broken`` (s : String) = s |> ignore
```

**Comment by ploeh** [comment]
FWIW, I ran that repro with three different test runners to make sure that this isn't a ReSharper test runner issue:

- TestDriven.Net
- Visual Studio runner
- xUnit.net console runner

All three runners reproduce the issue.

**Comment by kurtschelfthout** [comment]
Interesting, thanks. I will take a look.

**Comment by kurtschelfthout** [comment]
It's because of side-effects, and me not following my advice I gave above! Bad me. Also side-effects bad. I am thinking about FsCheck 3 and not doing any of this registration nonsense.

**Comment by ploeh** [comment]
> I am thinking about FsCheck 3 and not doing any of this registration nonsense.

Let me know if you need any help! I don't feel particularly familiar with the FsCheck 'core' code base yet, but I wouldn't mind learning, and a new major version implies a bit of restructuring that could be enlightening.

**Comment by kurtschelfthout** [comment]
Thanks for the offer, yes definitely could use help I think, just not clear yet what will end up going in there. I'll start with making a branch and marking issues that I think we'll need to address in a major release (i.e. that we can't do in a backwards compatible way) and adding some ideas, we can take it from there.
