### ISSUE TITLE
Conditional property being run even when the condition is false

### ISSUE THREAD

**Issue by treet** [fscheck/FsCheck#196]
The following script:   
 
    #r "./packages/FsCheck/lib/net45/FsCheck.dll"

    open FsCheck

    let ``Should discard test cases that do not satisfy the condition`` (ints : list<int>) =
      (List.length ints > 0) ==> (List.max ints > 0)

    Check.Quick ``Should discard test cases that do not satisfy the condition``

Results in the following output when run:

    $ fsharpi test.fsx 
    Falsifiable, after 1 test (0 shrinks) (StdGen (1969205831,296099026)):
    Original:
    []
    with exception:
    System.ArgumentException: The input sequence was empty.
    Parameter name: source
      at FSI_0001.Should discard test cases that do not satisfy the condition (Microsoft.FSharp.Collections.FSharpList`1 ints) <0x10eaead90 + 0x001eb> in <filename unknown>:0 
      at FsCheck.Testable.evaluate[a,b] (Microsoft.FSharp.Core.FSharpFunc`2 body, FsCheck.a a) <0x10eaea990 + 0x0006d> in <filename unknown>:0

Am I missing something or is this a bug? Does the condition only guarantee that the test won't fail if the condition is false, but the property expression may still be run?

(I'm running FsCheck 2.2.4 under Mono on OS X if that makes any difference)

**Comment by kurtschelfthout** [comment]
Because of eager evaluation I do think think there is anything Fscheck can do here with the case as written. Feel free if you have any ideas. 

But, you can make the second argument to ==> lazy, (or a unit function). Then it should not be run if the precondition is false.

**Comment by treet** [comment]
Ah, that makes perfect sense. The following code works as expected (List.max is never run on an empty list):

    let ``Should discard test cases that do not satisfy the condition`` (ints : list<int>) =
      (List.length ints > 0) ==> fun () -> (List.max ints > 0)

I suppose generally if the test case can't handle a certain input the 'correct' way would be to make sure no such input is generated. Coming from QuickCheck though I think I've been too reliant on lazy evaluation.

Thanks a lot!
