### ISSUE TITLE
Shrinking for Model-based Testing

### ISSUE THREAD

**Issue by schumi42** [fscheck/FsCheck#197]
Is there a way to customise the shrinker for the command sequences? 
For example if you also want to shrink attributes of the commands.

Or is it somehow possible to disable the shrinking of command sequences for the current version?
Shrinking without considering the preconditions can be counterproductive in some cases ...

**Comment by kurtschelfthout** [comment]
Yes, it leaves something to be desired for sure.

I think if you registered Arbitrary instances with an appropriate shrinker for the Commands (i.e. that shrinks attributes), it will try to use that.

To disable shrinking altogether, the only hack (and it is a hack) I can think of is to override the list Arbitrary instance and remove the shrinker.

**Comment by eiriktsarpalis** [comment]
I'm also using FsCheck for model testing and would like to see an option for disabling shrinking altogether in certain cases.

**Comment by kurtschelfthout** [comment]
I am planning to release something soon - basically exposing the function to create the default generator from the spec, and also a `toPropertyWith` that allows you to pass in generator and shrinker explicitly (and so also allows to not shrink at all). Should be pretty straightforward.

**Comment by kurtschelfthout** [comment]
Released in 2.2.5.
