### ISSUE TITLE
Advisory on property testing of System.decimal or derivations.

### ISSUE THREAD

**Issue by larsw** [fscheck/FsCheck#201]
Hi,

I've had FsCheck on my todo list for a long time, and I've finally gotten around to play with it.

I've constructed a monetary type (Money) that holds a currency and an amount. The amount is of course decimal-based.

Since System.Decimal isn't really an intrinsic type in .NET, the normal rules of wrapping arithmetic operations in a unchecked scope doesn't apply, so I had to filter the Money instances I generated. That worked fine, but I found it weird that I had to restrict the max value by more than / 2 (half) when adding two decimal values. I ended up with a decimal.MaxValue/1000 in my filter.

public static Aribtrary<Money> Money()
{
  const decimal max = decimal.MaxValue / 1000;
  const decimal min = 1 / 100m;

  return Arb.Generate<decimal>()
      .Where(x => x < max && x > min)
      .Select(x => new Money("NOK", Math.Round(x, 3)))
      .ToArbitrary();
}

Now, my test for the commutative property of addition of two Money instances went green.

Next up was to check the associative property of addition.

Since I'm using the FsCheck.Xunit integration, this is the test I wrote:

  [Property(MaxTest = 1000)]
  public void AdditionIsAssociative(Money a, Money b, Money c)
  {
      Assert.Equal((a + b) + c, a + (b + c));
  }

Bam. Red.

Even after assuring that my generator only generates Money instances with 2 decimal places in Amount, I can't seem to grok the rounding rules taking place inside the decimal type.

Has anyone experience with handling these types of situations?

Thanks in advance.

**Comment by kurtschelfthout** [comment]
I would start by looking at the counter-example FsCheck generates (i.e. the values of a, b and c) and work from there.

**Comment by larsw** [comment]
Where are the example you are referring to? Can't find it in any of the examples.

**Comment by larsw** [comment]
Ok, found it under FsCheck.MsTest.Examples, but it is int / System.Int32-based. System.Decimal is a totally different beast.

**Comment by kurtschelfthout** [comment]
No :) I mean look at the output of the failing test. It should print what the values are for which the test fails. In a simple case like this I sometimes create a separate normal unit test with just those values to debug and experiment.

**Comment by ploeh** [comment]
I think what @kurtschelfthout meant was that when your property fails, FsCheck gives you a detailed exception message. Among the details provided, it tells you the values (in this case of `a`, `b`, and `c`) that caused the test to fail.

If you didn't override `ToString` on `Money`, though, perhaps all you see is `Money`, `Money`, and `Money`...

**Comment by larsw** [comment]
Hi again,

@ploeh my Money type is really irrelevant in this context, so given the following test

```csharp
[Property(MaxTest = 100)]
public void AdditionOfDecimalsAreAssociative(decimal a, decimal b, decimal c)
{
    Assert.Equal(a + (b + c), (a + b) + c);
}
```
Which yields (example) the following output:
```
FsCheck.Xunit.PropertyFailedException: 
Falsifiable, after 10 tests (1 shrink) (StdGen (280696390,296128917)):
Original:
(-92233720355662856198M, -0.073786976281953304580M, 3689348816.4598972421M)
Shrunk:
(92233720355662856198M, -0.073786976281953304580M, 3689348816.4598972421M)

Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 92233720359352205014,38611027
Actual:   92233720359352205014,38611026
```

I assume that the System.Decimal - which really is just another floating-point type is *nearly* associative under addition, which to me was a bit surprising, but after reading the docs, I can see how addition of number with a large integer part with another number with a large fractional part will cause the underlying addition operation to have to round off some of the fractional digits.

**Comment by kurtschelfthout** [comment]
Yes, the main difference between float and decimal is that decimal is base 10. So it is a better representation for things that need to be exactly represented in base 10 arithmetic - money is the canonical example. But decimals are still floating point, so you should choose significant digits and precision wisely so that it works for your intended use case.

To understand why base 2 vs base 10 makes a difference, consider that common numbers like 0.1 are not exactly representable using a float. So 0.1 * 0.1 == 0.01 is false, but 0.1M * 0.1M == 0.01M is true.

I'm closing this as it seems your problem is not FsCheck specific. Searching for this stuff should give you ample things to research. Feel free to re-open or open a new issue if you have questions specific to FsCheck.
