### ISSUE TITLE
Experimental.StateMachine

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#202]
I was trying to implement the State Machine and stumbled upon some behavior I would not expect.
The Run and the Check Functions of Operation<Actual,Model> do not get called alternating.

This causes my model check to fail because at the point where "Check" is run my model already passed through multiple transitions while my SUT(system under test) only ran one transition.

I also tried cloning my model before returning it in "Run" because I was not sure how the object from "Run" gets passed to "Check". Did not work either.

If I am modelling the counter as an integer and simply use ++i, and --i  the property check works even though the functions are not called in alternating order.

So maybe I am missing out on something here, I am not sure.

Here is the c# code that fails for me (cloning of the model is not included since it had the same result)
```cs
public class Counter
    {
        public int Value { get; private set; }
        public void Inc() { Value++; }
        public void Dec() { Value--; }
    }

    public class WeirdCounterAbstraction 
    {
        public bool WasLastFunctionInc;
    }

    public class DecCommand : Operation<Counter, WeirdCounterAbstraction>
    {
        public override Property Check(Counter a, WeirdCounterAbstraction m)
        {
            a.Dec();
            return (!m.WasLastFunctionInc).ToProperty();
        }
        public override WeirdCounterAbstraction Run(WeirdCounterAbstraction m)
        {
            m.WasLastFunctionInc = false;
            return m;
        }
        public override string ToString() { return "Dec"; }
    }
    public class IncCommand : Operation<Counter, WeirdCounterAbstraction>
    {
        public override Property Check(Counter a, WeirdCounterAbstraction m)
        {
            a.Inc();
            return (m.WasLastFunctionInc).ToProperty();
        }
        public override WeirdCounterAbstraction Run(WeirdCounterAbstraction m) {
            m.WasLastFunctionInc = true;
            return m;
        }
        public override string ToString() { return "Inc"; }
    }

    public class CounterSetup : Setup<Counter, WeirdCounterAbstraction>
    {
        public override Counter Actual() { return new Counter(); }
        public override WeirdCounterAbstraction Model() { return new WeirdCounterAbstraction(); }
    }
    public class CounterMachine : Machine<Counter, WeirdCounterAbstraction>
    {
        public override Arbitrary<Setup<Counter, WeirdCounterAbstraction>> Setup
        {
            get { return Arb.From(Gen.Constant((Setup<Counter, WeirdCounterAbstraction>)new CounterSetup())); }
        }
        public override Gen<Operation<Counter, WeirdCounterAbstraction>> Next(WeirdCounterAbstraction value)
        {
            return Gen.OneOf(
                (Gen.Constant((Operation<Counter, WeirdCounterAbstraction>)new IncCommand())),
                (Gen.Constant((Operation<Counter, WeirdCounterAbstraction>)new DecCommand())));
        }
    }

    [TestClass]
    public class CounterTest
    {
        [TestMethod]
        public void TestCounter()
        {
            Check.VerboseThrowOnFailure(StateMachineExtensions.ToProperty(new CounterMachine()));
        }
    }
```

**Comment by kurtschelfthout** [comment]
`WeirdCounterAbstraction` should be an immutable class ideally. 

The way this works is it generates a whole trace of commands and runs them on the model, before doing anything to the SUT. This is to check that this trace satisfies preconditions, and so we can shrink it later. Then in the test phase, the generated trace is run on the SUT (`Counter`) and after each command the property returned from `Run` is checked.

Since you have only one instance of `WeirdCounterAbstraction` and you change `WasLastFunctionInc` for the whole trace each time, this can't work.

The approach with clone sounds like it might work, can you share that too if the above didn't clear things up.

**Comment by MarcoMaar** [comment]
Thank you for the explanation on how and why it get called the way it does.
I made the class immutable and it works. But it seems like a lot of work if the model is bigger.

I tried IClonable.Clone and a copy constructor but both methods do not work(okay they are quite similar so I am not surprised that if one fails the other one fails as well).

```cs
    public class WeirdCounterAbstraction : ICloneable
    {
        public bool WasLastFunctionInc;

        public WeirdCounterAbstraction()
        { }
        public WeirdCounterAbstraction(WeirdCounterAbstraction previous)
        {
            WasLastFunctionInc = previous.WasLastFunctionInc;
        }

        public object Clone()
        {
            var n = new WeirdCounterAbstraction();
            n.WasLastFunctionInc = WasLastFunctionInc;
            return n;
        }
    }
```

And for "Run" I used the following implementation
```cs
        public override WeirdCounterAbstraction Run(WeirdCounterAbstraction m) {
            m.WasLastFunctionInc = true;
            return new WeirdCounterAbstraction(m); // return (WeirdCounterAbstraction)m.Clone();
        }
```

**Comment by kurtschelfthout** [comment]
Ok, great. 

Immutable objects are more work because C# doesn't support it (yet). If/when they add record types you should be mostly set. 

You can create immutable classes manually: make your properties read-only and add either a With(...) method or a copy constructor that takes a bunch of optional arguments, one for each property. Bit of boilerplate but you only have to write it once, at the use-sites it is similar to setting a mutable property.

**Comment by mausch** [comment]
Re immutable records in C#, watch this space: https://github.com/mausch/CsDerive
