### ISSUE TITLE
Strange AppVeyor test failure, check if reproducible

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#205]
FsCheck.Test.Random.mkStdGen should return StdGen for every seed [FAIL]
      FsCheck.Xunit.PropertyFailedException : 
      Timeout of 1000 milliseconds exceeded, after 1 test (0 shrinks) (StdGen (1448802465,296131285)):
      IntWithMinMax 0

**Comment by jhamm** [comment]
This passes on a windows machine based on the master branch.
````fsharp
    [<Property(Replay = "(1448802465,296131285)")>]
    let ``mkStdGen should return StdGen for every seed`` (IntWithMinMax seed) =
        Prop.within 1000 <| lazy (let (StdGen (s1,s2)) = mkStdGen (int64 seed) in s1 > 0 && s2 > 0 (*todo:add check*) )
````

Maybe AppVeyor had a heavy load at that time for this test not to finish in 1 second?

**Comment by kurtschelfthout** [comment]
Yeah, I expected it to be something like that (or at least not reproducible). Thanks for checking!
