### ISSUE TITLE
Experimental.StateMachine Shrinking

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#206]
I realized that the Shrinking for ```Operations``` works differently than I expected.
It runs the shrunk Operations and afterwards checks if the Preconditions hold for the models from the last run.
From my understanding it would make more sense to take the shrunk Operations and only take the initial state from the last run. Then construct the models anew for the shrunk Operations while validating the Precondition for the current Operation at every step.

Example:
States ```[a,b,c]```
(Operations)Transitions ```[a->b, b->c, a->c]```
the Precondition is ```Transition.From.Contains(Model.State)```
Assume the error lies in state c
Following sequence in the form ```[StateBeforeOperation, Operation]``` is generated [a,a->b], [b,b->c] .. and then an error in ```Operation.Check``` occurs because of faulty c.

With the currently implemented version nothing was shrunk because the models preconditions were checked after they were run. Therefore the first model state would be ```b``` where ```a``` is expected (State Change already occurred)

With my suggestion one shrink would occur with following sequence [a,a->c], .. error

I implemented the suggested behavior on my local machine to see how it works. What do you think about it?

**Comment by kurtschelfthout** [comment]
I'm sorry, I don't follow what you mean, even with the example. Can you show the code of the new shrinker you've implemented if that is indeed what you have done?

In particular I don't understand what you mean with "the first model state would be `b` where `a` was expected." If I understand correctly that is the model state returned from `MachineRun.Setup` which should be deterministic and immutable.

**Comment by MarcoMaar** [comment]
I am sorry, my explanation was wrong. I misread the source-code. The problem is that ```newModels``` in ```shrink``` takes new models but without the initial one (for the pre condition check).

current (takes elements 2..n (no initial state)):
``````fsharp
let newModels = commands |> List.scan (fun model operation -> operation.Run model) initial |> List.tail
```
takes elements 1..n-1 (with initial state):
```fsharp
let newModels = commands |> List.scan (fun model operation -> operation.Run model) initial |> List.rev |> List.tail |> List.rev
```
With the second version the first precondition check would evaluate on the initial state.

Here is my version that I implemented yesterday
```fsharp
let shrink (spec:Machine<'Actual,'Model>) (run:MachineRun<_,_>) =
        let runModels (initial : 'Model) (operations : Operation<_,_> list) =
            let rec runModelsInner (operations : Operation<_,_> list) (models : 'Model list) : 'Model list = 
                match operations with
                | head :: tail -> if head.Pre models.Head then runModelsInner operations.Tail ((head.Run models.Head) :: models) else []
                | [] -> models
            let models = runModelsInner operations [initial] 
            if models.Length > 0 then Some(List.zip (models |> List.rev |> List.tail) operations) else None 
        Arb.Default.FsList().Shrinker run.Operations
        //try to shrink the list of operations
        |> Seq.choose (fun commands -> 
                            let operations = commands |> List.unzip |> snd
                            let newModels = runModels (fst run.Setup) operations
                            if newModels.IsSome then Some { run with Operations = newModels.Value } else None)
        //try to srhink the initial setup state
        |> Seq.append (Arb.toShrink spec.Setup (snd run.Setup) |> Seq.map (fun create -> { run with Setup = create.Model(), create }))
```

**Comment by kurtschelfthout** [comment]
Yes, I think I understand now, seems like a bug. Thanks for reporting. I will have another look tomorrow with hopefully a clearer head :)

**Comment by MarcoMaar** [comment]
sure keep me posted (:

**Comment by kurtschelfthout** [comment]
So this is indeed a bug that needs fixing, but while doing so I found some other issues so it kind of pulled me down a rabbit hole. I now have the shrinking working better, but it loops infinitely in certain cases ;) so need to fix that before I commit...

**Comment by MarcoMaar** [comment]
Thanks for taking care of that. So I assume the version I posted doesn't fix the problem properly. I am curious where it is lacking, I want to get a better understanding of F# and especially FsCheck.

**Comment by kurtschelfthout** [comment]
I don't think it's lacking, but I went over the code, and moved a few things around. For example, now the transition is shown first, and then the state to which it goes, like [(B->A.A); (A->C,C)].

The problem with the shrinker is that the list shrinker only tries to remove one element at a time from a run, and stops shrinking that branch if it doesn't work.

So if you have a failing test case like:

a->b; b-> a; a->; b->a; a->c

And the problem is in c, you'd think you can shrink to just a->c but it doesn't.

I'll try to commit what I have tonight anyway so you can take a look.

**Comment by MarcoMaar** [comment]
oh, yeah I realized that as well, but I thought that it is not the intention of the Shrinker to find an optimal solution.
One thing I would keep in mind is that if we have to shrink too often, shrinking for model based testing may not be feasible. Usually the SUT takes quite some time to run a test sequence, and we have limited control(we can write a custom shrinker, is there something else?) for the shrinking process.

**Comment by kurtschelfthout** [comment]
Not optimal, but I think it's reasonable for it to try and remove cycles. It's not running those execution sequences on the SUT to filter them out, it's just running the model.

Yes, to control the shrinking you can write a new shrinker. This actually gives you full control over what happens.

**Comment by MarcoMaar** [comment]
I am really looking forward to this version. In certain cases it could need less time(and shrinks?) than the regular "remove one element at a time approach" - and of course closer to optimal results.

I will make sure to give it a try as soon as it is out.

**Comment by kurtschelfthout** [comment]
Great - sorry to keep you waiting, real life is keeping me busy, I think I should have something in the next few days.

**Comment by kurtschelfthout** [comment]
Released in 2.2.5 (with some breaking changes, which I can do in a minor release because this is experimental ;) )

**Comment by MarcoMaar** [comment]
thanks for uploading!
I played around with your changes a bit and realized that when the sequence is getting shrunk```operation.Run model``` is called even if ```operation.Pre model``` returns false.

This is a problem insofar that Run might throw an exception because of an invalid transaction, which then causes the shrinking to stop.

Other than that it works quite well for me, thanks (:

**Comment by kurtschelfthout** [comment]
Cool, opened a new issue for that.
