### ISSUE TITLE
Exception: BigRational' is an F# union type but its representation is private

### ISSUE THREAD

**Issue by halcwb** [fscheck/FsCheck#207]
Using a BigRational generator I could use the below code in FsCheck version 2.2.2.

```
    // #region ---- QUICK CHECK GENERATORS ----

    let bigRGen (n, d) = 
        let n' = abs(n) |> BigRational.FromInt
        let d' = abs(d) |> BigRational.FromInt
        n'/d'

    let bigRGenerator =
        gen {
            let n, d = Random.m1, Random.m2
            return bigRGen(n, d)
        }

    type MyGenerators () =
        static member BigRational () =
            { new Arbitrary<BigRational>() with
                override x.Generator = bigRGenerator }

    Arb.register<MyGenerators>() |> ignore
```
However, with the latest 2.2.4 version I run into the following argument exception:

> Result Message:	
> System.ArgumentException : The type 'Microsoft.FSharp.Math.BigRational' is an F# union type but its representation is private. You must specify BindingFlags.NonPublic to access private type representations.
> Parameter name: unionType
> Result StackTrace:	
> at Microsoft.FSharp.Reflection.Impl.checkUnionType(Type unionType, BindingFlags bindingFlags)
> at Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(Object value, Type unionType, FSharpOption`1 bindingFlags)
> at FsCheck.ReflectArbitrary.reflectShrinkObj[a,b](FSharpFunc`2 getShrink, b o, Type t) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\ReflectArbitrary.fs:line 148
> at FsCheck.ReflectArbitrary.reflectShrink[a,a](FSharpFunc`2 getShrink, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\ReflectArbitrary.fs:line 183
> at FsCheck.Arb.Derive@937.Shrinker(a ) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Arbitrary.fs:line 939
> at FsCheck.Arb.Option@436-3.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Arbitrary.fs:line 436
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.IEnumerator.map@107.DoMoveNext(b& )
> at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1224[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
> at Microsoft.FSharp.Collections.SeqModule.f@4277-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
> at Microsoft.FSharp.Collections.SeqModule.result@1240.Invoke(Int32 i)
> at Microsoft.FSharp.Collections.IEnumerator.unfold@188.DoMoveNext(b& )
> at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.IEnumerator.map@107.DoMoveNext(b& )
> at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.IEnumerator.map@107.DoMoveNext(b& )
> at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@494-1.Invoke(Unit unitVar0)
> at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
> at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@384.Invoke(Unit unitVar0)
> at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
> at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.IEnumerator.map@107.DoMoveNext(b& )
> at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@494-1.Invoke(Unit unitVar0)
> at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
> at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.Skip@1498.GenerateNext(IEnumerable`1& next)
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.Skip@1498.GenerateNext(IEnumerable`1& next)
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source)
> at FsCheck.Runner.shrinkResult@95.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 95
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at FsCheck.Runner.test@105-1.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 127
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.TakeWhile@1490.GenerateNext(IEnumerable`1& next)
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
> at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
> at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
> at FsCheck.Runner.runner[a](Config config, a prop) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 163
> at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275
> at FsCheck.Check.Quick[Testable](Testable property) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 395

**Comment by kurtschelfthout** [comment]
I cannot reproduce, it seems like Arb.register is not being called, and so your generator is not being registered. FsCheck then tries to derive a generator using reflection, but that fails because the implementation of BigRational is private. (FsCheck takes this to mean that there are some invariants in the representation that need to be maintained via static constructors or the like).

Here is a complete example that works.

Note: you should use the methods on the Gen module to write generators, not Random. In fact those m1 and m2 are constants, so your generator will always return the same value. Always use property combinators (on Prop) to see the distribution of the generated values, or Check.Verbose at least once on any new generator to convince  yourself you're actually creating useful values!

```
type BigRational = private BigRational of int with 
    static member FromInt = BigRational
    static member (/)(BigRational a, BigRational b) = BigRational a

let bigRGen (n, d) = 
        let n' = abs(n) |> BigRational.FromInt
        let d' = abs(d) |> BigRational.FromInt
        n'/d'

let bigRGenerator =
    gen {
        let! n = Arb.generate<int>
        let! d = Arb.generate<int>
        return bigRGen(n, d)
    }

type MyGenerators () =
    static member BigRational () =
        { new Arbitrary<BigRational>() with
            override x.Generator = bigRGenerator }

Arb.register<MyGenerators>() |> ignore

Check.Quick(fun  (a:BigRational) -> true)
```

**Comment by halcwb** [comment]
Thanks for pointing out my rather stupid mistake. Furthermore, I put my generator code in a setup fixture so to make sure the generators were registered before any tests. Somehow, using 2.2.2 this wasn't a problem. The code now looks like this:

```
/// Create the necessary test generators
module Generators =

    let bigRGen (n, d) = 
            let d = if d = 0 then 1 else d
            let n' = abs(n) |> BigRational.FromInt
            let d' = abs(d) |> BigRational.FromInt
            n'/d'

    let bigRGenerator =
        gen {
            let! n = Arb.generate<int>
            let! d = Arb.generate<int>
            return bigRGen(n, d)
        }

    type MyGenerators () =
        static member BigRational () =
            { new Arbitrary<BigRational>() with
                override x.Generator = bigRGenerator }

[<SetUpFixture>]
type Config () =
    
    /// Make sure the generators are
    /// registered before running any
    /// test code.
    [<SetUp>]
    member x.Setup () = 

        Arb.register<Generators.MyGenerators>() |> ignore
```

**Comment by kurtschelfthout** [comment]
Ok - that's the reliable and recommended way to do it. Putting side-effecting code in a module is dangerous, can be tricky to predict when it is executed (or not). I can't think of anything that has changed in FsCheck as far as this is concerned... anyway, glad it's resolved.
