### ISSUE TITLE
Experimental.StateMachine Integrating externally generated sequences

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#208]
I am trying to combine a model based testing strategy with FsCheck because I suspect it to generate better ```Command``` Sequences. My other tool would generate the type of ```Command``` (lets call it ```TypeSequence```) while FsCheck would generate the members of it.

I am not sure how to implement this with the current version of FsCheck. I could leverage the ```Next``` function to always pick the next element from my ```TypeSequence```. But I don't know how to make sure that it takes all elements from it, since I cannot control the exact length used for generating the ```CommandSequence``` in FsCheck.

I understand that my intend arguably goes against the purpose of FsCheck. I am using a "random generator" but trying to leverage some of the randomness. But I think it would be a great addition if we can somewhat control the ```CommandSequence``` used in the ```StateMachine```. It allows us to combine it with other TestCase Generators.

So my question are: Am I missing something and it is already possible to implement what I want? If no, would it be an option to support using external Generators for ```Commands```?

**Comment by kurtschelfthout** [comment]
I think if you want FsCheck to generate something to use with another tool, you can write the generator then use `Gen.sample` to get a bunch of elements.

There is no way to tell FsCheck to generate elements from a list exhaustively - the assumption is that exhaustive testing is not possible because the state space is too large. (Not saying this isn't useful)

**Comment by MarcoMaar** [comment]
Maybe I explained poorly again.  I do not want to do exhaustive testing, I want to tell FsCheck which Commands to use in Next.

I still would like to use the  ```Machine<'Actual, 'Model>```.
With ```CommandSequence``` I mean the commands that will be generated with the ```Next```. They are generated one after the other. Therefore I don't know how to control the size of said Sequence.

I will go with an example.
My external tools generates me a sequence of Transitions. e.g..  Add,Substract,Add,Add each of those transitions will need a parameter(int). I want to use this generated Sequence in a way that the first ```Next``` call in ```Machine``` takes the first Element in my list(Add) and then generates the parameters and then creates a ```Generator``` of  ```AddCommand``` and returns it in ```Next```. Second call uses second element, etc. until all elements are used.

I am very focused on Next here, maybe there is another way to realize what I want, just seemed the Next is currently the closest.

**Comment by kurtschelfthout** [comment]
I see. Yes, perhaps that is doable - you'll need to implement Machine yourself, and pass it the sequence of transitions from outside. Then every time Next is called you pop the next transition and return it, e.g. with `Gen.constant` or if you want to generate some arguments something like

```
var transition = _transitions.Pop()
gen { let! arg1 = ....
         let! arg2 = ...
         return tranistion.Init(arg1,arg2)
}
```

Or something...may work...clearly not designed for it. The problem you're alluding to I think is that it's  not possible to signal "no further transitions" right now from the Machine. That should probably be fixed.

**Comment by MarcoMaar** [comment]
With implementing myself, do you mean deriving from ```Machine<'Actual, 'Model>``` and Implementing the abstract methods? If so than this is the approach I tried(Making the Next pop me an element from my transition sequence).

It is not only "no further transition" that causes my problem. The StateMachine could also finish its Commandgeneration before popping all elements. So I not need the exact size.

The "no further transition" has a different problem for me btw. As soon as my StateMachine reaches a terminal state ```Next``` it can not provide a new Operation and my run does not terminate.

**Comment by kurtschelfthout** [comment]
Yeah. So putting two and two together, for this to work Next should be able to generate a Stop command, and keep asking for operations until the Machine implementation generates stop. This sidesteps the size problem. Right?

**Comment by MarcoMaar** [comment]
That would be a solution for it, yes. I just want to make sure beforehand that it is in the sense of FsCheck since my case is very special. Sorry if that is bothersome.

I could create a PR and implement that if it is okay.

**Comment by kurtschelfthout** [comment]
Think it's ok for the state machine to change the interface. Erlang's has a similar interface I think. 

We can discuss more in detail if you PR.

**Comment by kurtschelfthout** [comment]
I've looked at #210 a bit. 

I don't really like the mutable field on MachineRun, but that's a detail. I wonder if we can't control the length of the operations more directly by letting people allow the generator - basically just by setting a fixed size for it.

The more interesting bit is how to do the Stop operation. The way you did it, adding a separate stop operation, is how I thought about it in the beginning of your thread. So I don't have anything against it at all. But now I am thinking perhaps there should be an abstract method on the model `IsEndState:bool` which returns true if it should be the final state. This seems conceptually cleaner but more onerous because the user would have to implement an interface on the now completely generic `'Model` parameter.

**Comment by MarcoMaar** [comment]
**MutableField**
> I don't really like the mutable field on MachineRun, but that's a detail. 

You mean in Machine right? I am also not really a fan of it. Sorry, can you explain a bit more? I am not really understanding your suggestion.

**StopCommand**
I agree that the stop command is not really clean. I just couldn't come up with something better for now. 

> But now I am thinking perhaps there should be an abstract method on the model IsEndState:bool which returns true if it should be the final state.

If we would use an abstract method I don't think the overhead is too bad. For small examples the overhead might seem big but for more complex scenarios you might need to create an own class anyway.

We could even do something like in the csharp snippet. People don't have to implement an interface if they use the generic model. And for complex models you derive directly from the base so you don't have the Value property.

```csharp
    public abstract class Model
    {
        public virtual bool IsEndState { get; }
    }

    public class Model<T> : Model
    {
        public T Value { get; }
        public Model(T value) { Value = value; }
    }
```

There is one thing I like about the StopCommand though. We don't need to know if it is an end state or not. e.g. If all other Commands don't satisfy the precondition, the Stop will be chosen. 
If we use the abstract method we have to think in which cases our Generator will be at a terminal state (well ... maybe thinking about that is not bad (; ).

P.S.: sorry for the messed up PR

**Comment by kurtschelfthout** [comment]
Not really sure there is a better way to deal with the length, was just thinking out loud, let me have a play with it.

Yes the stop command doesn't really have any obvious downsides. Would probably complicate the code to have a stop state as well (extra thing to check for etc), was just thinking an "end state" is usually how this thing is represented in a state machines, so perhaps it would be natural.

**Comment by MarcoMaar** [comment]
If you have any idea about the length let me know.

Sure, I get the "end state" thing. I am just not sure which of the two approaches is better.

**Comment by kurtschelfthout** [comment]
I made the size input a read-only property. Also changed the implementation of the max length a bit, I feel it's more idiomatic now.

Going to punt on the stop state for now unless someone comes up with a good reason to have it.

Feel free to open another issue if you have any more problems or suggestions.
