### ISSUE TITLE
Tests are not discovered on FSharp 4

### ISSUE THREAD

**Issue by Kurren-N** [fscheck/FsCheck#211]
Hope I'm posting in the right place

Fsharp.core 4.3.1.0 gets installed with fscheck. However when I upgrade the test project to Fsharp 4.4.0.0 the tests no longer get discovered. I've tried using a binding redirect in the App.Config but it has no effect. Any advice would be much appreciated!

Thanks,
Kurren

**Comment by ploeh** [comment]
Which test framework are you using?
Which test runner are you using?
Can you share a simple repro?

The reason I'm asking these questions is that, indeed, this symptom is normally caused by an incorrect FSharp.Core version.

**Comment by Kurren-N** [comment]
Thanks for the reply. 

I made a [minimal sample](https://github.com/Kurren-N/FsCheckBug) at the state before switching to F#4, and I commented out the binding redirect. At that point, FsCheck can't generate types from an F# 4 assembly when the test project is on F# 3.1. Switching the test project to F# 4 will then cause the tests not to be found. 

Framework: FsCheck.Xunit
Runner: xunit.runner.visualstudio (the VS test explorer)
Sample: https://github.com/Kurren-N/FsCheckBug

**Comment by ploeh** [comment]
Thank you for sharing a repro. I cloned it and updated it in order to be able to run the tests. Here's what I did:

I opened the package manager console and issued:

```
PM> Update-Package FSharp.Core
```

This causes the _Tests_ library to target F# 4.

The package configuration then looks like this:

```
PM> Get-Package

Id                                  Versions                                 ProjectName                                                                                         
--                                  --------                                 -----------                                                                                         
FsCheck                             {2.2.5}                                  Tests                                                                                               
FsCheck.Xunit                       {2.2.5}                                  Tests                                                                                               
FSharp.Core                         {4.0.0.1}                                Tests                                                                                               
xunit.abstractions                  {2.0.0}                                  Tests                                                                                               
xunit.extensibility.core            {2.1.0}                                  Tests                                                                                               
xunit.extensibility.execution       {2.1.0}                                  Tests                                                                                               
xunit.runner.visualstudio           {2.1.0}                                  Tests
```

I then uncommented the binding redirect from `App.config`:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Both tests now run successfully:

![image](https://cloud.githubusercontent.com/assets/242165/14404186/7d89503e-fe70-11e5-9b81-abd15b6cbe4d.png)

**Comment by Kurren-N** [comment]
Thanks Mark, it works now! It was the Nuget step I was missing. For anyone reading this, the binding redirect is in the App.config file.
