### ISSUE TITLE
Generating generic values

### ISSUE THREAD

**Issue by simendsjo** [fscheck/FsCheck#216]
Shouldn't FsCheck generate use primitive types for generic arguments so I don't have to use concrete types for generic structures?

```
// System.ArgumentException : Cannot create an instance of Microsoft.FSharp.Reflection.DynamicFunction`2[a,FsCheck.Property] because Type.ContainsGenericParameters is true.
//    at System.RuntimeType.CreateInstanceCheckThis()
//    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
//    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
//    at System.Activator.CreateInstance(Type type)
//    at Microsoft.FSharp.Reflection.FSharpValue.MakeFunction(Type functionType, FSharpFunc`2 implementation)
//    at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 316
//    at FsCheck.NUnit.Addin.FsCheckTestMethod.runTestMethod(TestResult testResult) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.NUnit.Addin\FsCheckTestMethod.fs:line 100
//    at FsCheck.NUnit.Addin.FsCheckTestMethod.runTestCase(TestResult testResult) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.NUnit.Addin\FsCheckTestMethod.fs:line 56
[<Property>]
let listAdd (x : 'a) (xs : 'a list) = (x :: xs).Head = x
```

**Comment by kurtschelfthout** [comment]
I wouldn't be strictly against such a feature if it would "fall out of the sky", but overall I think this is unlikely to be worth the complexity. The meaning of generic is that it doesn't matter what the type is, so you might as well pick one - int or so - your tests doesn't actually gain any strength by having FsCheck pick a random type, nor does it save any work on your part.

The complexity on the other hand is pretty high - your example is a simple generic type, but you can add subtype constraints, struct/reference type constraints, constructor constraints, equality and comparison constraints and so on. Figuring this all out correctly seems like a lot of work for little benefit.

**Comment by ploeh** [comment]
Since it looks like you might be using xUnit.net, you _can_ use [this trick](http://blog.ploeh.dk/2011/05/09/GenericunittestingwithxUnit.net) to test against more than a single generic type argument.

I do, however, agree with @kurtschelfthout that most of the time, it isn't warranted, so I rarely do it.

**Comment by simendsjo** [comment]
I misunderstood the [documentation on properties](https://fscheck.github.io/FsCheck/Properties.html)

```fsharp
let revRevIsOrig xs = List.rev(List.rev xs) = xs
```

> Generic properties, such as the one above will be tested by FsCheck as if the
> generic arguments are of type object; this means, that values of various simple
> types (bool, char, string,...) are generated.

**Comment by kurtschelfthout** [comment]
Oh yeah. I completely forgot about that feature...
