### ISSUE TITLE
Create a logo for FsCheck

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#219]
We are still using the unadorned F# logo. I was thinking something with a check mark and/or a "for all" predicate symbol (upside down "A") might be nice. I don't think it has to contain a reference to F# or the F# logo, but I also wouldn't be against it.

I am graphically challenged so definitely up for grabs :)

**Comment by ploeh** [comment]
Well, if you rotate the F# logo, you have the inverted _A_ in the lower part :wink: 

![fsharp256](https://cloud.githubusercontent.com/assets/242165/14586208/2e0157ce-0491-11e6-88d7-b6b963cec543.png)

**Comment by kurtschelfthout** [comment]
Indeed. Perhaps the F# foundation should change _its_ logo.

**Comment by ReedCopsey** [comment]
I have an idea...will post tomorrow (once I have access to design tools)

**Comment by kurtschelfthout** [comment]
Incidentally, I'm not the first one to have thought of the for all symbol apparently ;)

https://www.scalacheck.org/
https://github.com/jsverify/jsverify

**Comment by ploeh** [comment]
Here's a concept suggestion:

![fscheck logo suggestion](https://cloud.githubusercontent.com/assets/242165/14706330/467906dc-07be-11e6-9068-b13440948a54.jpg)

As you can tell, it's a hand-drawn concept sketch. Notice that it's a combination of the inverted A and a checkmark.

Perhaps the lines should be thicker or thinner. Perhaps the vertical bar should be higher or lower. Perhaps the 'colours' should be inverted, so that the symbol itself appears as negative space (like, e.g., the [AutoFixture logo](https://raw.githubusercontent.com/AutoFixture/AutoFixture/master/AutoFixtureLogo200x200.png)).

If you hate it, that's OK :smile: If not, however, I'll be happy to try to refine it, or for someone else with better design skills than I have to use the concept for inspiration.

**Comment by moodmosaic** [comment]
Looks awesome to me 🤓

**Comment by kurtschelfthout** [comment]
Yeah, I like the concept. 

There are other ways of differentiating the check mark part of the forall - like giving it a (subtly) different color. But I like the separation between the two like you did too.

**Comment by ploeh** [comment]
FWIW, I don't know much about graphical design, but what I do know about logo design is that a good logo should also be recognisable in black and white. That's the reason I used a bit of space to separate the two parts of the shape.

We can still give each shape a different colour, if you'd like. We can also choose to ignore the 'rule' about black-and-white recognisability.

**Comment by kurtschelfthout** [comment]
Good point. Also better for people who are color blind.

**Comment by kurtschelfthout** [comment]
I had some fun in Inkscape. Actual thing is svg, it looks a bit pixelated here but can be fixed. I tried adding a # sign somewhere too, but didn't think it plays out well.

![logo-small](https://cloud.githubusercontent.com/assets/164917/14798459/a39ec88c-0b2f-11e6-9f6f-cf97ed02c8bb.png)

**Comment by ploeh** [comment]
Do you have a particular intent for the logo? If, for example, you want to use it for icons, you might consider how it fits into a quadratic shape. (That's one of the reasons I drew the above sketch on quadratic paper.)

I wouldn't mind fiddling more with this, but I'm quite busy this week and the next.

@ReedCopsey also claimed to have an idea, so perhaps that one is worth waiting for :smile:

**Comment by kurtschelfthout** [comment]
That's a good point. I didn't put all that much thought into it :)

I'll see how it looks in a square shape and try to post back.

No rush.

**Comment by ploeh** [comment]
I decided to play a bit with plotting that concept into an isometric triangular grid, in order to get something that would fit into a quadratic shape. Here's a suggestion:

![fscheck-logo-concept-02](https://cloud.githubusercontent.com/assets/242165/15516839/fcb809e8-21f4-11e6-8712-7d5c81201d82.png)

In this concept, I chose to show a black rendering, because I think it's important that a logo also works in black & white. It's entirely possible, however, to use two different colours, as suggested by @kurtschelfthout.

What do you think?

**Comment by smoothdeveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/87944/15517994/f6dfb7c2-21fa-11e6-9be1-ca54c9eb5b20.png)

Not sure if that was mentioned in this thread (awesome to have polished logos on many F# projects BTW), but we could fit a F and a S and a Check in that logo you are sketching.

**Comment by moodmosaic** [comment]
I like the logo proposed by @ploeh.

I think the turned A (∀) symbol works as a nice logo for FsCheck, as long as it doesn't support existential quantification.

**Comment by kurtschelfthout** [comment]
I like the shape of it and agree it should also work in black and white as we discussed above, but I also think it could use some color to spice things up. I used red and green because that is connected to testing in my mind, but am not attached to that choice.Perhaps making the shape a bit thinner would be interesting to try, it looks perhaps a bit heavy (though that could also be the black and white thing). 

Do you have an svg or something folks can play with?

**Comment by ploeh** [comment]
Here's a red/green version:

![fscheck-logo-concept-02-red-green](https://cloud.githubusercontent.com/assets/242165/15574269/adbd27a2-234c-11e6-8a9f-f6e3a7171776.png)

**Comment by ploeh** [comment]
And here's a version using the colours of the F# logo:

![fscheck-logo-concept-02-fsharp-logo-colours](https://cloud.githubusercontent.com/assets/242165/15574289/bf99adc4-234c-11e6-9626-175dd174c1c7.png)

**Comment by ploeh** [comment]
Obviously, nothing is set in stone, but while it may look a bit heavy, there's a geometric reason for that, since I actually plotted the shape on an isometric triangular grid:

![fscheck-logo-concept-02-grid](https://cloud.githubusercontent.com/assets/242165/15574340/1b98d992-234d-11e6-958c-a2b3fbf208c9.png)

Personally, I find the proportions quite attractive exactly because they have a geometric background :smile:

**Comment by ploeh** [comment]
I actually did most of the work in PowerPoint :flushed: but I don't mind sharing the file if someone wants to play around with it:

[FsCheck-logo-isometric-triangles.png.pptx](https://github.com/fscheck/FsCheck/files/284251/FsCheck-logo-isometric-triangles.png.pptx)

**Comment by ploeh** [comment]
One way to make it a bit thinner, now that I think about it, is to make the outline of each shape thick, but transparent:

![fscheck-logo-concept-02-lighter](https://cloud.githubusercontent.com/assets/242165/15574721/59324110-234f-11e6-8528-e4beb05bf050.png)

**Comment by ploeh** [comment]
I like the original shape better, though, because with the lighter design, the angles don't line up.

**Comment by kurtschelfthout** [comment]
Nice. uhm, I feel bad deciding by myself. I'm going to poll around the house here to get some reactions :)

Others, feel free to let preferences know...

**Comment by ploeh** [comment]
To be clear: I'm putting this suggestion out here as a concept, not as a final suggestion. There are lots of ways we can riff on this concept.

**Comment by ploeh** [comment]
As an example, we can use only the outline, instead of a filled-out block of colour:

![fscheck-logo-concept-02a-outline](https://cloud.githubusercontent.com/assets/242165/15632061/e7336bfe-2586-11e6-959d-439fe4cef4da.png)

**Comment by ploeh** [comment]
We can also fill out the blocks, but keep a distinct outline:

![fscheck-logo-concept-02a-outline-and-filled](https://cloud.githubusercontent.com/assets/242165/15632064/01cd33fa-2587-11e6-92da-3cd541ff39ca.png)

**Comment by ploeh** [comment]
Another area we can still experiment with is the width of the cut:

![fscheck-logo-concept-02a-cut-width](https://cloud.githubusercontent.com/assets/242165/15632089/db071f46-2587-11e6-9076-a8d76fe35005.png)

What I _do_ think is important is to maintain the geometry of the isometric triangular grid:

![1b98d992-234d-11e6-958c-a2b3fbf208c9](https://cloud.githubusercontent.com/assets/242165/15632101/0f1f41fa-2588-11e6-9f75-9497cd7452c6.png)

**Comment by ploeh** [comment]
Yet another option is to keep the triangles visible:

![fscheck-logo-concept-02b-visible-triangles](https://cloud.githubusercontent.com/assets/242165/15632122/b1ecc6c8-2588-11e6-9373-0942a0912873.png)

**Comment by ploeh** [comment]
BTW, I've intentionally put each image in a separate post so that everyone can use the new _reaction_ GitHub feature to 'upvote' or 'downvote' each suggestion individually.

**Comment by ploeh** [comment]
Solicited feedback on Twitter: https://twitter.com/ploeh/status/736839475179999232

**Comment by cloudRoutine** [comment]
@ploeh  how about using the F# logo color version layered on top of the triangle grid in the background?

**Comment by ploeh** [comment]
@cloudRoutine You mean like this?

![fscheck-logo-concept-02a-fsharp-colours-on-grid](https://cloud.githubusercontent.com/assets/242165/16278214/557655b2-38b6-11e6-94ca-71cf512c14fb.png)

**Comment by cloudRoutine** [comment]
yup, but with thicker stroke weight

**Comment by kurtschelfthout** [comment]
I finally picked a logo and updated. It's not published yet so if you have final objections there are still a few days left. I picked the original F#-blue forall A because I like the simplicity of it, and the colors reflect the connection to F#. It also had the most upvotes :)

**Comment by kurtschelfthout** [comment]
Many thanks to @ploeh for trying out designs, and my apologies for leaving this so long.

**Comment by ploeh** [comment]
Cool 😊 

Could you use this variation instead? It has the same colours, but I made an error in the geometry of the first ones I showed. It's corrected here

![fscheck-logo-concept-02a-fsharp-logo-colours](https://cloud.githubusercontent.com/assets/242165/22619959/ce93423c-eb00-11e6-93e6-f28221da9c61.png)

**Comment by ploeh** [comment]
Also: all of these are created using PowerPoint. Would you like me to add the PowerPoint file to FsCheck's repository as well?

**Comment by kurtschelfthout** [comment]
Sure, might as well override the png in the same PR?

**Comment by ploeh** [comment]
PR sent: https://github.com/fscheck/FsCheck/pull/342

**Comment by kurtschelfthout** [comment]
Thank you!
