### ISSUE TITLE
Support for Framework 4.0?

### ISSUE THREAD

**Issue by smoothdeveloper** [fscheck/FsCheck#225]
I haven't checked yet what would be involved to support Framework 4.0, I think besides a bit of reflection stuff which might need work (TypeInfo not present) it shouldn't have too much impact.

Was this considered before? Any reason to have 4.5 as the lowest framework?

**Comment by mausch** [comment]
The original reason to move to 4.5 was using ExceptionDispatchInfo https://github.com/fscheck/FsCheck/commit/f248b094662b28b1c846f0e81e870129c10cbbda

**Comment by smoothdeveloper** [comment]
Thanks.
