### ISSUE TITLE
Documentation for showing how to specify MaxTest, StartSize, using just inline Props in C#

### ISSUE THREAD

**Issue by Aaronontheweb** [fscheck/FsCheck#230]
I've been able to use the XUnit integration seamlessly to configure specs for which I want large test sizes like this:

```csharp
 [Property(QuietOnSuccess = true, MaxTest = 10000)]
        public Property ChannelOutboundBuffer_must_always_correctly_report_writability_and_PendingBytes(IByteBuf[] writes)
        {
            bool writeable = true;
            var buffer = new ChannelOutboundBuffer(TestChannel.Instance, () =>
            {
                writeable = !writeable; // toggle writeability
            });

            foreach (var msg in writes) ....
```

For the life of me, I can't figure out how to set properties like `MaxTest` when using this syntax:

```csharp
  [Theory]
        [InlineData(typeof(UnpooledByteBufAllocator))]
        public void Buffer_should_perform_consistent_reads_and_writes(Type allocatorType)
        {
            var allocator = (IByteBufAllocator)Activator.CreateInstance(allocatorType);

            var writeReadConsitency = Prop.ForAll<BufferOperations.IWrite[], BufferSize>((writes, size) =>
            {
                var buffer = allocator.Buffer(size.InitialSize, size.MaxSize);
```

Could you add some documentation showing how to configure these values when using the builder interface on `Prop`?

**Comment by Aaronontheweb** [comment]
Bah, hit enter too quickly - finished spelling out the rest of the issue above.

**Comment by kurtschelfthout** [comment]
It's not on `Prop` it's on `Check`. Your example is cut off so I can't quite tell if it's complete - I hope there is a `QuickCheckThrowOnFailure()` at the end there. :)

Instead of that use the overload of `Check` where you can pass a `Configuration`. You can set `MaxTest` on that.

https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/RunnerExtensions.fs#L108-108
