### ISSUE TITLE
Why FsCheck.NUnit depends on NUnit.Runners

### ISSUE THREAD

**Issue by xperiandri** [fscheck/FsCheck#231]
What if I just want to use test adapter?

**Comment by kurtschelfthout** [comment]
Because it needs dlls that are only available in the NUnit.Runners package. The NUnit plugin architecture is less than ideal.

**Comment by xperiandri** [comment]
Do you know if it was changed in nUnit 3?

**Comment by kurtschelfthout** [comment]
It was, and in a good directio, but last I tested (which is a while ago) it wasn't there yet. See #98 for details and if you're interested.
