### ISSUE TITLE
Make Gen.sample easier to use in v3

### ISSUE THREAD

**Issue by moodmosaic** [fscheck/FsCheck#236]
Even though _not_ all generators depend on size, `Gen.sample` takes `size`, for setting the size.

``` f#
val sample : size:int -> n:int -> gn:Gen<'a> -> 'a list
```

Why not defining `Gen.sample` as:

``` f#
val sample : n:int -> gn:Gen<'a> -> 'a list
```

The size passed to the generator should always be the same; if one wants another size then he or she should explicitly use `Gen.resize`.

---

That's also how `sample` works in Erlang QuickCheck by QuviQ and Haskell QuickCheck.

**Comment by moodmosaic** [comment]
Let me know if you'd want to see this in action on some v3-related branch.

**Comment by kurtschelfthout** [comment]
I'm conflicted on this. I'm sympathetic to the argument that we have  `Gen.resize` to control this already. On the other hand we are back to picking a magic number for size now in `sample`.

**Comment by moodmosaic** [comment]
>we are back to picking a magic number for size now in `sample`.

Not necessarily. — How about this:

```f#
let sample gn = [ for s in [ 0..2..20 ] -> resize s gn |> eval ]
```

(I haven't tried to compile this, but you should get the idea.)

**Comment by kurtschelfthout** [comment]
Well, that's two magic numbers, `2` and `20` :)

**Comment by moodmosaic** [comment]
👍
