### ISSUE TITLE
Experimental.StateMachine Setup Shrinking

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#239]
I created a  counter state machine to try out shrinking of `Setup<Actual,Model>`.
I added a bug which fails the increment statement if it is executed while the Counter value is higher than a certain threshold.

My Setup takes an integer value to create the Counter and also uses this integer as the model.
On shrinking it shrinks the integer and returns the new setups.

Here is a test run that causes unexpected behavior for me.

```
Original:
(94, Setup Counter)
Decrement:10 -> 84
Decrement:1 -> 83
Increment:7 -> 90
Increment:3 -> 93
Decrement:4 -> 89

Shrunk:
(0, Setup Counter)
Decrement:10 -> 84
Decrement:1 -> 83
Increment:7 -> 90
Increment:3 -> 93
Decrement:4 -> 89
```

There are two things that seem odd to me:
1. Shrinking the Setup does not affect the commands (e.g. the model still has the same value after executing the commands even though the setup was shrunk).
2. Neither commands nor the command sequence is shrunk.

I guess both occur because shrinking of the setup happens after shrinking of the commands.
https://github.com/fscheck/FsCheck/blob/afc48655c090f7e5990cb662cc9ea85917829230/src/FsCheck/StateMachine.fs#L324

**Comment by kurtschelfthout** [comment]
Yes, two bugs, one cause as you say...

**Comment by MarcoMaar** [comment]
I can have a look and try to fix the shrinking.
The only question I have before I start is, do we need a setup?

I mean it makes the StateMachine more complex and prone to errors and I do not see too much of a benefit. I actually only found the error because I wanted to write documentation for it (;

I never needed the functionality in a real applications. And if you need an initialization with a random state why not create a command for it and ensure it gets called first.

But yeah that are just my thoughts. Maybe there are some useful scenarios for the Setup with a generator.

To make it short. What do you think: Should I fix it or should I remove it?

**Comment by kurtschelfthout** [comment]
Interesting idea. Where would the initial state be produced? And how would you ensure a particular "setup" operation is called first?

**Comment by MarcoMaar** [comment]
I guess there are various options. What I did in the counter example is to derive my setup from `Setup<Actual,Model>` and add a flag to indicate if an InitCommand was already generated or not. Then on `Machine.Next` I check the flag and generate respectively. Since `Machine.Setup` is called at the beginning of every run I don't have to care about resetting the flag since I get a new instance of my Setup.

I think using the current Setup with a generator is cleaner, but as I mentioned I am not sure if it is worth it. For me the need of a randomly generated Setup seems pretty low.

**Comment by kurtschelfthout** [comment]
I've had occasional use for it; one example that comes to mind is testing mutable data structures like resizable arrays or dictionaries that take some kind of initial size or bucket size. Typically this should only influence perf so it's not in the model.

**Comment by MarcoMaar** [comment]
So I guess it makes more sense to keep the setup and adjust setup shrinking, right?

**Comment by kurtschelfthout** [comment]
haha, yes less code is generally better. But not above all else...otherwise there would be no code...
