### ISSUE TITLE
Using Gen.Sample to generate multiple values appears to be not "random enough" 

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#242]
I tried use Gen.Sample to generate multiple values in a very short time and it appears that the values generated tend to be the same during a certain time period. 

```csharp
var l = new List<int>();
var fl = Gen.Choose(0, 1).Sample(1, 100);
foreach (var i in fl) { Debug.Write(i); } //version1
Debug.WriteLine("");

for (int i = 0; i < 100; i++)
{
    int toAdd = Gen.Choose(0, 1).Sample(1, 1).Head;
    l.Add(toAdd);
}
foreach (var i in l) { Debug.Write(i); } //version2
```

This code snippet produced following sample outputs:
```
1110101001111000001111000011111000011100000011110000011110000111110000111110000111100000111100001111
1111111111111111111111111111111111111111111111111110000000000000000000000000000000000000000000000000
```

```
0001111000011111000011110000011110000011110011110001111000011111000011111000011110000011110000111111
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

version1 seems to be "more random" than version2. Sorry for my poor explanation of randomness.
I ran the generators about 20 times and I never saw a pattern with only one consecutive 0 or 1. e.g: 0001001...

**Comment by kurtschelfthout** [comment]
yeah, that's just because it uses time as the seed every time you call sample. Basically, don't do that :)

**Comment by MarcoMaar** [comment]
I suspected that time was the culprit (;

I sort of understand why the second approach is no good. Because it doesn't make too much sense to call Sample with size 1 multiple times.

What is with the first approach? It appears to be more random but it still looks clustered.

How should I generate a list of integer then? Or am I missing some obvious method?

**Comment by kurtschelfthout** [comment]
Yeah, the random implementation is not great. It has some known problems, Planning to replace it with another implementation in 3.0.

`Gen.listOf Gen.choose (0,1)` for example. Basically, never use `sample` or `eval` in a new generator implementation.

**Comment by MarcoMaar** [comment]
yeah, I saw the issue for the change of the random generator. Since I did not try out the branch I wasn't sure if there is the same problem or not.

Thanks I will give Gen.listOf a try.

**Comment by moodmosaic** [comment]
>How should I generate a list of integer then?

Here's another way of getting a list of integers out of FsCheck, in F# Interactive:

```fsharp
#I __SOURCE_DIRECTORY__
#r "../../packages/FsCheck.2.4.0/lib/net45/FsCheck.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"

open FsCheck

let intGen = Gen.sized <| fun s -> Gen.choose (-s, s);;
let lstGen = intGen |> Gen.listOfLength 10;;
let result = lstGen |> Gen.sample 255 1 |> Seq.head;;

// val intGen : Gen<int>
// val lstGen : Gen<int list>
// val result : int list = [85; -24; 205; 82; -30; 83; -208; -108; 5; 197]
```

---

**Notes**

 * *255* in `sample` means the runtime size that FsCheck uses shouldn't go above that value.
 * *1* means I want `sample` to generate 1 element (in this case, 1 list).
 * `intGen` is a generator for integers. It uses the `sized` combinator for accessing the runtime size, which in this case is provided via `sample`. Then it passes that size to `choose` for picking up an integer from the set [-size, size].

Given the above, the lists of integers that FsCheck can generate, given the above generators, will not contain numbers outside of [-255, 255].

**Comment by moodmosaic** [comment]
I've now executed the above in F# interactive 3 times and got back

```
val result : int list = [-192; -70; 71; 5; 162; -110; -3; 13; -14; -2]
```

```
val result : int list = [2; 3; 3; 0; 8; 9; -2; 7; -4; 10]
```

```
val result : int list = [-31; 3; 2; 27; -23; 2; 41; -46; -15; 13]
```

on each execution respectively.

**Comment by MarcoMaar** [comment]
@moodmosaic 
It still has the same outcome if you produce only 0 and 1.

```fsharp
let easyPrint l = 
    for e in l do printf "%d" e
    printfn ""
let intGen = Gen.choose (0, 1)
let lstGen = intGen |> Gen.listOfLength 100
let result = lstGen |> Gen.sample 255 1 |> Seq.head
easyPrint result

//0001111000011111000011111000011110000000011111001110101000011111000011111000011110000011110000111110
```

But thank you anyway. I think the explanation of @kurtschelfthout makes sense. It is related to time and won't work properly in the current version.
