### ISSUE TITLE
Experimental.StateMachine Behavior on unexpected input

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#252]
I was thinking of how we should handle the following two cases.
- No operation that satisfies the precondition could be generated.

Currently if the precondition is not satisfied the generated sequence to the current point is used. Alternately we could throw an exception and inform the user that the precondition couldn't be met. Otherwise the user may not realize that his model is faulty.
The downside would be that if we are at a terminal state the user would have to create a StopCommand by himself... So I am not sure what we could do, but I think we should not conceal that the Preconditions can't be satisfied.
- In Next no Operation is generated at all

Currently if no operation is generated in next this exception is thrown:
`System.IndexOutOfRangeException : Index was outside the bounds of the array.`

Maybe we could check for this behavior in FsCheck and throw a custom exception that informs the user he forgot to generate an operation.

A case where this error can occur is for example the following:
You use weights to generate commands. Especially if the weights are calculated in a not straightforward way it could happen that all weights are 0 without noticing it.

**Comment by MarcoMaar** [comment]
And I found a third thing.

- Postcondition not satisfied.

Currently if `Machine.Check` fails the run is still continued until the end. I think it would be better to abort the run and list how far Check got in the sequence.

The reason why I would abort without completing the run is the following:
If our SUT enters an unexpected state we can no longer safely operate it. This can result in further errors. The problem is then that FsCheck might not report the first error but another one. Finding the root problem is then tough.

Oh .. We could also shorten the sequence for the Shrinker if we abort early.

**Comment by kurtschelfthout** [comment]
Agree with the second and third points. 

First point too, I think it should generate an arguments exhausted message at some point - same as what you get if you have a strong filter and FsCheck can't find enough examples to satisfy the filter. 

Third point is the result of using .&. to recursively combine each step; that's been on my list to change for a while.

**Comment by kurtschelfthout** [comment]
Should now be addressed.
