### ISSUE TITLE
Make Gen.eval easier to use in v3

### ISSUE THREAD

**Issue by moodmosaic** [fscheck/FsCheck#268]
Currently, the type signature of `Gen.eval` is

``` fsharp
int -> StdGen -> Gen<'a> -> 'a
```

Where `int` stands for `size`, `StdGen` for an instance of `Random`, and `Gen<'a>` for the generator we want to evaluate.

I believe that `StdGen` shouldn't be exposed, as it's really an implementation detail, and so `Gen.eval` should look like:

``` fsharp
int -> Gen<'a> -> 'a
```

Where `int` stands for `size`, and `Gen<'a>` for the generator we want to evaluate.

---

_If_ `Runner` uses `Gen.eval` for test-replaying, that could be done via some other function, probably internal, or [hidden](http://blog.ploeh.dk/2015/09/21/public-types-hidden-in-plain-sight/).

Related: #267, #236, #198.

**Comment by Aaronontheweb** [comment]
I second this - would help a lot with an FsCheck integration I'm working on designed to make it much easier to use with C# POCO classes (including fun edge cases like constructor arguments, etc...). Being able to access the same StdGen instance as the `Runner` or not having to worry about it period would be great.

**Comment by moodmosaic** [comment]
Actually, I think that making `Gen.eval` public wasn't a good idea at all, since there's `Gen.sample`...

**Comment by ploeh** [comment]
Isn't `Gen.eval` deterministic?

**Comment by moodmosaic** [comment]
True. `Gen.sample` uses `Gen.eval` internally. And `Gen.eval` takes the seed as argument so it's an easy way to replay a test...

**Comment by moodmosaic** [comment]
👍
