### ISSUE TITLE
Cannot load FsCheckAddin.fs in interactive

### ISSUE THREAD

**Issue by halcwb** [fscheck/FsCheck#279]
When trying to load a test project with FsCheck in a script file using the powertools generate references, I get the following error:

> error FS0074: The type referenced through 'NUnit.Core.TestResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'nunit.core.interfaces'.

However, the requested library is loaded in the interactive. Also, specifically adding the requested reference doesn't solve the problem.

> -> Referenced '..\packages\NUnit.Runners\tools\lib\nunit.core.dll'
> 
> 
> --> Referenced '..\NUnit.Runners\tools\lib\nunit.core.interfaces.dll'
> 
> 
> [Loading ..\load-references-release.fsx
>  ..\FsCheckAddin.fs
>  ..\BuildTest.fs
> 
> 
> ..\FsCheckAddin.fs(12,17): error FS0074: The type referenced through 'NUnit.Core.TestResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'nunit.core.interfaces'.

**Comment by ploeh** [comment]
Does the version of `nunit.core.interfaces` loaded match the version needed?

**Comment by halcwb** [comment]
My lock file matches exactly the FsCheck lock file with regard to the nunit versions (= 2.6.4).

**Comment by halcwb** [comment]
I completely give up, I have spent days of time to get a reliable working FsCheck test setup with VS 2013 without getting in the mess with FSharp.Core. Local builds run fine but deploying op AppVeyor results in:

```
Build started
Fetching repository commit (acfda5c)...OK
Total: 145.4 KB in 44 files
build.cmd runtests
No version specified. Downloading latest stable.
Starting download from https://github.com/fsprojects/Paket/releases/download/2.66.9/paket.exe
Done.
Paket version 2.66.9.0
Downloading fsharp/FAKE:8c077f35f8cd0350485109ddd1810dafe9885d1a modules/Octokit/Octokit.fsx to C:\projects\genutils\paket-files\fsharp\FAKE\modules\Octokit\Octokit.fsx
Downloading FsCheck.Nunit 2.4
Downloading FsCheck 2.4
Downloading FAKE 4.27
Downloading FSharp.Compiler.Service 2.0.0.6
Downloading FSharp.Core 4.0.0.1
Downloading FSharp.Formatting 2.14.3
Downloading FSharpVSPowerTools.Core 2.3
Downloading FSPowerPack.Community 3.0
Downloading FSPowerPack.Core.Community 3.0
Downloading FSPowerPack.Linq.Community 3.0
Downloading FSPowerPack.Metadata.Community 3.0
Downloading FSPowerPack.Parallel.Seq.Community 3.0
Downloading FsUnit 1.4.1
Downloading Microsoft.Bcl 1.1.10
Downloading Microsoft.Bcl.Build 1.0.21
Downloading Microsoft.Net.Http 2.2.29
Downloading Newtonsoft.Json 8.0.3
Downloading NUnit 2.6.4
Downloading NUnit.Runners 2.6.4
Downloading Octokit 0.19
Downloading SourceLink.Fake 1.1
Downloading Unquote 3.1.1
Downloading halcwb/GenBuild:601aef1c9ab42ebc3d3ec76dbca39fc076544deb scripts/appveyor.fsx to C:\projects\genutils\paket-files\halcwb\GenBuild\scripts\appveyor.fsx
Downloading halcwb/GenBuild:601aef1c9ab42ebc3d3ec76dbca39fc076544deb scripts/targets.fsx to C:\projects\genutils\paket-files\halcwb\GenBuild\scripts\targets.fsx
Downloading halcwb/GenBuild:601aef1c9ab42ebc3d3ec76dbca39fc076544deb scripts/travis.fsx to C:\projects\genutils\paket-files\halcwb\GenBuild\scripts\travis.fsx
21 seconds - ready.
Building project with version: 1.0.52 
Shortened DependencyGraph for Target RunTests: 
<== RunTests 
   <== CopyBinaries 
      <== Build 
         <== AssemblyInfo 
            <== Clean 
 
The resulting target order is: 
 - Clean 
 - AssemblyInfo
 - Build
 - CopyBinaries 
 - RunTests 
Starting Target: Clean  
Creating C:\projects\genutils\bin 
Creating C:\projects\genutils\temp 
Finished Target: Clean 
Starting Target: AssemblyInfo (==> Clean) 
Created AssemblyInfo file "C:\projects\genutils\src\Informedica.GenUtils.Lib\AssemblyInfo.fs". 
Finished Target: AssemblyInfo 
Starting Target: Build (==> AssemblyInfo) 
Building project: C:\projects\genutils\GenUtils.sln
  C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe  C:\projects\genutils\GenUtils.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\projects\genutils\packages\FAKE\tools\FakeLib.dll"
C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe  C:\projects\genutils\GenUtils.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\projects\genutils\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 12.0.40629.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.
 
Build started 6/7/2016 4:24:41 AM.
     1>Project "C:\projects\genutils\GenUtils.sln" on node 1 (Rebuild target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
     1>Project "C:\projects\genutils\GenUtils.sln" (1) is building "C:\projects\genutils\src\Informedica.GenUtils.Lib\Informedica.GenUtils.Lib.fsproj" (3) on node 1 (Rebuild target(s)).
     3>CoreClean:
         Creating directory "obj\Release\".
     1>Project "C:\projects\genutils\GenUtils.sln" (1) is building "C:\projects\genutils\tests\Informedica.GenUtils.Tests\Informedica.GenUtils.Tests.fsproj" (2) on node 2 (Rebuild target(s)).
     2>CoreClean:
         Creating directory "obj\Release\".
     3>PrepareForBuild:
         Creating directory "bin\Release\".
     2>PrepareForBuild:
         Creating directory "bin\Release\".
     3>CoreCompile:
         C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Release\Informedica.GenUtils.Lib.dll --debug:pdbonly --noframework --define:TRACE --doc:bin\Release\Informedica.GenUtils.Lib.XML --optimize+ -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0\FSharp.Core.dll" -r:C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.dll -r:C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.dll -r:C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.dll -r:C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll" --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ "C:\Users\appveyor\AppData\Local\Temp\1\.NETFramework,Version=v4.5.AssemblyAttributes.fs" NullCheck.fs List.fs Option.fs Reflection.fs String.fs BigRational.fs 
       _CopyFilesMarkedCopyLocal:
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.dll" to "bin\Release\FSharp.PowerPack.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.dll" to "bin\Release\FSharp.PowerPack.Linq.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.dll" to "bin\Release\FSharp.PowerPack.Metadata.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.dll" to "bin\Release\FSharp.PowerPack.Parallel.Seq.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.xml" to "bin\Release\FSharp.PowerPack.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.xml" to "bin\Release\FSharp.PowerPack.Linq.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.xml" to "bin\Release\FSharp.PowerPack.Metadata.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.xml" to "bin\Release\FSharp.PowerPack.Parallel.Seq.xml".
       CopyFilesToOutputDirectory:
         Copying file from "obj\Release\Informedica.GenUtils.Lib.dll" to "bin\Release\Informedica.GenUtils.Lib.dll".
         Informedica.GenUtils.Lib -> C:\projects\genutils\src\Informedica.GenUtils.Lib\bin\Release\Informedica.GenUtils.Lib.dll
         Copying file from "obj\Release\Informedica.GenUtils.Lib.pdb" to "bin\Release\Informedica.GenUtils.Lib.pdb".
     3>Done Building Project "C:\projects\genutils\src\Informedica.GenUtils.Lib\Informedica.GenUtils.Lib.fsproj" (Rebuild target(s)).
     2>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Release\Informedica.GenUtils.Tests.dll --debug:pdbonly --noframework --define:TRACE --doc:bin\Release\Informedica.GenUtils.Tests.XML --optimize+ -r:C:\projects\genutils\packages\FsCheck\lib\net45\FsCheck.dll -r:C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.Addin.dll -r:C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0\FSharp.Core.dll" -r:C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.dll -r:C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.dll -r:C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.dll -r:C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.dll -r:C:\projects\genutils\packages\FsUnit\lib\net45\FsUnit.NUnit.dll -r:C:\projects\genutils\src\Informedica.GenUtils.Lib\bin\Release\Informedica.GenUtils.Lib.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" -r:C:\projects\genutils\packages\FsUnit\lib\net45\NHamcrest.dll -r:C:\projects\genutils\packages\NUnit.Runners\tools\lib\nunit.core.dll -r:C:\projects\genutils\packages\NUnit.Runners\tools\lib\nunit.core.interfaces.dll -r:C:\projects\genutils\packages\NUnit\lib\nunit.framework.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll" -r:C:\projects\genutils\packages\Unquote\lib\net45\Unquote.dll --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ "C:\Users\appveyor\AppData\Local\Temp\1\.NETFramework,Version=v4.5.AssemblyAttributes.fs" FsCheckAddin.fs BuildTest.fs BigRationalTests.fs 
       _CopyFilesMarkedCopyLocal:
         Copying file from "C:\projects\genutils\packages\FsCheck\lib\net45\FsCheck.dll" to "bin\Release\FsCheck.dll".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.Addin.dll" to "bin\Release\FsCheck.NUnit.Addin.dll".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.dll" to "bin\Release\FsCheck.NUnit.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.dll" to "bin\Release\FSharp.PowerPack.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.dll" to "bin\Release\FSharp.PowerPack.Linq.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.dll" to "bin\Release\FSharp.PowerPack.Metadata.dll".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.dll" to "bin\Release\FSharp.PowerPack.Parallel.Seq.dll".
         Copying file from "C:\projects\genutils\packages\FsUnit\lib\net45\FsUnit.NUnit.dll" to "bin\Release\FsUnit.NUnit.dll".
         Copying file from "C:\projects\genutils\src\Informedica.GenUtils.Lib\bin\Release\Informedica.GenUtils.Lib.dll" to "bin\Release\Informedica.GenUtils.Lib.dll".
         Copying file from "C:\projects\genutils\packages\FsUnit\lib\net45\NHamcrest.dll" to "bin\Release\NHamcrest.dll".
         Copying file from "C:\projects\genutils\packages\NUnit.Runners\tools\lib\nunit.core.dll" to "bin\Release\nunit.core.dll".
         Copying file from "C:\projects\genutils\packages\NUnit.Runners\tools\lib\nunit.core.interfaces.dll" to "bin\Release\nunit.core.interfaces.dll".
         Copying file from "C:\projects\genutils\packages\NUnit\lib\nunit.framework.dll" to "bin\Release\nunit.framework.dll".
         Copying file from "C:\projects\genutils\packages\Unquote\lib\net45\Unquote.dll" to "bin\Release\Unquote.dll".
         Copying file from "C:\projects\genutils\src\Informedica.GenUtils.Lib\bin\Release\Informedica.GenUtils.Lib.pdb" to "bin\Release\Informedica.GenUtils.Lib.pdb".
         Copying file from "C:\projects\genutils\src\Informedica.GenUtils.Lib\bin\Release\Informedica.GenUtils.Lib.xml" to "bin\Release\Informedica.GenUtils.Lib.xml".
         Copying file from "C:\projects\genutils\packages\FsCheck\lib\net45\FsCheck.pdb" to "bin\Release\FsCheck.pdb".
         Copying file from "C:\projects\genutils\packages\FsCheck\lib\net45\FsCheck.xml" to "bin\Release\FsCheck.xml".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.Addin.pdb" to "bin\Release\FsCheck.NUnit.Addin.pdb".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.Addin.xml" to "bin\Release\FsCheck.NUnit.Addin.xml".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.pdb" to "bin\Release\FsCheck.NUnit.pdb".
         Copying file from "C:\projects\genutils\packages\FsCheck.Nunit\lib\net45\FsCheck.NUnit.xml" to "bin\Release\FsCheck.NUnit.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Core.Community\Lib\Net40\FSharp.PowerPack.xml" to "bin\Release\FSharp.PowerPack.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Linq.Community\Lib\Net40\FSharp.PowerPack.Linq.xml" to "bin\Release\FSharp.PowerPack.Linq.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Metadata.Community\Lib\Net40\FSharp.PowerPack.Metadata.xml" to "bin\Release\FSharp.PowerPack.Metadata.xml".
         Copying file from "C:\projects\genutils\packages\FSPowerPack.Parallel.Seq.Community\Lib\Net40\FSharp.PowerPack.Parallel.Seq.xml" to "bin\Release\FSharp.PowerPack.Parallel.Seq.xml".
         Copying file from "C:\projects\genutils\packages\FsUnit\lib\net45\FsUnit.NUnit.pdb" to "bin\Release\FsUnit.NUnit.pdb".
         Copying file from "C:\projects\genutils\packages\FsUnit\lib\net45\FsUnit.NUnit.xml" to "bin\Release\FsUnit.NUnit.xml".
         Copying file from "C:\projects\genutils\packages\FsUnit\lib\net45\NHamcrest.pdb" to "bin\Release\NHamcrest.pdb".
         Copying file from "C:\projects\genutils\packages\NUnit\lib\nunit.framework.xml" to "bin\Release\nunit.framework.xml".
         Copying file from "C:\projects\genutils\packages\Unquote\lib\net45\Unquote.xml" to "bin\Release\Unquote.xml".
       _CopyAppConfigFile:
         Copying file from "App.config" to "bin\Release\Informedica.GenUtils.Tests.dll.config".
       CopyFilesToOutputDirectory:
         Copying file from "obj\Release\Informedica.GenUtils.Tests.dll" to "bin\Release\Informedica.GenUtils.Tests.dll".
         Informedica.GenUtils.Tests -> C:\projects\genutils\tests\Informedica.GenUtils.Tests\bin\Release\Informedica.GenUtils.Tests.dll
         Copying file from "obj\Release\Informedica.GenUtils.Tests.pdb" to "bin\Release\Informedica.GenUtils.Tests.pdb".
     2>Done Building Project "C:\projects\genutils\tests\Informedica.GenUtils.Tests\Informedica.GenUtils.Tests.fsproj" (Rebuild target(s)).
     1>Done Building Project "C:\projects\genutils\GenUtils.sln" (Rebuild target(s)).
 
Build succeeded.
    0 Warning(s)
    0 Error(s)
 
Time Elapsed 00:00:04.69
Finished Target: Build 
Starting Target: CopyBinaries (==> Build) 
Creating C:\projects\genutils\bin\Informedica.GenUtils.Lib 
Finished Target: CopyBinaries 
Starting Target: RunTests (==> CopyBinaries) 
C:\projects\genutils\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\projects\genutils\tests\Informedica.GenUtils.Tests\bin\Release\Informedica.GenUtils.Tests.dll" "-xml:TestResults.xml"  
C:\projects\genutils\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\projects\genutils\tests\Informedica.GenUtils.Tests\bin\Release\Informedica.GenUtils.Tests.dll" "-xml:TestResults.xml"  
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Running build failed.
Error:
NUnit test failed. Process finished with exit code FileNotFound (-2). 
 
--------------------------------------------------------------------- 
Build Time Report 
--------------------------------------------------------------------- 
Target         Duration 
------         -------- 
Clean          00:00:00.0021404 
AssemblyInfo   00:00:00.0202169 
Build          00:00:05.2564912 
CopyBinaries   00:00:00.0621262 
Total:         00:00:08.0157477 
Status:        Failure 
--------------------------------------------------------------------- 
  1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code FileNotFound (-2).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
   at FSI_0005.Targets.clo@197-20.Invoke(Unit _arg8) in C:\projects\genutils\paket-files\halcwb\GenBuild\scripts\targets.fsx:line 202
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
--------------------------------------------------------------------- 
Command exited with code 42
```

**Comment by halcwb** [comment]
Note that this is with the app.config redirect for FSharp.Core

**Comment by ploeh** [comment]
I may be barking up the wrong tree, but from the log, it looks like FAKE is pulling down `FSharp.Core 4.0.0.1`, while the build later complains that it can't find `FSharp.Core, Version=4.4.0.0`. Could it be the Paket configuration that points to the wrong version?

**Comment by halcwb** [comment]
I finally got it fixed, I was referencing FSharp.Core from the GAC in my test project, but it is all kinds of PITA, boiling down to not being able to upgrade to NUnit v3, if this happens I think all of the above goes away.

**Comment by kurtschelfthout** [comment]
How is this related to NUnit 3?

Anyway, if you're interested in NUnit 3 support, have a look at #98. Last I left it, NUnit 3 itself didn't seem to be ready for prime time.

**Comment by ploeh** [comment]
> Last I left it, NUnit 3 itself didn't seem to be ready for prime time.

FWIW, we released [AutoFixture.NUnit3](https://www.nuget.org/packages/AutoFixture.NUnit3) in March, and while there still seems to be a few issues, in general, I'm hearing less about this Glue Library than [the one for NUnit 2](https://www.nuget.org/packages/AutoFixture.NUnit2). The NUnit 2 extensibility model gave us a lot of grief, so even if there are a few issues with NUnit 3, it's better than NUnit 2.

If you compare the download numbers for those two packages, you can also see that [AutoFixture.NUnit3](https://www.nuget.org/packages/AutoFixture.NUnit3) is being downloaded more than [AutoFixture.NUnit2](https://www.nuget.org/packages/AutoFixture.NUnit2), now that it's available.

**Comment by ploeh** [comment]
I just latched on to your general comment about NUnit 3 :smile: I agree that it's probably not relevant in this particular case.

**Comment by halcwb** [comment]
Sorry keep nagging about nunit. With the current version of nunit used by fscheck, trying to run tests crashes on my mac:

> NUnit.Runners/tools/nunit-console.exe "-nologo" "-noshadow" "-labels" "/GenBuild.Tests.dll" "-xml:TestResults.xml" 
> /Library/Frameworks/Mono.framework/Commands/mono  "/GenBuild/packages/NUnit.Runners/tools/nunit-console.exe" "-nologo" "-noshadow" "-labels" "/GenBuild.Tests.dll" "-xml:TestResults.xml" 
> WARNING: The runtime version supported by this application is unavailable.
> Using default runtime: v4.0.30319
> ProcessModel: Default    DomainUsage: Single
> Execution Runtime: mono-4.0
> * Assertion at object.c:2189, condition `vt' not met
> 
> Stacktrace:
> 
>   at <unknown> <0xffffffff>
>   at (wrapper managed-to-native) System.Runtime.Remoting.Proxies.RealProxy.InternalGetTransparentProxy (System.Runtime.Remoting.Proxies.RealProxy,string) <0xffffffff>
>   at System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy () <0x00118>
>   at System.Runtime.Remoting.RemotingServices.GetOrCreateClientIdentity (System.Runtime.Remoting.ObjRef,System.Type,object&) <0x00268>
>   at System.Runtime.Remoting.RemotingServices.GetRemoteObject (System.Runtime.Remoting.ObjRef,System.Type) <0x00027>
>   at System.Runtime.Remoting.RemotingServices.GetProxyForRemoteObject (System.Runtime.Remoting.ObjRef,System.Type) <0x00067>
>   at System.Runtime.Remoting.RemotingServices.Unmarshal (System.Runtime.Remoting.ObjRef,bool) <0x0012b>
>   at System.Runtime.Remoting.RemotingServices.Unmarshal (System.Runtime.Remoting.ObjRef) <0x0001b>
>   at System.Runtime.Remoting.ObjRef.GetRealObject (System.Runtime.Serialization.StreamingContext) <0x00023>
>   at System.Runtime.Serialization.ObjectManager.ResolveObjectReference (System.Runtime.Serialization.ObjectHolder) <0x000fe>
>   at System.Runtime.Serialization.ObjectManager.DoFixups () <0x000ff>
>   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler,System.Runtime.Serialization.Formatters.Binary.__BinaryParser,bool,bool,System.Runtime.Remoting.Messaging.IMethodCallMessage) <0x0009a>
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler,bool,bool,System.Runtime.Remoting.Messaging.IMethodCallMessage) <0x00173>
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler,bool,System.Runtime.Remoting.Messaging.IMethodCallMessage) <0x00037>
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler,bool) <0x0002f>
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler) <0x00027>
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream) <0x0001f>
>   at System.Runtime.Remoting.RemotingServices.DeserializeCallData (byte[]) <0x00053>
>   at (wrapper xdomain-dispatch) System.AppDomain.SetData (object,byte[]&,byte[]&,string) <0xffffffff>
>   at (wrapper xdomain-invoke) System.AppDomain.SetData (string,object) <0xffffffff>
>   at (wrapper remoting-invoke-with-check) System.AppDomain.SetData (string,object) <0xffffffff>
>   at NUnit.Util.DomainManager.CreateDomain (NUnit.Core.TestPackage) <0x00803>
>   at NUnit.Util.TestDomain.Load (NUnit.Core.TestPackage) <0x0008b>
>   at NUnit.ConsoleRunner.ConsoleUi.Execute (NUnit.ConsoleRunner.ConsoleOptions) <0x00514>
>   at NUnit.ConsoleRunner.Runner.Main (string[]) <0x007c3>
>   at NUnit.ConsoleRunner.Class1.Main (string[]) <0x00013>
>   at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>
> 
> Native stacktrace:
> 
> 	0   mono                                0x00157e46 mono_handle_native_sigsegv + 342
> 	1   mono                                0x001a85f1 sigabrt_signal_handler + 129
> 	2   libsystem_platform.dylib            0x9b3d979b _sigtramp + 43
> 	3   ???                                 0xffffffff 0x0 + 4294967295
> 	4   libsystem_c.dylib                   0x9484ec34 abort + 156
> 	5   mono                                0x002fcca1 monoeg_log_default_handler + 129
> 	6   mono                                0x002fcd9b monoeg_assertion_message + 107
> 	7   mono                                0x00270e0f mono_class_proxy_vtable + 1599
> 	8   mono                                0x0027073b mono_remote_class_vtable + 59
> 	9   mono                                0x001e0c8e ves_icall_Remoting_RealProxy_GetTransparentProxy + 158
> 	10  ???                                 0x02e2d3e0 0x0 + 48419808
> 	11  ???                                 0x02e2d2a9 0x0 + 48419497
> 	12  ???                                 0x02e2c0f9 0x0 + 48414969
> 	13  ???                                 0x02e2be78 0x0 + 48414328
> 	14  ???                                 0x02e2bdc0 0x0 + 48414144
> 	15  ???                                 0x02e2bc74 0x0 + 48413812
> 	16  ???                                 0x02e2bb34 0x0 + 48413492
> 	17  ???                                 0x02e2bb0c 0x0 + 48413452
> 	18  ???                                 0x02e2b93f 0x0 + 48412991
> 	19  ???                                 0x02e0fc20 0x0 + 48299040
> 	20  ???                                 0x02e0e093 0x0 + 48291987
> 	21  ???                                 0x02e0d2ac 0x0 + 48288428
> 	22  ???                                 0x02e0d128 0x0 + 48288040
> 	23  ???                                 0x02e0d0e0 0x0 + 48287968
> 	24  ???                                 0x02e0d0a0 0x0 + 48287904
> 	25  ???                                 0x02e0d068 0x0 + 48287848
> 	26  ???                                 0x02e2a5cc 0x0 + 48408012
> 	27  ???                                 0x02e2a3c0 0x0 + 48407488
> 	28  ???                                 0x02cd843f 0x0 + 47023167
> 	29  ???                                 0x02cd9e84 0x0 + 47029892
> 	30  ???                                 0x02cb34a4 0x0 + 46871716
> 	31  ???                                 0x02cb2844 0x0 + 46868548
> 	32  ???                                 0x02cad39d 0x0 + 46846877
> 	33  ???                                 0x00741c2c 0x0 + 7609388
> 	34  ???                                 0x00740edc 0x0 + 7605980
> 	35  ???                                 0x00740fb4 0x0 + 7606196
> 	36  mono                                0x000a81aa mono_jit_runtime_invoke + 714
> 	37  mono                                0x0026d4ff mono_runtime_invoke + 127
> 	38  mono                                0x00273251 mono_runtime_exec_main + 401
> 	39  mono                                0x0027300a mono_runtime_run_main + 618
> 	40  mono                                0x00120bdd mono_jit_exec + 93
> 	41  mono                                0x00122f31 mono_main + 7985
> 	42  mono                                0x0009aa80 main + 768
> 	43  mono                                0x0009a775 start + 53
> 
> Debug info from gdb:
> 
> (lldb) command source -s 0 '/tmp/mono-gdb-commands.TwMhV0'
> Executing commands in '/tmp/mono-gdb-commands.TwMhV0'.
> (lldb) process attach --pid 6430
> 

I also filed a bug report of this: https://bugzilla.xamarin.com/show_bug.cgi?id=40785. But no response as of yet. Another argument to upgrade NUnit 3?

**Comment by kurtschelfthout** [comment]
Sorry for the very late reply. I think this is perhaps due to:
WARNING: The runtime version supported by this application is unavailable.

Perhaps there is a mismatch between the nunit exe and the version of mono you're using?

In any case I don't think this is an FsCheck problem (modulo it supporting NUnit 3, but we have another thread for that).

**Comment by kurtschelfthout** [comment]
Closing as unclear what we can do here. Feel free to re-open though if I missed something.
