### ISSUE TITLE
Property fails when exception is thrown, even if property is `or`-ed with another true property

### ISSUE THREAD

**Issue by Alxandr** [fscheck/FsCheck#280]
I would expect the following to work just fine:

```fsharp
let a =
  Prop.ofTestable <| lazy
    failwith "crash"

let b =
  Prop.ofTestable <| lazy
    true

a .|. b
```

However, currently it just forwards the exception. Is there any way I can get around this while composing Properties? I currently have a helper `(===)` that checks equality, and if it's not equal throws (because it gives me error messages that actually shows where it went wrong and what values were given).

**Comment by ploeh** [comment]
I realise this isn't what you're asking about, but since you wrote that you

> have a helper `(===)` that checks equality, and if it's not equal throws (because it gives me error messages that actually shows where it went wrong and what values were given)

I was wondering if you were aware of [Unquote](http://www.swensensoftware.com/unquote)?

**Comment by Alxandr** [comment]
@ploeh Nope, I have not. Though I don't really see the relevance. My problem is that I have properties (taking arbitrary arguments) which I need to test, while still wanting to get error messages showing me what assertion failed *and* being able to compose `'testable`'s together.
