### ISSUE TITLE
Allow to run a suite of tests with the same seed

### ISSUE THREAD

**Issue by theimowski** [fscheck/FsCheck#282]
I have a somewhat unusual case for using FsCheck, as I once described [in my blog post](http://theimowski.com/blog/2015/12-21-property-based-testing-xslt/index.html).

Now, while I found it convenient to use `[<Property>]` attribute for my properties to nicely integrate with XUnit, I discovered that test run performance was very poor due to fact that most of time was spent in the XSLT processor (N tests multiply 100 runs = 100*N XSLT processor invocations).
I've workaround this issue by using a custom sub-type of `Property` attribute:

```fsharp
type XsltProperty() =
    inherit FsCheck.Xunit.PropertyAttribute(Replay  = XsltProperty.Seed)
    
    static let seed = 
        let (FsCheck.Random.StdGen(a,b)) = FsCheck.Random.newSeed()
        sprintf "%d,%d" a b

    static member Seed with get() = seed
```

Because `Seed` member is static, its value is set upon first invocation, and all functions marked with `[<XsltProperty>]` will always run with the same seed (the seed will differ between one run and another).
Thanks to this, I was able to **memoize** XSLT processing for a specific XML document, and thus reduce number of XSLT processor invocations from 100*N to 100.

I'm wondering whether it might be worth adding something similar to the FsCheck itself (maybe only to the XUnit plugin?), which would allow to run a set of tests with the same seed. 
What you think?

**Comment by kurtschelfthout** [comment]
Not to diminish the value of your particular case, but it sounds like it adds too limited general purpose value. To do this I think we'd have to add a new attribute that users can put on the module or type level - that sounds like a bit too much for this one feature. Perhaps though we could add a more general configuration attribute where we could set all the configuration as on the `PropertyAttribtue`, but it would take effect on all the tests in the type/module. But then we'd also have to make sure that the `PropertyAttribute` on the method level properly overrides these.

**Comment by moodmosaic** [comment]
>Perhaps though we could add a more general configuration attribute where we could set all the configuration as on the PropertyAttribtue, [..]. But then we'd also have to make sure that the PropertyAttribute on the method level properly overrides these.

Doesn't it sound a bit complicated?

---

IIRC, there's already a *Replay* functionality which is set to `None` by default, and setting it to `Some StdGen` will make the test to be replayed in the exact same way.

**Comment by theimowski** [comment]
That's right - I'm not sure whether my use case is worth the hussle implementing such configuration in FsCheck itself.
@moodmosaic  - yes `Replay` is what I'm using at the moment, however I need to set up the same `Replay` value for all my tests, plus I need to make sure that this `Replay` value differs between two tests runs.

I'll have a look around the codebase and see if this could be done without too much interference - if not I'll close the issue.

**Comment by kurtschelfthout** [comment]
> Doesn't it sound a bit complicated?

Not more complicated than what is already there for Arbitrary overrides.

**Comment by moodmosaic** [comment]
>Not more complicated than what is already there for Arbitrary overrides.

That's a different story though, and we should be fixing it on `v3`.

**Comment by kurtschelfthout** [comment]
> That's a different story though, and we should be fixing it on v3.

Disagree. My expectation is that this aspect of configuration in FsCheck.Xunit will remain exactly as is, from the user's perspective. You are probably referring to changes in how Arbitrary instances are registered/configured that are planned for v3, but that is an orthogonal issue.

**Comment by moodmosaic** [comment]
Oops, yes. Sorry. :flushed:

**Comment by kurtschelfthout** [comment]
Closing as this is done and released.
