### ISSUE TITLE
Signing assembly makes property tests vanish

### ISSUE THREAD

**Issue by T-Becker** [fscheck/FsCheck#292]
I have a single F# assembly where I collect property based tests of several other assemblies. Recently I needed access to an internal of an assembly under test. That meant I needed the `InternalsVisibleTo` attribute and had my F# assembly signed.

As soon as I put `[<assembly: AssemblyKeyFileAttribute("keypair.snk")>]` into *AssemblyInfo.fs* all tests marked with `Property` disappear from VS2015's test runner window. After commenting out the assembly attribute, all tests come back.

Even more, I can make the remaining `Fact` tests disappear by putting a stupid property test in the same file:
`[<FsCheck.Xunit.Property>] let foo () = true`

Removing that line brings back the `Fact` tests from the same file.

PS: I'm running _FSharp.Core v.3.1.2.5_ and have the binding redirect in the _App.config_, but it doesn't make a difference.
`<dependentAssembly>
<assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
</dependentAssembly>`

And here are the version numbers:

- FsCheck                             {2.5.0}
- FsCheck.Xunit                       {2.5.0}
- FSharp.Core                         {3.1.2.5}
- xunit                               {2.1.0}
- xunit.abstractions                  {2.0.0}
- xunit.assert                        {2.1.0}
- xunit.core                          {2.1.0}
- xunit.extensibility.core            {2.1.0}
- xunit.extensibility.execution       {2.1.0}
- xunit.runner.visualstudio           {2.1.0}

**Comment by ploeh** [comment]
IIRC, FsCheck isn't signed with a strong name, so does your test project even compile when your attempt to sign it?

AFAIK, you can only strong-name sign an assembly if all it dependencies are also strong-name signed.

**Comment by kurtschelfthout** [comment]
What @ploeh said, and to pre-empt your potential next question, signing FsCheck is not on the table. You can of course build from source + sign yourself. You may want to check out https://github.com/dsplaisted/strongnamer/ which seems to make this relatively easy, have not tried it myself though.

**Comment by T-Becker** [comment]
@ploeh: Yes, it does compile.

@kurtschelfthout: If that is the decision for FsCheck, that's ok. But aren't the described effects strange anyways?

**Comment by kurtschelfthout** [comment]
Yeah I would have expected a compile error too...I think perhaps because of the dynamic loading, something goes wrong during loading of the test assembly only when it has to load FsCheck (i.e. when you have a Property attribute in there so you actually use FsCheck)

**Comment by kurtschelfthout** [comment]
Not sure what to do with this so closing. Feel free to re-open if I missed something.
