### ISSUE TITLE
Add a section to the main page for Examples?

### ISSUE THREAD

**Issue by dlr2** [fscheck/FsCheck#294]
I used FsCheck in my F# tutorial, the [testing part](http://www.opcoast.com/demos/fsharp/part3.html), its not on Github now (but could be I suppose). Would it make sense to add a section to the main page with header 'Examples' with a link thereto?

**Comment by kurtschelfthout** [comment]
Sure, just add it to the Learning Resources section: https://fscheck.github.io/FsCheck/LearningResources.html

**Comment by dlr2** [comment]
Done. Thanks
Dave

**Comment by kurtschelfthout** [comment]
Brilliant, thanks. And great tutorial!
