### ISSUE TITLE
FsCheck.xUnit has incomplete source information in Visual Studio

### ISSUE THREAD

**Issue by ashwinsathyar** [fscheck/FsCheck#297]
![screenshot](https://cloud.githubusercontent.com/assets/2137463/17392254/03c5313e-59d1-11e6-9d16-0ff854a17d56.PNG)
I have a <Property> based test like the following

`module Foo = 
    [<Property>]
    let ``Reverse of reverse of a list is the original list ``(xs:list<int>) =
        List.rev(List.rev xs) = xs`

The discovered test in Test Explorer isn't having the appropriate Source code information.
Clicking the test in the Test Explorer in visual studio gives the following in the pane where the source file name and line information is displayed.

Source: no source available.

Looks like when the test is discovered the xUnit is unable to set the "CodeFilePath" and "LineNumber" information in the TestCase object.

**Comment by kurtschelfthout** [comment]
I can't reproduce this. I create a new Visual Studio 2015 F# Library project, installed FsCheck.Xunit and xunit.runner.visualstudio in it, copy pasted your code above and it works:

 
![image](https://cloud.githubusercontent.com/assets/164917/17396298/adc6f420-5a2a-11e6-9229-67d3c99e2642.png)

**Comment by ashwinsathyar** [comment]
Strange!! I did the same steps. It doesn't work.
Following is the dump of my packages.config

  <package id="FsCheck" version="2.6.0" targetFramework="net452" />
  <package id="FsCheck.Xunit" version="2.6.0" targetFramework="net452" />
  <package id="FSharp.Core" version="3.1.2.5" targetFramework="net452" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net452" />
  <package id="xunit.extensibility.core" version="2.1.0" targetFramework="net452" />
  <package id="xunit.extensibility.execution" version="2.1.0" targetFramework="net452" />
  <package id="xunit.runner.visualstudio" version="2.1.0" targetFramework="net452" />

Are you running on the same set ?

**Comment by kurtschelfthout** [comment]
Yes, same set. Not sure what can cause this...

**Comment by tlycken** [comment]
I'm seeing this behavior too in a new project (in which I've admittedly mucked around a bit since I'm pretty new to this and don't really know what I'm doing...). I'll see if I can get it to work in a fresh solution, and if not, I'll try to work out why...

**Comment by kurtschelfthout** [comment]
Cool, thanks @tlycken . Must admit this one has me a bit stumped as I cannot seem to reproduce.

**Comment by 0x53A** [comment]
Just one random idea: do you maybe not generate a pdb file? I think this is required for VS to map the method to file / line.

**Comment by tlycken** [comment]
I'm sorry, but I may have just made a stupid newbie error and tripped over this. It turns out I had managed to declare my tests as values rather than functions. Compare these two:

```
let ``this won't work`` =
    true

let ``this will, though`` () =
   true
```

When I fixed that, tests are discovered in all my cases. Sorry for the noise... :(

**Comment by ploeh** [comment]
@tlycken, if it helps, I've made that mistake at least once within the last 6 months :flushed: Took me some time to figure out, too...

**Comment by kurtschelfthout** [comment]
Seems like this was solved or at least not reproducible.
