### ISSUE TITLE
null string not generated by default

### ISSUE THREAD

**Issue by mathias-brandewinder** [fscheck/FsCheck#30]
Consider the following:

let longEnough (s:string) = s.Length > 10
let check (s:string) = 
    s.Length <= 10 ==> (longEnough s = false)
Check.Quick check

let (bad:string) = null
longEnough (bad)

I would have expected FsCheck to propose a null string as a counter-example. Would love to hear if this is by design (and why), or by accident.

**Comment by arialdomartini** [comment]
I honestly find this inconvenient.

Adding on top of @ploeh's comment: I might be wrong, but asking FsCheck to generate

    type Foo = {
        Bar : Bar
        Baz : Baz
        Qux : Qux }

and avoiding null values requires a lot of boiler plate code.
It would be nice to have a global configuration to completely get rid of null values.
