### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by Thorium** [fscheck/FsCheck#304]
I find this library very hard to take in use with existing frameworks like NUnit or xUnit.

I tried first with NUnit. FsCheck and FsCheck.NUnit, it added my project this `FsCheckAddin.fs ` which broke the build. `open NUnit.Core.Extensibility` NUnit.Core is not defined. Also NUnitAddin doesn't exist. So I excluded the file and didn't help, other errors... Ok, maybe NUnit samples have expired. Maybe no-one uses NUnit even if it's the default with ProjectScaffold. So I went for xUnit.

No luck either. F# examples in the source repo: None
This is how far I got with my xUnit test:

```fsharp
(*
paket.dependencies:
FSharp.Core

// Testing frameworks:
group Test
  source https://nuget.org/api/v2
  framework >= 4.0

  nuget canopy
  nuget FsUnit.xUnit
  nuget xunit.core
  nuget xunit.abstractions
  nuget xunit.runner.visualstudio >= 2.0 version_in_path: true
  nuget xunit.runner.console
*)
namespace TestingFsCheck
#if INTERACTIVE
#I "../../packages/test/xunit.extensibility.core/lib/portable-net45+win8+wp8+wpa81/"
#r "../../packages/test/xunit.extensibility.core/lib/portable-net45+win8+wp8+wpa81/xunit.core.dll"
#I "../../packages/test/xunit.assert/lib/dotnet/"
#r "../../packages/test/xunit.assert/lib/dotnet/xunit.assert.dll"
#I "../../packages/test/FsUnit.xUnit/lib/net45/"
#r "../../packages/test/FsUnit.xUnit/lib/net45/NHamcrest.dll"
#r "../../packages/test/FsUnit.xUnit/lib/net45/FsUnit.Xunit.dll"
#endif

open System.Linq.Expressions
open Xunit
open FsUnit.Xunit
open FsCheck
open System
open System.Collections.Generic
open System.Linq
open System.Linq.Expressions
open Microsoft.FSharp.Linq.RuntimeHelpers
open NHamcrest.Core
open Xunit.Extensions

// https://fsprojects.github.io/FsUnit/
type ``My fixture`` ()=

    [<Theory>] member test.
     ``myTest`` (xs : int[]) =
        should equal xs (Array.rev xs)

// How do I fill the theory?
```

**Comment by ploeh** [comment]
IIRC, FsCheck.NUnit is still based on NUnit 2, which has a horrible extensibility model. From a consumer's perspective, it means that you can't expect to just pull down FsCheck.NUnit (or anything else that attempts to extend NUnit 2) and expect it to 'just work'. It's unfortunate, but is an effect of how NUnit 2 is designed. AFAIK, there's not a lot that package publishers can do to make that situation better. It just _is_ that brittle.

With NUnit 3, things are better, but I don't think FsCheck has made that move yet.

The xUnit.net integration, on the other hand, is fairly smooth, but you shouldn't use `[<Theory>]`, but rather FsCheck.Xunit's `[<Property>]` attribute.

The [documentation demonstrates this](https://fscheck.github.io/FsCheck/RunningTests.html), as well as many other aspects of executing FsCheck properties.

In addition to the documentation, I have a ton of examples on my blog. One place to start could be with the [Types + Properties = Software](http://blog.ploeh.dk/2016/02/10/types-properties-software) article series, where all but the first two articles show FsCheck examples. This article series is backed by [sample code on GitHub](https://github.com/ploeh/KataTennis) that you can download and examine.

Another example code base is https://github.com/ploeh/DiamondFsCheck, which also comes with some blog posts. If you want to see examples of more advanced combinators, you can take a look at my article on doing the [Roman Numerals kata with FsCheck](http://blog.ploeh.dk/2016/06/28/roman-numerals-via-property-based-tdd).

Additionally, if you don't mind throwing a few cents my way, you can watch my Pluralsight course [Introduction to Property-based Testing with F#](http://bit.ly/property-based-testing-intro), perhaps with selections from [Unit Testing with F#](http://bit.ly/unittestingwithfsharp) or some of my other F# Pluralsight course.

HTH

**Comment by kurtschelfthout** [comment]
> No luck either. F# examples in the source repo: None

Eh?

NUnit examples:
https://github.com/fscheck/FsCheck/blob/master/examples/FsCheck.NUnit.Examples/PropertyExamples.fs

xUnit examples, pretty much every file here:
https://github.com/fscheck/FsCheck/tree/master/tests/FsCheck.Test
