### ISSUE TITLE
x + 1 > x : should int generator be more aggressive?

### ISSUE THREAD

**Issue by mathias-brandewinder** [fscheck/FsCheck#307]
I'll start by stating the case that got me thinking:

```
let ``x + 1 > x`` x =
    x + 1 > x
Check.Quick ``x + 1 > x``
```
> Ok, passed 100 tests.

But "obviously" `Int32.MaxValue + 1 > Int32.MaxValue` is `false`.

I am a bit torn here, and would be interested to hear thoughts.

On one hand, FsCheck failed to find a relatively simple counter-example here, where, for instance, it finds counter-examples for the equivalent `float` case pretty quick.

On the other hand, I can see how systematically exercising edge cases (for instance, all the special cases for `float` or `int`) might get in the way for more vanilla cases. 

If I write numeric code, I want these edge cases to be caught. If I write more "businessy" code, I probably don't care about what happens when the number of `Widget` ordered is `Int32.MaxValue`, or the `Widget` price is `-infinity`, my focus is probably more on other ways my business logic could be incorrect, and having to specify that the `int` or `float` is not degenerate might become quite annoying.

So - bug or no bug? Am I thinking too much of FsCheck in the same light as Pex, as an edge-case hunter? Perhaps it would be useful to have something like a `hardcore` flag taking more aggressive behaviors?

**Comment by kurtschelfthout** [comment]
Yes, the `int` generator is a bit of an odd one out perhaps. I think it is a matter of choosing nice defaults.

If you want the min and max you can use `IntWithMinMax`: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Arbitrary.fs#L67

I think if you use floats it's more likely that you are doing some kind of scientific calculation, where NaN and rounding errors will bite you eventually, so it kind of makes sense for FsCheck to focus on that by default.

For `int` I'm not convinced it's the same story. For example, other generators, like in fact the float generator, depend on the int generator - the min and max values would have to be filtered out more often than not I reckon.

Of course, this is just conjecture. Overall I can see both arguments; but given I don't see a strong argument either way, I prefer to maintain the status quo to avoid disruption for users. 

Re: pex - Pex is much more of an edge case finder than FsCheck, which has to rely on heuristics or programmer supplied generators. On the other hand, this is much cheaper and scales to larger systems;  neither is guaranteed find all bugs, but either will very likely find some bugs. Things are never easy :)

Re: the `hardcore` flag. My gut feeling is that I would prefer the generators to be modular, i.e. independent of any harder to find background settings or flags. That is possible by either making parametrized generators (like `Gen.choose` which chooses an int in a given interval) or by adding new "derived" types like `PositiveInt` and `IntWithMinMax` for (from F# at least) easily accessible and readable tweaking of the behavior:

    let ``x + 1 > x`` (IntWithMinMax x) = ...

**Comment by mathias-brandewinder** [comment]
Thanks for the reply, and the pointer to `IntWithMinMax` - I think that addresses my issue, and I agree with your point regarding not disrupting current users. I won't close it just yet, in case others want to comment, but I am happy to see this issue closed!

**Comment by mathias-brandewinder** [comment]
Closing it now - happy with the explanation :)
