### ISSUE TITLE
Consider replacing the custom Type Class simulation mechanism with Trait F#

### ISSUE THREAD

**Issue by moodmosaic** [fscheck/FsCheck#313]
One day, when the [Trait F#](https://github.com/CaptainHayashi/visualfsharp/blob/hackathon-vs/examples/fsconcepts.md) concept gets released it could replace the custom [Type Class simulation](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/TypeClass.fs) used by FsCheck.

**Comment by kurtschelfthout** [comment]
Don't disagree but see little point in keeping an issue open for that.

**Comment by moodmosaic** [comment]
Agreed. – And even closed, this is more discoverable than a Twitter discussion. 😃
