### ISSUE TITLE
VS-Integration: FsCheck.XUnit does not show currently executing test

### ISSUE THREAD

**Issue by 0x53A** [fscheck/FsCheck#324]
When I run a XUnit Property test, the test is greyed out and when it finishes, it gets either the green check or the red icon:

![image](https://cloud.githubusercontent.com/assets/4236651/19393229/23c3748c-9234-11e6-80b2-387882e512d1.png)

![image](https://cloud.githubusercontent.com/assets/4236651/19393178/f3a1056c-9233-11e6-8941-7bc1c0817086.png)

When I run a long running Fact, I can see an in-progress icon:

![image](https://cloud.githubusercontent.com/assets/4236651/19393217/162ffdd6-9234-11e6-81ab-5f703c7d70dd.png)

![image](https://cloud.githubusercontent.com/assets/4236651/19393205/0e9580fa-9234-11e6-8c1d-31be724052c6.png)

Since Property tests can potentially take a long time, it would be great to see which test is currently executing.

**Comment by kurtschelfthout** [comment]
Yeah...any idea how to do that? I assume we need to put some message on xunit's message bus, we're already putting `TestStarting` perhaps something else is needed.

https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L234
