### ISSUE TITLE
DoNotSize generators are skewed

### ISSUE THREAD

**Issue by ploeh** [fscheck/FsCheck#332]
It looks like some of the DoNotSize generators are skewed:

```
> Arb.generate<DoNotSize<int64>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(-1, 988696); (1, 11304)]

> Arb.generate<DoNotSize<uint64>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(0, 359391); (1, 640609)]

> Arb.generate<DoNotSize<int32>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(1, 371659); (-1, 628341)]

> Arb.generate<DoNotSize<uint32>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(1, 500065); (0, 499935)]

> Arb.generate<DoNotSize<int16>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(1, 499986); (-1, 500002); (0, 12)]

> Arb.generate<DoNotSize<uint16>>
    |> Gen.map (fun (DoNotSize x) -> float x)
    |> Gen.sample 0 1000000
    |> List.countBy sign;;
val it : (int * int) list = [(1, 999985); (0, 15)]
```

The 16-bit generators both look good, the 32-bit generators are suspect, and the 64-bit generators are skewed by orders of magnitude.

I expected these generators to generate values drawn from a uniform distribution across their entire range, but that seems not to be the case. Is this on purpose? If so, why?

**Comment by kurtschelfthout** [comment]
I'm afraid this may reflect the "badness" of the current random number generator - and hence why there is a replacement on the fscheck3 branch.

The replacement generates uniform numbers (at least, the authors of the paper I implemented ran a decent battery of statistical tests on the output) within the full int64 range. The current implementation generates _untested_ uniform output in _almost_ the int32 range. Afaik there is paper by Koen Claessen et al that shows some pretty skewed results with this random generator.

Would be useful to repeat the experiment with the replacement...and re-invigorate the fscheck3 effort (that's more for me than for anyone else, been having fun contributing to the F# compiler lately...)
