### ISSUE TITLE
FsCheck prints to stdout

### ISSUE THREAD

**Issue by haf** [fscheck/FsCheck#336]
FsCheck seems to print to stdout, which is a problem for Expecto, which can run in parallel and thus may interleave characters with FsCheck.

Can I configure the logger? What would you say about me PRing Logary's Facade that supports replacing the printer and is a single file?

**Comment by kurtschelfthout** [comment]
You should already be able to write a custom runner like in FsCheck.Xunit that gets callbacks when there is anything to print, and redirect those. xunit 2.0 is also MT so we did a similar thing there.

**Comment by haf** [comment]
Good. I'll track this in expecto then. Thank you.
