### ISSUE TITLE
How to use Gen.Map in C# Core?

### ISSUE THREAD

**Issue by johnnymo87** [fscheck/FsCheck#343]
Hi, this is a great library, but I'm struggling with some of the more advanced use-cases on C# core. This is a bit more of a C# core question than an fscheck question, but I figured I'd ask here first before [corefx](https://github.com/dotnet/corefx).

I am trying to use `Gen.Map` on C# core (1.0.0), and I am struggling to supply it with the F# function that it requires. The closest I've come is from the [helios-io project](https://github.com/helios-io/helios), which is C# but I believe not C# core. They wrote [some helper functions](https://github.com/helios-io/helios/blob/dev/tests/Helios.FsCheck.Tests/FsharpDelegateHelper.cs#L12-L16) which handles the conversion from C# lambdas to F# functions:
```cs
public static FSharpFunc<T2, TResult> Create<T2, TResult>(Func<T2, TResult> func)
{
    Converter<T2, TResult> conv = input => func(input);
    return FSharpFunc<T2, TResult>.FromConverter(conv);
}
```
[Here is an example](https://github.com/helios-io/helios/blob/dev/tests/Helios.FsCheck.Tests/Channels/Sockets/TcpServerSocketChannelStateMachine.cs#L324-L327) of it in action:
```cs
Func<int, IEventLoopGroup, Operation<ITcpServerSocketModel, ITcpServerSocketModel>> producer =
                    (s, e) => new ClientConnect(s, e) as Operation<ITcpServerSocketModel, ITcpServerSocketModel>;
var fsFunc = FsharpDelegateHelper.Create(producer);
return Gen.Map2(fsFunc, Gen.Choose(1, 10), GenClientEventLoops().Generator);
```

Unfortunately, it seems that `Converter` is not available in C# core: `The type or namespace name 'Converter<,>' could not be found`. I've also tried `System.Converter` and `Microsoft.FSharp.Core.Converter`, no luck there either.

Any advice?

**Comment by mausch** [comment]
Generally speaking, when using FsCheck in C# you shouldn't have to worry about converting to/from FSharpFuncs (unless of course you're actually trying to test F# code!)

In particular, `map` is called `Select` in C#.

Check out the examples in https://github.com/fscheck/FsCheck/blob/master/examples/FsCheck.CSharpExamples/Program.cs .

**Comment by kurtschelfthout** [comment]
All the functions that take an F# function have a counterpart that take a `Func` in C#.  For `Map`, you should use the more idiomatic `Select` in C#.

The examples in https://fscheck.github.io/FsCheck/TestData.html#Useful-Generator-Combinators currently only show the F# variants, unfortunately.

**Comment by kurtschelfthout** [comment]
@mausch you're 10 seconds faster! :)

**Comment by johnnymo87** [comment]
Wow, I should tried the obvious thing first. `Select` works like a charm, thanks!
