### ISSUE TITLE
Stackoverflow in shrinking

### ISSUE THREAD

**Issue by 0x53A** [fscheck/FsCheck#344]
moved from here: https://github.com/fscheck/FsCheck/issues/189

I have the issue that sometimes XUnit is terminated with a stackoverflow.
Attaching the debugger afterwards shows that the SO is inside my test code, but the root cause is that FsCheck used up wayyy to many frames.

[fscheck_sox.txt](https://github.com/fscheck/FsCheck/files/757928/fscheck_sox.txt)

my guess would be that the cause is here: https://github.com/fscheck/FsCheck/blob/0bad7cc56e843ad4f44898feb879d0e2a4c22ac9/src/FsCheck/Runner.fs#L89

for each iteration it wraps the value in one Skip.
So if you have a test which generates a lot of Shrinks (which I do), then each shrink consumes I think three callframes. (as far as I understand it, if you use Skip, it wraps the original enumerable in a new object.)

I guess the solution would be to not use Skip but call .GetEnumerator, and use .Current / .MoveNext().

**Comment by 0x53A** [comment]
Unfortunately I couldn't yet reliably reproduce the stackoverflow, so I couldn't test if this really solves the issue, but I am optimistic ...

My work firewall mucks with github authentication, so I can't upload code, but the following diff should hopefully fix this:


[fix.patch.txt](https://github.com/fscheck/FsCheck/files/758024/fix.patch.txt)

replace shrinkResult with

```F#
    let rec private shrinkResult (result:Result) (shrinks:IEnumerator<Rose<Result>>) =
        seq { if (shrinks.MoveNext()) then
                //result forced here
                let (MkRose ((Lazy result'),shrinks')) = shrinks.Current
                if result'.Outcome.Shrink then yield Shrink result'; yield! shrinkResult result' (shrinks'.GetEnumerator())
                else yield NoShrink result'; yield! shrinkResult result shrinks
              else
                yield EndShrink result
        }
```

and adapt the call:
![image](https://cloud.githubusercontent.com/assets/4236651/22696507/84e81b3a-ed4e-11e6-9c16-553053a00364.png)


I have run the tests from the project FsCheck.Test and they were all green.

**Comment by kurtschelfthout** [comment]
I can't reproduce this, even when creating a Arbitrary instance + test that goes through the `Seq skip` recursion a gazillion times. I have also tried a few other cases like alternatively successful shrink then unsuccessful one etc. It must be some particular pattern of shrinkage.

**Comment by 0x53A** [comment]
So I think I figured it out.

You need to have a test which fails the first iteration. The arbitrary then needs to generate a large number of shrinks, which all pass.

Each time a shrink passes, the enumerable is wrapped once in Skip (see shrinkResult in Runner.fs/line99).

The following code causes an increased callstack in each iteration for me:

```F#
type DemoType = DemoType of int
    with member x.I =
            match x with
            | DemoType i -> i

type MyGenerators =
    static member FilterModel =
        { new Arbitrary<DemoType>() with
            override __.Generator =
                Gen.constant 1 |> Gen.map (fun i -> DemoType i)
            override __.Shrinker model = Seq.initInfinite (fun i -> DemoType(i + model.I + 1))
        }


module Tests =
    
    [<FsCheck.Xunit.Property(Arbitrary=[|typeof<MyGenerators>|], MaxFail=1000, MaxTest=100, EndSize=1000)>]
    let ``my test``(x : DemoType) =
        if x.I = 1 then
            Xunit.Assert.False(true)
        ()
```

I will now check whether my proposed fix actually fixes that, brb

**Comment by 0x53A** [comment]
With the proposed changes from my first comment, I can observe a constant stackspace.
Also, the iterations are way faster, I got up to >10k in a few seconds (and ``new System.Diagnostics.StackTrace().FrameCount`` is still at 47)

**Comment by 0x53A** [comment]
PR sent. This also explains why my property test only failed intermittently:

The test runs against a database, so when the DB is cold, the first iteration fails sometimes (timeout or so).
But since there is nothing actually wrong with the code, all subsequent shrinks then pass, causing the Stackoverflow.

**Comment by 0x53A** [comment]
@kurtschelfthout , do you have any plans for when you will release the next version on nuget? Thanks!

**Comment by kurtschelfthout** [comment]
Shouldn't be too long, want to look at a few smaller issues first. Meanwhile feel free to get the latest build from AppVeyor, see the readme for how to do that.
