### ISSUE TITLE
Running model-based tests with NUnit

### ISSUE THREAD

**Issue by helinko** [fscheck/FsCheck#348]
Is this even possible? If I try to run something like [this](https://github.com/fscheck/FsCheck/blob/master/examples/FsCheck.NUnit.CSharpExamples/ClassesToTest/CounterSpec.cs), NUnit doesn't find the tests because there are no attributes. And there doesn't seem to be any documentation on which attributes to use and where. So am I missing something or is this just not supported?

**Comment by kurtschelfthout** [comment]
You're missing this: https://github.com/fscheck/FsCheck/blob/master/examples/FsCheck.NUnit.CSharpExamples/Examples.cs#L26

**Comment by helinko** [comment]
Oh right. I tried that earlier but got confused by some other errors in my properties. Anyways, thanks!
