### ISSUE TITLE
Not able to register type

### ISSUE THREAD

**Issue by Eitilt** [fscheck/FsCheck#353]
I'm trying to create generators for testing a custom Stream concatenation implementation, but am getting stuck on registering my test types. I've tried taking out the `private` as well as putting the `Arb.register` call in both files, in `main`, and even seeing if it needed an actual property check to trigger, but no matter what I do, I get a `System.Exception` thrown from `Gen.sample` that says `'The type Generators+ReadableStream is not handled automatically by FsCheck. Consider using another type or writing and registering a generator for it.'` For reference, my setup currently (I'll be refactoring out the shared code once I know everything works) looks like this:

**Generators.fs**
```
module Generators

open System.IO
open FsCheck

type private ReadSeekWriteStream (bytes) =
    inherit MemoryStream (bytes, true)
    let buffer = bytes

    override stream.ToString () =
        sprintf "read, seek, write : %A" buffer


    static member Generate =
        Gen.apply
        <| gen {
                return fun bs -> new ReadSeekWriteStream (bs) :> Stream
            }
        <| Gen.sized (fun len -> Gen.arrayOfLength len Arb.generate<byte>)

type private ReadSeekStream (bytes) =
    inherit MemoryStream (bytes, false)
    let buffer = bytes

    override stream.ToString () =
        sprintf "read, seek, _____ : %A" buffer


    static member Generate =
        Gen.apply
        <| gen {
                return fun bs -> new ReadSeekStream (bs) :> Stream
            }
        <| Gen.sized (fun len -> Gen.arrayOfLength len Arb.generate<byte>)

// ...

type ReadableStream =
    static member ArbInstance () =
        [ ReadSeekWriteStream.Generate
        ; ReadSeekStream.Generate
        // ...
        ]
        |> Gen.oneof
        |> Arb.fromGen
Arb.register<ReadableStream> () |> ignore
```
**Program.fs**
```
open FsCheck

open Generators

[<EntryPoint>]
let main argv =
    Gen.sample 5 5 Arb.generate<ReadableStream>
    |> printfn "%A"
    
    printfn "Press any key to close..."
    System.Console.ReadKey () |> ignore

    0 // return an integer exit code
```

Any idea what might be going wrong?

Yes, I know people often recommend `Prop.forAll` and passing the `Arbitrary` explicitly, but I find the simple `'a -> bool` properties as used in [the documentation](https://fscheck.github.io/FsCheck/Properties.html) much more functional and (moreover) readable and would rather not give up on it if I don't have to; also, from reading the other issues on here, it seems like the entire mechanism will be overhauled in v3, but I'd rather not wait until that comes out to get this working.

While I'm here, is there any way to use `Gen.oneOf` and still get the benefits of a custom shrinker? I'd rather not test each of the permutations individually (hence the wrapping `ReadableStream` and similar types), but it seems like not even `Arb.fromGenShrink` or `Arb.fromGenShrinkFunc` would allow me to get the shrinker based on the chosen type. Or does the `Gen.sized` handle that for me automatically?

**Comment by ploeh** [comment]
It looks like in your `main` function, you're requesting a `ReadableStream`, which is your 'typeclass'.

AFAICT, `ReadableStream` defines a generator for `Stream` values, so if you use `Arb.generate<Stream>` it might work.

I haven't tried it, though...

**Comment by Eitilt** [comment]
Just checked, and it still throws the same exception. Besides, I'd eventually like to have different specializations of `Stream` to test specific methods (`ReadableStream` will be complemented with `WritableStream`, `SeekableStream`, and anything else that would help -- think `PositiveInt`) as well as a separate generator for `Stream` that can give any combination.

**Comment by kurtschelfthout** [comment]
Are you sure? I just tried using `Arb.generate<Stream>` in your main function and it works...

Your approach of having different generates and putting them together in a generator for a supertype should work.

**Comment by kurtschelfthout** [comment]
> While I'm here, is there any way to use Gen.oneOf and still get the benefits of a custom shrinker? I'd rather not test each of the permutations individually (hence the wrapping ReadableStream and similar types), but it seems like not even Arb.fromGenShrink or Arb.fromGenShrinkFunc would allow me to get the shrinker based on the chosen type. Or does the Gen.sized handle that for me automatically?

If I understand what you're asking, in the shrinker for the `Stream` you'd have to do type tests and dispatch to the shrinkers for each type manually. But the type of shrinkers is `'T -> seq<'T>` so you can certainly do that. Perhaps it would be useful to expose dynamic versions of `Arb.generate` and `Arb.shrink` to alleviate some of the tedious coding involved.

**Comment by Eitilt** [comment]
I agree that everything should work, but it's not. I've extracted the files into a minimal project and uploaded it [to Dropbox](https://www.dropbox.com/s/o8d8fd0ead3nfl2/example-fscheck-gen.zip?dl=0) in case the issue's somewhere else in my setup, if you don't mind checking. The code's still set up for `Arb.generate<ReadableStream>`, but that's easy enough to switch over (I was also commenting-out the `Arb.register<Stream>` on line 43 when I did).

And that makes sense with the shrinker. I'll see what I can put together once the generator's working.

**Comment by kurtschelfthout** [comment]
Just move the `Arb.register<ReadableStream> () |> ignore` to your `main` function or otherwise call a function in the `Generators` module. Static initialization of a module in F# is only done when you access a type or function in that module.

I didn't have that problem because I pasted your `main` function in the `Generators` module when I tried it.

**Comment by Eitilt** [comment]
That's definitely good to know, but even after moving my generators code to my `Program.fs` (and commenting out the registration of the base `Stream`, as that wasn't recognizing that I extended the class -- I left the `ReadableStream` registration intact), I'm still getting the same exception no matter if I have the `Arb.register` in the same file or in the `main` just before the generator needs to be used. Unless it's something to do with using FSharp.Core 4.1.0 rather than the minimum 3.1.2.5 (which I need to do or things panic even harder), I'll just chalk it up to "something on my computer is being really strange" and pass the generator explicitly until v3. Thanks for the help, though!

**Comment by kurtschelfthout** [comment]
To be clear, `Arb.register<ReadableStream>()` will register an Arbitrary instance of type `Stream`, so  `Arb.generate<Stream>()` works, but `Arb.generate<ReadableStream>()` does not. 

So your original code has two problems:
1) `Arb.register` was not in fact being called because it was in the static init of a module.
2) Even if it is called, it is registering a generator for `Stream` and so only `Arb.generate<Stream>()` works, not `Arb.generate<ReadableStream>()`.

**Comment by Eitilt** [comment]
Ah, that's got it. Sorry for the confusion. And I've found what I was trying to do with `ReadableStream` on the Tips and Tricks page, so that's answered that as well. Thanks!
