### ISSUE TITLE
[Minor] Some tests don't have source information

### ISSUE THREAD

**Issue by 0x53A** [fscheck/FsCheck#355]
I just noticed this while testing the other PR:

most tests have a clickable got-to-source link, but some don't.

I can't see any difference between the ones that do, and the ones that don't.

![image](https://cloud.githubusercontent.com/assets/4236651/23482258/b65d6e90-fece-11e6-81a3-db285daa67ee.png)
![image](https://cloud.githubusercontent.com/assets/4236651/23482266/bca24d48-fece-11e6-94b9-dd7d1d3fd46f.png)

![image](https://cloud.githubusercontent.com/assets/4236651/23482304/d1e9d5cc-fece-11e6-9d22-049520ea6bf7.png)

![image](https://cloud.githubusercontent.com/assets/4236651/23482293/cbc5d092-fece-11e6-871f-c2a96cd923b3.png)

**Comment by kurtschelfthout** [comment]
Yeah, there is some weird interaction with xUnit and the VS test runner. Some tests don't show up under the irclass either for example.  I think I've raised this before with the xunit folks and they pointed me to the VS folks etc. So I doubt there is much we can do here.

**Comment by kurtschelfthout** [comment]
Looks like somewhere in the last 3 years this got fixed :)
