### ISSUE TITLE
FsCheck doesn't return larger integers

### ISSUE THREAD

**Issue by helixsync** [fscheck/FsCheck#358]
I have been trying to using the FsCheck library with my C# code and the NUnit however I noticed that the integers chosen never get into the higher numbers. My testing has been limited to this environment so not sure how well this extends elsewhere 

```
        [FsCheck.NUnit.Property]
        public void NumberTest(int val)
        {
            if (val > 5000)
                throw new Exception("This exception is never reached");
            Console.WriteLine(val);
        }
```

**Comment by ploeh** [comment]
Does [this](http://stackoverflow.com/a/40591931/126014) answer your question?

**Comment by helixsync** [comment]
The answer wasn't totally clear but it was enough to get me in the correct direction. The following now works.

        [FsCheck.NUnit.Property(EndSize = int.MaxValue)]
        public void NumberTest(int val)
        {
            if (val > 5000)
                throw new Exception("This exception is never reached");
            Console.WriteLine(val);
        }

**Comment by helixsync** [comment]
I did some more testing with the new option and it appears that by setting the end size to a large number it also causes the 0 case from not happening (or at least happening too infrequently)

        [FsCheck.NUnit.Property(EndSize = 50000, StartSize = 0)]
        public void NumberTest(int val)
        {
            if (val == 0)
                throw new Exception("This exception is never reached");
            Console.WriteLine(val);
        }

I realize that it can't hit every number but it would seem that zero and perhaps some other numbers (1, -1) should appear more frequently as they are often a cause of bugs of which property testing could help expose.

**Comment by kurtschelfthout** [comment]
This is expected. FsCheck gradually increase the size in the course of test run linearly between StartSize and EndSize, but perhaps somewhat counter-intuitively increases the size _before_ the first test. So in your case for 100 tests you get increases of 50000/100 = 500 per test, and the first test runs with a size of 500. This means you have a 1 in 1001 chance of getting a 0. The next one 1 in 2001 and so on.

By default the end size is 100 so the first run has about 1 in 3 chance, then 1 in 5 and so on. 

In any case this means lower absolute values have a much higher chance to be generated than higher values.

FsCheck does not guarantee that a particular value is generated. You can make the odds overwhelming in to that effect, but if you really want to test certain values write a separate test for them.

You can also write a generator for example that, no matter what the size, generates 0 say 1 in 5 times. The trade off is of course that for 100 tests about 20 will effectively be the same test run multiple times.
