### ISSUE TITLE
Trouble with xUnit.net 2.2.0

### ISSUE THREAD

**Issue by ploeh** [fscheck/FsCheck#359]
I can't figure out if I'm doing something wrong, but I'm having trouble getting _FsCheck.Xunit_ working with xUnit.net 2.2.0.

I've created a simple repro code base with a single test module:

```fsharp
module Properties

open FsCheck
open FsCheck.Xunit
open Swensen.Unquote

[<Property>]
let myProperty (NonNegativeInt x) = 0 <=! x

[<Property>]
let myGenProperty () =
    Arb.generate |> Gen.map ((*) 2) |> Arb.fromGen |> Prop.forAll <| fun i ->
        0 =! i % 2
```

With xUnit.net 2.1.0 it works fine:

```
$ packages/xunit.runner.console.2.2.0/tools/xunit.console.exe MyProperty/bin/Debug/MyProperty.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: MyProperty
  Discovered:  MyProperty
  Starting:    MyProperty
  Finished:    MyProperty
=== TEST EXECUTION SUMMARY ===
   MyProperty  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 0,709s
```

While it's working, my NuGet packages are like this:

```
Id                                  Versions
--                                  --------
FsCheck                             {2.7.2} 
FsCheck.Xunit                       {2.7.2} 
Unquote                             {3.1.2} 
xunit.abstractions                  {2.0.0} 
xunit.extensibility.core            {2.1.0} 
xunit.extensibility.execution       {2.1.0} 
xunit.runner.console                {2.2.0}
```

Subsequently, I updated xUnit.net:

```
Id                                  Versions
--                                  --------
FsCheck                             {2.7.2} 
FsCheck.Xunit                       {2.7.2} 
Unquote                             {3.1.2} 
xunit.abstractions                  {2.0.1} 
xunit.extensibility.core            {2.2.0} 
xunit.extensibility.execution       {2.2.0} 
xunit.runner.console                {2.2.0} 
```

Now the tests no longer run:

```
$ packages/xunit.runner.console.2.2.0/tools/xunit.console.exe MyProperty/bin/Debug/MyProperty.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: MyProperty
  Discovered:  MyProperty
=== TEST EXECUTION SUMMARY ===
   MyProperty.dll  Total: 0
```

My `App.config` looks like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="xunit.core" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.3545" newVersion="2.2.0.3545" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Is this a known issue, or am I missing something obvious?

**Comment by kurtschelfthout** [comment]
Someone mentioned the same to me on Twitter before so I think it's the same for everyone. Don't know why though. Does it work if in the FsCheck solution if you upgrade xunit there?

**Comment by ploeh** [comment]
If I upgrade xUnit.net on the FsCheck solution, I can get it to work. It took a little fiddling to get it to compile, but once I was past that, it seems to be working.

Despite much fiddling with my repro, I've yet to figure out why it's not working... I'll have to do more digging, but suggestions are welcome.

**Comment by kurtschelfthout** [comment]
I guess they changed things in a backwards incompatbile way. Perhaps you shouldn't spend too much time on this and we should just release a new version that is compiled with 2.2?

**Comment by ploeh** [comment]
As a general observation, the xUnit.net maintainers know what they're doing, so I'm not entirely convinced of that explanation.

It might be fine to release a new version of _FsCheck.Xunit_ compiled against xUnit.net 2.2, but there's no guarantee that it'll work...

Anyway, if you'd like to do this, I have the updated files on my hard drive, so I can send a pull request. Should I do that?

**Comment by kurtschelfthout** [comment]
>As a general observation, the xUnit.net maintainers know what they're doing, so I'm not entirely convinced of that explanation.

Yes, wasn't accusing anyone of incompetence. Just that this is a bit of a minefield, especially wrt to extensions/plugins.

>Anyway, if you'd like to do this, I have the updated files on my hard drive, so I can send a pull request. Should I do that?

Let's try it. If you send a PR, AppVeyor will produce the FsCheck NuGet packages so installing those into a fresh test project should at least give us some information.

**Comment by ploeh** [comment]
PR sent: https://github.com/fscheck/FsCheck/pull/360

**Comment by kurtschelfthout** [comment]
So I think this is because xunit removed .NET Framework 4.5 support (because MSFT removed support for it). We should do the same.

**Comment by ploeh** [comment]
Possibly... I've tried updating all FsCheck projects to target .NET 4.5.2, and adding those as references in my little investigation project, but that doesn't seem to help...

**Comment by ploeh** [comment]
...but, since I agree that FsCheck should target a supported run-time, and since I still had the changes, I've sent a pull request: https://github.com/fscheck/FsCheck/pull/362

**Comment by kurtschelfthout** [comment]
Hm. Okay, there goes that theory :)

**Comment by ploeh** [comment]
> there goes that theory

Or maybe I fucked up my experiment...

**Comment by kurtschelfthout** [comment]
> Or maybe I fucked up my experiment...

Yeah...independent reproduction is the basis of any scientific endeavour so I'll start with that :)

**Comment by kurtschelfthout** [comment]
I do not have a solution but I do have a number of observations.

1. For C# projects, everything seems to work as normal. I can create a new C# project, install FsCheck.Xunit in it and upgrade xunit to 2.2. and everything works as expected.
2. For F# projects, things don't work with xunit 2.2 and as you say using the FsCheck package that targets net452 doesn't change anything. What's interesting though is that for say the following class, it finds all the tests _before_ the first `Property` (i.e. `X` and `X2`) but not any after that.

So things go wrong in the following case:
1. F# project
2. that uses `PropertyAttribute`
3. with xunit 2.2.

Quite puzzling....

```
namespace XunitTest

open FsCheck
open global.Xunit
open FsCheck.Xunit

type Class1() = 
    [<Fact>]
    member this.X1() = Check.QuickThrowOnFailure(fun i -> i < 100)
    [<Fact>]
    member this.X() = Check.QuickThrowOnFailure(fun i -> i < 100)
    [<Property>]
    member this.Y(i:int) = ()
    [<Fact>]
    member this.Y2() = Check.QuickThrowOnFailure(fun i -> i < 100)
```

**Comment by kurtschelfthout** [comment]
Let's see what #363 does.

Also weird that in the FsCheck solution itself, everything works. All tests are discovered.

**Comment by ploeh** [comment]
FWIW, @bradwilson [suggested](https://twitter.com/bradwilson/status/841701524241707008) bringing this up on the xUnit.net Slack channel... I'm not on Slack, so I'm just leaving this here for anyone else who might read it 😉

**Comment by kurtschelfthout** [comment]
Thanks! I joined the slack channel...will report back here if something comes out of it.

**Comment by kurtschelfthout** [comment]
So something did come out. I can make it work with FsCheck.Xunit 2.7.2 if I add binding redirects as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="xunit.core" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.3545" newVersion="2.2.0.3545" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="xunit.execution.desktop" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.3545" newVersion="2.2.0.3545" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

C# adds these automatically if you install xunit 2.2 in the project, which explains why it worked.

Makes sense too: FsCheck.Xunit.dll refers to xunit.core 2.1.0 but by upgrading that dll is not referenced anymore.

This is all a bit annoying because adding binding redirects doesn't work automatically in F#. Then again hopefully most people in F# are using paket, which I believe does take care of this.

Another thing to consider is that if I re-compile FsCheck.Xunit with xunit.core 2.2, as is the situation currently on master, I can't get it to work with xunit 2.1 anymore, even with binding redirects.

I'm not sure what's best: 
- work out of the box with the latest version of xunit, and don't work at all with xunit 2.1, or 
- work by default with the old version and need a binding redirect (likely this will confuse many people) to work with xunit 2.2.

**Comment by bradwilson** [comment]
Well, I don't get a vote, but my choice is:

> * work out of the box with the latest version of xunit, and don't work at all with xunit 2.1

It's reasonable to update your dependencies as you ship new versions. That said, you should probably document the binding redirect thing somewhere. 😉

**Comment by ploeh** [comment]
It works! It surprises me that redirection of `xunit.execution.desktop` is necessary, even when running the command-line runner, but it seems to work...

Thank you, @kurtschelfthout and @bradwilson, for your help 👍

**Comment by kurtschelfthout** [comment]
> Well, I don't get a vote, but my choice is:

@bradwilson You earned your vote! Also happy to count it because that was what I wanted to do all along, but @ploeh kept me honest so now we know the reason why ;)

Thought this kind of issue is best documented as a wiki: https://github.com/fscheck/FsCheck/wiki/How-to-get-F%23-projects-that-use-FsCheck.Xunit--=2.7.2-to-work-with-xunit-2.2 Kind of an experiment...
