### ISSUE TITLE
Docs - Translation to spanish

### ISSUE THREAD

**Issue by Andrea** [fscheck/FsCheck#36]
Hi there

As I mentioned in commit a9575a54525c036ee9d0c246c46e9e3c6ee48ab3 I have started a translation of the docs to spanish. 
I am a little confused about the FSharp.Formating usage,  I had a look at docs/content and I only see the English version in the fsx files, and the japanese at the root of /docs. So basically I have not idea where to put the spanish files :D 
Also I assume that I should create files with formatting similar to the fsx files inside /docs/content right?

Cheers

**Comment by kurtschelfthout** [comment]
Spring cleaning issues, I'm guessing this is not really happening anymore :) Feel free to open a PR of course if it is.
