### ISSUE TITLE
Applying MaxFail Property param with FsCheck.Xunit and C#

### ISSUE THREAD

**Issue by ayb4btu** [fscheck/FsCheck#373]
This is more of a question than an issue as I'm probably using it incorrectly, but how should the MaxFail param for the Property attribute be applied when using C# and FsCheck.Xunit.

I've tried the following, but the default 100 tests are still run, when I would have thought that the tests would stop running after the fifth return:

```C#
    [Property(MaxFail = 5)]
    public void MaxFailTest(int one)
    {
        if (one < 0)
        {
            System.Diagnostics.Debug.WriteLine($"{one} is below 0");
            return;
        }

        Assert.Equal(one, one);
    }
```
Or is the MaxFail param only implemented for the ==> operator in F#?

**Comment by ploeh** [comment]
The `MaxFail` number indicates how many attempts to try before giving up. I don't know if it applies in _other_ cases than when using `==>`, but it definitely can be useful there.

If you want to change the default number of times a property runs, you can use the `MaxTest` property.

HTH

**Comment by ayb4btu** [comment]
I'm learning how to use FsCheck with C# (rather than F#, which I believe is what it was designed for), and as part of this I'm trying the different `Property` attribute params to see how they work.

As far as I'm aware, there isn't an equivalent F# `==>` operator in C#, so I'm _guessing_ `MaxFail` is unusable with C# tests? (I was hoping that simply `return`ing without an `Assert` might be equivalent.)

If `MaxFail` isn't usable with C#, I guess if there is a number of tests needing to be skipped when using default generators, then I should look at creating custom generators? Or, as you suggested, increase `MaxTest` sufficiently to cover the number of values that could be rejected.

**Comment by kurtschelfthout** [comment]
> As far as I'm aware, there isn't an equivalent F# ==> operator in C#, so I'm guessing MaxFail is unusable with C# tests? (I was hoping that simply returning without an Assert might be equivalent.)

Use `When`, [example](https://fscheck.github.io/FsCheck/Properties.html#Conditional-Properties).

As @ploeh explained, `MaxFail` is only applicable to conditional properties using `==>` and `When`.

**Comment by ayb4btu** [comment]
I can run `Prop.ForAll....QuickCheck();` style test, but that runs the test internal and separate to the 
Xunit method test, the following would run 100 times, with `Prop.ForAll` run 100 times for each run:

```C#
    [Property]
    public void SomeTest()
    {
        Prop.ForAll<int, int>((x, y) => (x == y).When(x > 0));
    }
```

How would `When` be used with the Xunit examples presented in [FsCheck.XUnit.CSharpExamples/ReverseFixture.cs](https://github.com/fscheck/FsCheck/blob/master/examples/FsCheck.XUnit.CSharpExamples/ReverseFixture.cs) if it can be?

**Comment by kurtschelfthout** [comment]
> the following would run 100 times, with Prop.ForAll run 100 times for each run:

No it doesn't, it just runs 100 tests. It'll basically be interpreted as a parametrized test that takes `(unit, int, int)` and so in addition generates 100 "random" `unit` values, but that shouldn't get in the way.

You want to return the property though, as written it doesn't even run your test:

[Property]
    public Property SomeTest()
    {
        return Prop.ForAll<int, int>((x, y) => (x == y).When(x > 0));
    }

**Comment by ayb4btu** [comment]
Thanks, your example is helping clear things up, I didn't realise `Property` objects could be returned. I was trying to treat these like value tests, where results are Asserted.

For FsCheck (when not using `MaxFail`) which of these approaches is generally deemed better (and if so, why), or is it subjective:

        [Property(MaxTest = 5)]
        public bool MaxTestParam_ReturnBool(int one)
        {
            return one == one;
        }

        [Property(MaxTest = 5)]
        public void MaxTestParam_XunitAssert(int one)
        {
            Assert.Equal(one, one);
        }

        [Property(MaxTest = 5)]
        public Property MaxTestParam_InputVariable_ReturnProperty(int one)
        {
            var result = one == one;

            return result.ToProperty();
        }

        [Property(MaxTest = 5)]
        public Property MaxTestParam_PropForAll_ReturnProperty()
        {
            return Prop.ForAll<int>(one => one == one);
        }

**Comment by ploeh** [comment]
From those alternatives, I'd use `MaxTestParam_XunitAssert`.

`MaxTestParam_ReturnBool` works, but you don't get much feedback if the property fails.

`MaxTestParam_InputVariable_ReturnProperty` also works, but why make things more complicated than they have to be? The same could be said for `MaxTestParam_PropForAll_ReturnProperty`.

**Comment by ayb4btu** [comment]
Thanks, that's given me a lot more insight into how FsCheck operates.
