### ISSUE TITLE
missing pdb for netstandard1.6

### ISSUE THREAD

**Issue by ctaggart** [fscheck/FsCheck#379]
The netstandard1.6 folder should have the pdb & xml files as well. I noticed this while working on #378.

```
C:\Users\camer\Downloads\FsCheck.2.9.0> tree /f
Folder PATH listing
Volume serial number is 00000098 8E63:C73D
C:.
│   FsCheck.2.9.0.nupkg
│
└───lib
    ├───net452
    │       FsCheck.dll
    │       FsCheck.pdb
    │       FsCheck.xml
    │
    ├───netstandard1.6
    │       FsCheck.dll
    │
    ├───portable-net45+netcore45
    │       FsCheck.dll
    │       FsCheck.pdb
    │       FsCheck.XML
    │
    ├───portable-net45+netcore45+wp8
    │       FsCheck.dll
    │       FsCheck.pdb
    │       FsCheck.XML
    │
    └───portable-net45+netcore45+wpa81+wp8
            FsCheck.dll
            FsCheck.pdb
            FsCheck.XML
```

**Comment by kurtschelfthout** [comment]
Yeah, I kind of knew about this. I looked at it at some point, and gave up.

- The xml is not produced by the F# compiler, for reasons that are not clear to me. That is, in the output folder of FsCheck.netcore.fsproj there is no FsCheck.xml file.
- The pdb file is produced by the compiler, but is not packaged in the (intermediate) netcore-only NuGet package. This just uses `dotnet pack` so not sure what is going on there. So it also doesn't get merged into the final NuGet package.

**Comment by kurtschelfthout** [comment]
Closing this - currently not using source link anymore due to likely F# compiler bugs wrt debugging with portable pdbs. Waiting until some dust settles.
