### ISSUE TITLE
Test "parallelTest works with custom arb" fails with Stackoverflow

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#387]
Possibly has something to do with new size mechanism and Gen.piles introduced after merge from master to fscheck3.

**Comment by Rattenkrieg** [comment]
Which one fails? I got everything green after rebase.

**Comment by kurtschelfthout** [comment]
Think it only happens with release build. Run the build script to see.

**Comment by Rattenkrieg** [comment]
I've found failing one - `parallelTest works with custom arb`
I tend to think SO is related to custom arbitrary rather than parallelism. I've expierenced similar issue (in sequntial tests) with custom arbitrary for predefined types like ints, strings. Will investigate soon.

**Comment by kurtschelfthout** [comment]
Yeah, got a stack trace at some point. Lots of Gen.map closures. Could be it's reproducible just by generating a long list or something. 

I only get it when running with the console runner though, which is weird.
