### ISSUE TITLE
Defining single-case DU arbitrary using Arb.convert causes infinite loop when shrinking

### ISSUE THREAD

**Issue by cmeeren** [fscheck/FsCheck#392]
Consider the following type:

```f#
/// A string that can have any value, but is never null
type NonNullString = NonNullString of string with
    static member op_Explicit(NonNullString s) = s
```

When defined in the following way, a failing test never completes due to (I assume) some shrinking problem:

```f#
type ArbitraryAdditions =
    static member NonNullString() =
        Arb.from<string>
        |> Arb.filter (fun s -> not (isNull s))
        |> Arb.convert NonNullString string
```

If I instead define it using Arb.fromGen, it works (but never shrinks):

```f#
type ArbitraryAdditions =
    static member NonNullString() =
        Arb.generate<string>
        |> Gen.filter (fun s -> not (isNull s))
        |> Gen.map NonNullString
        |> Arb.fromGen
```

And if I create a shrinker, it of course also works:

```f#
type ArbitraryAdditions =
    static member NonNullString() =
        let shrinker (NonNullString s) = 
            Arb.shrink<string> s
            |> Seq.filter (fun s -> not (isNull s))
            |> Seq.map NonNullString
        let gen = 
            Arb.generate<string>
            |> Gen.filter (fun s -> not (isNull s))
            |> Gen.map NonNullString
        Arb.fromGenShrink (gen, shrinker)
```

Is it expected behavior to get an infinite loop when creating an arbitrary using the first method?

**Comment by cmeeren** [comment]
Oh, wait, my mistake - I literally thought of it the moment I posted. Here's the correct implementation à la method 1:

```f#
static member NonNullString() =
    Arb.from<string>
    |> Arb.filter (fun s -> not (isNull s))
    |> Arb.convert NonNullString (fun (NonNullString s) -> s) // Here's the difference
```

If I have understood correctly, this is because `string` calls `ToString` on an object, it doesn't convert something to a string (in this case using `op_Explicit`), contrary to the `EvenInt` example [in the docs](https://fscheck.github.io/FsCheck/TipsAndTricks.html#Use-pattern-matching-instead-of-forAll-to-use-custom-generators) (which I had carelessly adapted).

**Comment by cmeeren** [comment]
One more question: Using the corrected implementation above, is it still guaranteed that shrinks will not produce nulls?

**Comment by kurtschelfthout** [comment]
> One more question: Using the corrected implementation above, is it still guaranteed that shrinks of NonNullString will not produce nulls? I.e., are the shrunk values passed through the pipeline (here, the filter) before being used?

Yes and yes.
