### ISSUE TITLE
Show unprintable characters as byte codes?

### ISSUE THREAD

**Issue by cmeeren** [fscheck/FsCheck#393]
I was experimenting with creating new Arbitrary types and made a quick one for `NonEmptyString` just to check my understanding.

I wanted to test shrinking, so I created a failing test and was surprised to see this in the console (nevermind that it says `NonNullString` instead of `NonEmptyString`, that's irrelevant):

![emptystring](https://user-images.githubusercontent.com/7766733/30496006-6a1c3130-9a4e-11e7-806c-f11501c3092a.png)

What? But I definitely excluded empty strings using `Arb.filter (fun s -> s <> "")`!

I was about to make a bug report but needed to experiment some more first, so I copied the output temporarily into Notepad++. And lo and behold, an Unprintable Character™ appeared out of nowhere (as they are wont to do):

![notepad](https://user-images.githubusercontent.com/7766733/30496005-6a1ab9b8-9a4e-11e7-8f67-8995d7df611b.png)

I'd say "the plot thickens", but that's the grand finale, really.

I notice that often, generated strings contain "characters" starting with backslash `\` (not sure what the correct term is - byte codes? code points?). Would it be possible to show unprintable characters in this manner too, so users don't mistake them for empty strings and end up on a wild goose chase?

**Comment by kurtschelfthout** [comment]
> Would it be possible to show unprintable characters in this manner too, 
Not that I know of. We just call `printf` on the generated objects.

**Comment by kurtschelfthout** [comment]
Ok, I guess we could add a special case for strings in the output so that special characters are mapped first. Do you know of some list of unprintable characters?

**Comment by cmeeren** [comment]
Just google it? https://www.juniper.net/documentation/en_US/idp5.1/topics/reference/general/intrusion-detection-prevention-custom-attack-object-extended-ascii.html

**Comment by kurtschelfthout** [comment]
There is apparently a `Char.IsControl`.
