### ISSUE TITLE
Using from C#

### ISSUE THREAD

**Issue by ArtGangsta** [fscheck/FsCheck#399]
It seems that it is mandatory to understand F# in order to us FsCheck with C#.

Is that true?

If not, is there any documentation on how to use this for C# programmers who have no knowledge of F#?

I would like to recommend this tool to a large corporation with hundreds of developers.   I don't feel that I can do that without understanding the F# knowledge requirement for FsCheck.

Thank you.

**Comment by Rattenkrieg** [comment]
Lot of examples in docs are written in both F# and C#. [Here](https://fscheck.github.io/FsCheck/QuickStart.html) is good place to start. You may found contents of [examples directory](https://github.com/fscheck/FsCheck/tree/master/examples) useful for demonstration to your colleagues.

**Comment by Rattenkrieg** [comment]
Crafting complex _Arbitraties_ is one thing that may appear easier to implement in F#. Though it also doable in C#, you have to deal with abusing LINQ or writing deeply nested code.

**Comment by Aaronontheweb** [comment]
@ArtGangsta I wrote some blog posts explaining how we use the C# FsCheck APIs in production here: http://www.aaronstannard.com/fscheck-property-testing-csharp-part2/

**Comment by kurtschelfthout** [comment]
I don't see how anyone can answer that question for you. This is an open source project and all the documentation is available as is, as well as a bunch of other info in blog posts, papers etc. Clearly the thing is written in F# so if you want to contribute core code then that's going to be in F#. Examples and docs are both F# and C# - there are likely a few places in the doc where the C# doc can be enhanced, in particular in the reference documentation - but FsCheck has a C# API with (afaik) the same functionality as the F# API.

**Comment by ArtGangsta** [comment]
Rattenkrieg and Aaronontheweb, thank you so much.  That helps a lot!

thanks kurt  -- sorry to make it seem like my question is unanswerable.  I'm trying to see if it's possible to use Fscheck in an environment where developers are not required to use or learn F#, or even have it installed.   I can see now that it's doable.
