### ISSUE TITLE
Task-async Tests Cannot Fail

### ISSUE THREAD

**Issue by chrisoverzero** [fscheck/FsCheck#406]
Sorry, this is all going to be in C# – my F# is not so good.

**Version** FsCheck v3.0.0-alpha1
**Related** FsCheck.Xunit v3.0.0-alpha1, xunit.core 2.3.0

Given the following xUnit.net test case:

```csharp
/// <summary>An example of the failure of async tests.</summary>
[Properties(QuietOnSuccess = true)]
public static class ExampleFixture
{
    [Property(DisplayName = "Irrespective of the exception thrown, the test passes.")]
    static async Task FailMe()
    {
        await Task.CompletedTask;
        Assert.False(true);
    }
}
```

...I'd expect it to fail. However, this test passes.

It looks like the issue is in [Testable][], testing for the success of a `Task`. I *think* that in `ContinueWith`, the `IsCompleted` property of a `Task` will always be `true`. What to check in order to know whether a `Task` has thrown is the `IsFaulted` property.

In LINQPad:

```csharp
await Task.FromException(new Exception("wow")).ContinueWith(t =>
{
  t.IsCompleted.Dump(); // True
  t.IsFaulted.Dump(); // True
  t.Exception.Dump(); // an aggregate exception
});

await Task.CompletedTask.ContinueWith(t =>
{
  t.IsCompleted.Dump(); // True
  t.IsFaulted.Dump(); // False
  t.Exception.Dump(); // null
});
```

[Testable]: https://github.com/fscheck/FsCheck/blob/ce793a4eedf3f1af4776345048341e1369ae8613/src/FsCheck/Testable.fs#L147-L149

**Comment by Rattenkrieg** [comment]
Thanks for trying out alpha build!

> It looks like the issue is in Testable, testing for the success of a Task. I think that in ContinueWith, the IsCompleted property of a Task will always be true. What to check in order to know whether a Task has thrown is the IsFaulted property.

Seems thats the issue. I will investigate it on weekends.
You can do it [this way](https://github.com/fscheck/FsCheck/blob/fscheck3/examples/FsCheck.XUnit.CSharpExamples/ReverseFixture.cs#L16-L21) for now.

**Comment by chrisoverzero** [comment]
I have a PR ready to go for this, if you're interested.

**Comment by Rattenkrieg** [comment]
Awesome, go ahead!

**Comment by kurtschelfthout** [comment]
Fix released in alpha2. Thanks!
