### ISSUE TITLE
Installing NuGet package on net461 framework installs superfluous dependencies

### ISSUE THREAD

**Issue by hickford** [fscheck/FsCheck#410]
Installing FsCheck with nuget.exe for .NET Framework 4.6.1 installs a bunch of extra packages that aren't required, in particular NETStandard.Library:

    > nuget install FsCheck -Framework net461
    ...
    Retrieving package 'FsCheck 2.10.3' from 'nuget.org'.
    Retrieving package 'FSharp.Core 4.1.18' from 'nuget.org'.
    Retrieving package 'Microsoft.NETCore.Platforms 1.1.0' from 'nuget.org'.
    Retrieving package 'Microsoft.Win32.Primitives 4.3.0' from 'nuget.org'.
    Retrieving package 'NETStandard.Library 1.6.1' from 'nuget.org'.
    Retrieving package 'System.AppContext 4.3.0' from 'nuget.org'.
    ... [~20 more packages]
    Executing nuget actions took 41.31 sec

This doesn't happen on net46 framework.

    > nuget install FsCheck -Framework net46
    ...
    Retrieving package 'FsCheck 2.10.3' from 'nuget.org'.
    Retrieving package 'FSharp.Core 4.1.17' from 'nuget.org'.
    Retrieving package 'System.ValueTuple 4.3.0' from 'nuget.org'.
    ...
    Executing nuget actions took 1.66 sec

**Comment by hickford** [comment]
This is the same problem as https://github.com/Microsoft/visualfsharp/issues/3451 for FSharp.Core , for which the solution was https://github.com/Microsoft/visualfsharp/pull/3452 "Basically FSharp.Core needs an empty dependency group for net45."

**Comment by hickford** [comment]
As I understand, it would suffice to edit `FsCheck.nuspec`

    <dependencies>
      <group>
        <dependency id="FSharp.Core" version="4.1.0"></dependency>
      </group>
      <group targetFramework=".NETStandard1.6">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers"></dependency>
        <dependency id="FSharp.Core" version="4.1.18" exclude="Build,Analyzers"></dependency>
      </group>
    </dependencies>

Adding an extra group

      <group targetFramework="net45">
        <dependency id="FSharp.Core" version="4.1.0"></dependency>
      </group>

**Comment by kurtschelfthout** [comment]
Hm, okay. Not sure how to do that in the paket.tempate file though.

**Comment by hickford** [comment]
So FsCheck.nuspec is generated from https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/paket.template

**Comment by kurtschelfthout** [comment]
That's right. `Paket pack` is used for creating the nuget package.

**Comment by kurtschelfthout** [comment]
I can do that, see #411.

**Comment by kurtschelfthout** [comment]
Doesn't work though. Why does it download them? Why only 4.6.1?

**Comment by hickford** [comment]
I can explain the behaviour of NuGet. NuGet chooses between the dependency groups in the nuspec according to the target framework. Here the groups are .NET Standard 1.6 and Framework.Any (the unlabelled group). NuGet considers .NET Framework 4.6 closest to Framework.Any, however .NET Framework 4.6.1 is considered closer to .NET Standard 1.6 because [".NET Framework 4.6.1 implements .NET Standard 1.6"](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). Adding a dependency group for .NET Framework 4.6.1 (or lower) would solve the problem.

**Comment by kurtschelfthout** [comment]
> Adding a dependency group in the nuspec for .NET Framework 4.6.1 (or lower) would solve the problem.

It doesn't though. Try to install 2.10.5-b944 or b945 from the Appveyor feed. It still adds the dependencies and the nuspec is as you said.

**Comment by kurtschelfthout** [comment]
Wait, maybe it does. To be clear it still adds things like System.Xml but it shouldn't add Net Standard 1.6.1 package?

**Comment by hickford** [comment]
Thanks, let me test. 

Aha. Be careful to append `-DependencyVersion HighestPatch` to the install command to avoid running into https://github.com/Microsoft/visualfsharp/issues/3451

After doing that, any of b944 b945 b946 solves the problem for me.

    C:\Users\hats\Downloads>nuget install -Framework net461 -Source C:\Users\hats\Downloads;https://api.nuget.org/v3/index.json -Prerelease fscheck -Version 2.10.4-b944  -DependencyVersion HighestPatch
    Feeds used:
      C:\Users\hats\.nuget\packages\
      C:\Users\hats\Downloads\nupkgs
      https://api.nuget.org/v3/index.json



        Attempting to gather dependency information for package 'fscheck.2.10.4-b944' with respect to project 'x\packages', targeting '.NETFramework,Version=v4.6.1'
        Gathering dependency information took 2.18 sec
        Attempting to resolve dependencies for package 'fscheck.2.10.4-b944' with DependencyBehavior 'HighestPatch'
        Resolving dependency information took 0 ms
        Resolving actions to install package 'fscheck.2.10.4-b944'
        Resolved actions to install package 'fscheck.2.10.4-b944'
        Retrieving package 'FsCheck 2.10.4-b944' from 'C:\Users\hats\Downloads\nupkgs'.
        Retrieving package 'FSharp.Core 4.1.18' from 'C:\Users\hats\.nuget\packages\'.
        Adding package 'FSharp.Core.4.1.18' to folder 'C:\Users\hats\Downloads\x\packages'
        Added package 'FSharp.Core.4.1.18' to folder 'C:\Users\hats\Downloads\x\packages'
        Successfully installed 'FSharp.Core 4.1.18' to x\packages
        Adding package 'FsCheck.2.10.4-b944' to folder 'C:\Users\hats\Downloads\x\packages'
        Added package 'FsCheck.2.10.4-b944' to folder 'C:\Users\hats\Downloads\x\packages'
        Successfully installed 'FsCheck 2.10.4-b944' to x\packages
        Executing nuget actions took 477.17 ms

**Comment by hickford** [comment]
Brilliant, thank you. Please let me know when you make a release with this fix.

**Comment by kurtschelfthout** [comment]
Done in 2.10.4.
