### ISSUE TITLE
Consider relaxing FSharp.Core constraint for net452 in FsCheck 3

### ISSUE THREAD

**Issue by eiriktsarpalis** [fscheck/FsCheck#418]
Hi, I've recently switched to using FsCheck 3, and I've been enjoying its performance improvements immensely. However, I've noticed that the nuget package requires FSharp.Core >= 4.1 even for the net452 target. I think this might create implications for people consuming the library using old tooling like VS2013 or VS2015. Is the choice to require 4.1 deliberate or an artifact of tooling?

**Comment by kurtschelfthout** [comment]
I was following some guidance on the fsharp.core 4.2 package. In fact I was thinking to target >= 4.2. I think there are some packaging shenanigans with earlier versions that cause dependencies to be downloaded when they don't need to. It is all big mess on the packaging front and I'd love to get out of that business entirely tbh, but I also don't want to cause issues for users, so thanks for raising this. What implications do you suspect?

**Comment by eiriktsarpalis** [comment]
Spent some time, but I think I was able to solve packaging in [Argu](https://www.nuget.org/packages/Argu/4.1.0)

Without concrete evidence, I have experienced issues when building newer F# runtime projects with older versions of tooling. I'm assuming there will also be issues when referencing FsCheck with older builds of fsi. The bottom line is that we avoid upgrading to, say, F# 4.0 when some team members are editing that codebase using VS2013.

**Comment by kurtschelfthout** [comment]
I see - I didn't realize you were thinking that far back. I don't currently envision back-porting to support FSharp.Core < v4.0. The last version of FsCheck that supported 3.1 is v2.8.2 (which is not that old). 

I really don't like the idea of breaking users, but it boils down to protecting my time really, and spending it on things I enjoy. (Either way I feel like I cannot win. When I used to target older FSharp.Core versions, people complained about version redirects all the time. Though maybe tooling around that has improved now.)

**Comment by eiriktsarpalis** [comment]
I think requiring 4.0 is reasonable at this stage.

**Comment by kurtschelfthout** [comment]
That is also more doable I think, let me check the impact.

**Comment by kurtschelfthout** [comment]
Released `FSharp.Core >= 4.0` constraint for desktop in 2.10.6 and 3.0.0-alpha3.
