### ISSUE TITLE
Consider constraining Nunit dependency in FsCheck.Nunit to major number

### ISSUE THREAD

**Issue by eiriktsarpalis** [fscheck/FsCheck#419]
[Current releases of FsCheck.NUnit](https://www.nuget.org/packages/FsCheck.Nunit/) are constraining to the minor number of NUnit (in this case 3.8 <= x < 3.9). Would it be possible to relax this to a major version constraint (i.e 3 <= x < 4.0)?

**Comment by kurtschelfthout** [comment]
It was like that at some point but NUnit broke the extension API a couple too many times on minor version number increases. I'd be happier to release FsCheck to upgrade to latest NUnit version instead, would that help?

**Comment by eiriktsarpalis** [comment]
Sure, but it seems that it certainly adds pressure on you the author to release on every minor upgrade of NUnit. We can override regardless, but what if you optimistically assume SemVer and let users roll back when it's not the case?

**Comment by kurtschelfthout** [comment]
I think it will amount to the same amount of annoyance  ;)

I added >= 3.8.1 because I know the current FsCheck.NUnit doesn't work with versions before that.
