### ISSUE TITLE
Configuring maximum number of tests has no effect in .NET Core

### ISSUE THREAD

**Issue by crow-ua** [fscheck/FsCheck#420]
Here's  test pasted from https://fscheck.github.io/FsCheck/RunningTests.html
```
[Property]
public void Test()
{
	var configuration = Configuration.Quick;
	configuration.MaxNbOfTest = 1000;
	configuration.QuietOnSuccess = true;
	true.ToProperty().Check(configuration);	
}
```
I'm changing the number assigned to MaxNbOfTest and the flag to true/false, but the test runner always displays `Ok, passed 100 tests`.
The application is targeting .NET Core 2.0:
```
<TargetFramework>netcoreapp2.0</TargetFramework>
//..
<PackageReference Include="xunit" Version="2.3.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
<PackageReference Include="FsCheck" Version="2.10.6" />
<PackageReference Include="FsCheck.Xunit" Version="2.10.6" />
```
I was thinking runner itself has something to do with this, but both Resharper and Visual Studio Test Runner in my VS2017 provide same output.

**Comment by ploeh** [comment]
IIRC, the test must return the `Property`:

```csharp
[Property]
public Property Test()
{
	var configuration = Configuration.Quick;
	configuration.MaxNbOfTest = 1000;
	configuration.QuietOnSuccess = true;
	return true.ToProperty().Check(configuration);	
}
```

If so, I don't think it has anything to do with .NET Core, but I could be wrong...

**Comment by crow-ua** [comment]
Doesn't look like it, `Check` is of type void.

**Comment by ploeh** [comment]
I don't think that snippet is supposed to be executed from within a `[Property]`... Try running those four lines of code in a console app; I'd expect it to print out an error message.

**Comment by ploeh** [comment]
In a unit test, you either need `QuickCheckThrowOnFailure` as described in https://fscheck.github.io/FsCheck/RunningTests.html, or, if you're using _FsCheck.XUnit_, you must return the `Property`.

**Comment by kurtschelfthout** [comment]
Like @ploeh said - that snippet is under the heading "Running a single property from an fsx/csx file or a command line runner". What is happening is that you are running 100 times 1000 tests. The test method is interpreted as an Fscheck test with default config (there are properties on the `PropertyAttribute` to change these). Then, the inner test is `true.ToProperty().Check` which is executed 1000 times but doesn't print anything on exit as per your config.

See here for xUnit.net examples: https://fscheck.github.io/FsCheck/RunningTests.html#Using-FsCheck-Xunit

**Comment by crow-ua** [comment]
> In a unit test, you either need QuickCheckThrowOnFailure
I'm already doing that in other tests, but it doesn't have an overload accepting configuration.
> [Property(QuietOnSuccess = true, MaxNbOfTests=1000)]
Attribute property is named differently, but this way it indeed works.
`[Property(QuietOnSuccess = false, MaxTest = 1000)]`
Thanks for help.
