### ISSUE TITLE
Harmonize Config/Configuration/PropertyAttribute

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#421]
As noted in #420 we have about a handful of configuration types that have slightly different property names.

As much as possible we should limit the number of different configuration types. At least make all the names the same to avoid confusion.

Also, the basic `Config` type https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Runner.fs#L39 should become a POCO mutable type - that means we can probably get rid of a few wrappers. And also, F# record types in a public API are basically a big no-no, as they can't be changed without breaking compatibility.

This should happen on the fscheck3 branch, and where possible add/deprecate in v2.

**Comment by ploeh** [comment]
Why do you want to make it mutable?

**Comment by kurtschelfthout** [comment]
> Why do you want to make it mutable?

So we can have just one `Configuration` type that is conveniently usable from both F# and C#.

**Comment by ploeh** [comment]
It doesn't have to be mutable in order to be usable from C#...

**Comment by kurtschelfthout** [comment]
_conveniently_ usable ;) from both langs and easily extensible. I guess you're referring to using optional parameters but that gets unwieldy pretty quickly I think.

**Comment by ploeh** [comment]
No, I wasn't thinking of optional parameters. What you can do in C#, and how I'd design C# APIs even in the absence of F#, would be something like a Fluent Builder API that would enable people to write something like:

```csharp
Configuration.Default.WithMaxTest(1000);
```

The problem with using F# records for public APIs has nothing to do with immutability, but that you can't add constructor overloads with default values. One can address that, however, by not exporting the internal structure of the record:

```fsharp
type Config = private Config of (maxTest : int, maxFail : int (* ... *))
```

(It's possible that I got the details of the syntax wrong; I haven't tried to compile that snippet...

**Comment by kurtschelfthout** [comment]
Yes, hadn't considered that - fluent builder will work. 

The problem I have with record types is that they can't be changed without breaking backwards compatibility, specifically breaking the constructor. There have been various proposals to F# to address that, but they've been consistently rejected.

Afaik you can't make a public record type with a private constructor. 

They are also annoying to use from C#. 

Going forward I want all record types removed from the public API and am banning record types from appearing in the public API.

We can still use record types for the internals if useful.

**Comment by ploeh** [comment]
> Afaik you can't make a public record type with a private constructor.

IIRC, you're right. One can, however, hide them in single-case DUs.

**Comment by LaurenceJKing** [comment]
Hi, I was just taking a look at this issue, to see if I could sort it out. I have a question about Replay value.

`//in RunnerExtensions.fs
member __.Replay 
        with get() = (match replay with None -> Unchecked.defaultof<uint64*uint64*int> | Some s -> (s.Rnd.Seed,s.Rnd.Gamma,defaultArg s.Size 0))
        and set(v) = replay <- Some <| let s,g,size = v in { Rnd = Random.createWithSeedAndGamma (s,g); Size = if size = -1 then None else Some size }`

When we get the Reply property, we get 0 if Size is none. But when we set the Replay property, Size is only set to none if the value is -1. 

Is there any particular reason for this?

**Comment by kurtschelfthout** [comment]
> Is there any particular reason for this?
Not something that I can remember off the top of my head...looks like a bug or at least an inconsistency. There are a few tests that check replay. Might be useful to add to those if something is not covered, change it and see what happens.

**Comment by LaurenceJKing** [comment]
Another question, while I'm at it:
There are a few config values which don't play very nicely with C# (things like the Replay option or the Every function).

How would you propose handling that?

- I could keep using the F# types (which seems preferable from a maintenance perspective, but which could be frustrating for C# users who want to read config values)

or

- I could use C# types (e.g. Func, rather than fun), but that makes life harder for F# users (including ourselves)

**Comment by kurtschelfthout** [comment]
Those are already wrapped in C# friendly types in the `Configuration` type for C# afaik, eg: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/RunnerExtensions.fs#L56

Or did I misunderstand your question?

**Comment by LaurenceJKing** [comment]
Maybe I am misunderstanding the task then:
I thought the the aim was to create a fluent builder for the Config type (Runner.fs) which would enable it to be used from both C# and F# (thus eliminating the need for the Configuration class in RunnerExtensions.fs)

e.g:
`type Config = private Config of 
                         {| MaxTest: int ... Every: int -> list<obj> -> string |} with
                         member this.WithMaxTest maxTest = //set MaxTest here
                         member this.WithEvery(every: int -> list<obj> -> string ) = //set Every here
                         member this.WithEvery(every: Func<int, obj array, string>) = this.WithEvery(fun i os -> every.Invoke(i, List.toArray os)) //C# can now use Config.Default.WithEvery                        
`

**Comment by kurtschelfthout** [comment]
Making one type is one way to approach this, yes. Maybe you can use overloads with both `FSharpFunc` and `Func`, or use the trick elsewhere of making the "core" type F# friendly and then having C# friendly extension methods on it (see e.g. `Arbitrary` and `ArbitraryExtensions` etc). In any case I don't want to choose one over the other, there is normally a way (typically overloading and using attributes to hide methods from intellisense in one language but not the other etc) to present a nice interface to both languages.
