### ISSUE TITLE
No detailed feedback from failing NUnit tests using PropertyAttribute

### ISSUE THREAD

**Issue by adj123** [fscheck/FsCheck#423]
I've found when using FsCheck from NUnit, I don't get any feedback from failing tests about the input which triggered them in the ReSharper test runner:

![image](https://user-images.githubusercontent.com/5223665/35188708-50724b3a-fe11-11e7-9a85-0b55b65aa66e.png)

I also get the same behaviour in NCrunch and the 'VS for Mac' inbuilt unit test runner. I'm using FsCheck[.NUnit] 2.6.10 and NUnit 3.9.0. While I do love FsCheck as a tool, this issue does render the tests unfortunately somewhat useless when calling them this way. The problem appears to be resolved when I alter this part of `FsCheckTestMethod.RunTestMethod`:

```
        | TestResult.Exhausted _ ->
            let msg = sprintf "Exhausted: %s" (Runner.onFinishedToString "" testRunner.Result)
            testResult.SetResult(new ResultState(TestStatus.Failed, msg))
        | TestResult.False (testdata, originalArgs, shrunkArgs, Outcome.Exception e, seed)  ->
            let msg = sprintf "%s" (Runner.onFailureToString "" testdata originalArgs shrunkArgs seed)
            testResult.SetResult(new ResultState(TestStatus.Failed, msg))
        | TestResult.False (testdata, originalArgs, shrunkArgs, outcome, seed) ->
            let msg = sprintf "%s" (Runner.onFinishedToString "" testRunner.Result)
            testResult.SetResult(new ResultState(TestStatus.Failed, msg))
```

to also pass the `msg` into `SetResult`, as well as the `ResultState` constructor. I'm a bit surprised that I might be the first one to discover a genuine issue like this given how it would presumably be fairly major for NUnit users so if this is just user error and I'm doing something wrong, please let me know! Else shall I submit a PR?

Thanks

**Comment by kurtschelfthout** [comment]
Don't think the NUnit runner is that much used. Also wouldn't be totally surprised if this used to work with older versions of NUnit. Either way, please do submit a PR, thanks!

**Comment by adj123** [comment]
Ok great I hoped it would just be something like that - will do.
