### ISSUE TITLE
Property functions

### ISSUE THREAD

**Issue by stijnmoreels** [fscheck/FsCheck#428]
Hi,
For testing properties, I usually use some "helper"/property-functions to extract some common logic.
I've wrapped some common functions in a separate repository: [FsCheck.Extras](https://github.com/stijnmoreels/FsCheck.Extras) but I don't know if this is useful to add to the **FsCheck** repository instead?

Thanks in advance!

Greetings
Stijn

**Comment by kurtschelfthout** [comment]
Hm, yes. Interesting question. On the whole it's certainly useful, and the cost of adding to FsCheck proper is not great - the properties you have there seem pretty much timeless and don't add any further complications (like dependencies etc). I also like that perhaps they could give some ideas to newcomers on what properties they can write.

On the other hand there are some advantages to keeping these things separate - for example you do become dependent on FsCheck versioning, API stability and release scheme. And I would probably not like to take on additional dependencies for other kinds of "abstract properties". I am also a bit mindful that many people in the F#/C# world dislike operators, so at the very least we'd have to come up with a different namespace to put these things in.

One alternative to complete convergence is to keep both projects separate but move your repo to the FsCheck org (i.e. it would be fscheck/FsCheck.Properties or something like that (Extras sounds a bit too vague to me). You'd still own the repo more or less like you do now (I guess there could be some subtleties with github organisations so it's not _exactly_ the same, I'm not an expert), but it might benefit from some additional visibility.

Just thinking out loud here...

**Comment by kurtschelfthout** [comment]
I'm not an expert in this, but I invited you as a member in the FsCheck organization, and have allowed members to create repositories. So you should be able to do: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ and then the "root" FsCheck.Properties repository should appear as fscheck/FsCheck.Properties and you should be able to clone, push etc like it was under your user account.
