### ISSUE TITLE
Property attribute causes the test to be excluded from the Live Unit Testing with XUnit.

### ISSUE THREAD

**Issue by OnurGumus** [fscheck/FsCheck#429]
After adding a Property Attribute, Visual studio does not do any live unit testing for that test. Converting it to Fact makes it working again.

**Comment by kurtschelfthout** [comment]
This is likely because live unit testing looks for Fact attributes explicitly. I don't think there is much we can do about that here - probably more of a question for the VS team in the first instance?

Feel free to come back here if you have better information.
