### ISSUE TITLE
Suggestion: string generator that draws from a user-supplied file

### ISSUE THREAD

**Issue by rmunn** [fscheck/FsCheck#430]
The [Big List of Naughty Strings](https://github.com/minimaxir/big-list-of-naughty-strings) or BLNS is not a list of swearwords or other words considered "naughty" from a human perspective; rather, it's a list of strings that are likely to cause problems in various kinds of code, such as `<img \x00src=x onerror="alert(1)">` (which might trigger a bug in an HTML parser) or `😍` (which might trigger a bug in a program that assumed that ALL UTF-16 characters will be two bytes, and forgot about surrogate pairs).

It might be a good idea for FsCheck's string generator to, about half the time, create a string drawn randomly from the BLNS. Completely-random strings are also important, but a string drawn from a known list of potentially-dangerous values would be useful in even more testing scenarios than a randomly-generated string.

**Comment by kurtschelfthout** [comment]
I don’t think we’d make it part of the standard string generator. I’d be more open (but not entirely convinced) to add a separate “naughty string” generator, which would allow people to combine random and naughty with a distribution they choose. 

I’m also not sure if it would be ok to include this list of strings in FsCheck, where does that end? Maybe it’d be better to have a generator that takes a file (in various common formats) as input and chooses arbitrarily from the list in there.  That would make it easy for people to write this generator and modify the file as they see fit.

**Comment by rmunn** [comment]
I like the idea of generalizing this to draw from a file. Common formats would probably include plaintext (newline-delimited), JSON, and maybe XML. Though XML would be more complicated: you'd also have to specify the element name that would contain each individual string, or perhaps an XPath search string whose results would provide the data. And then there's the question of XML files where the desired strings are in attributes vs. in element contents... But plaintext and JSON would both be simple to implement.

**Comment by ploeh** [comment]
If you start to separate concerns, I think you'd agree that there are two concerns here:

1. A generator that picks from a list of pre-defined values.
2. An engine that can read in files and parse them.

The first feature already exists in FsCheck: it's called `Gen.elements`. The second feature, I'd argue doesn't belong in FsCheck at all.

**Comment by kurtschelfthout** [comment]
> The first feature already exists in FsCheck: it's called Gen.elements. The second feature, I'd argue doesn't belong in FsCheck at all.

Yes, good point. I agree.

> But plaintext and JSON would both be simple to implement.

Plain text is so simple it's really not worth adding to the API (```filename |> File.ReadAllLines |> Gen.elements```). JSON, I don't think it's worth taking a dependency on a Json parser just for it.

This made me think a bit on when I'd be inclined to extend FsCheck's API surface.

With new generator "combinators", i.e. that are parametrized on other generators, it would have to either offer significant new functionality that can't be achieved with combining anything less than a handful of existing combinators. And even then it might be a close call, depending how niche it is. One exception is performance; if there is a significant performance benefit I'd be more happy to specialize.

For primitive generators (i.e. that generate a new type of thing), they'd have to be sufficiently complicated to write yourself (e.g generate F# quotations, expression trees, state machines,...) and if they add extra dependencies on FsCheck, that would be a much closer call. I'd be in favor of separating to a separate library in the latter case.
