### ISSUE TITLE
Exception when comparing generated map containing private DU

### ISSUE THREAD

**Issue by jbezak** [fscheck/FsCheck#436]
I ran into an exception when running following test:

> Message: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
---- System.ArgumentException : The type 'SiteAgent.MessageGateway.Server.Tests.Foo+Bar' is an F# union type but its representation is private. You must specify BindingFlags.NonPublic to access private type representations.
Parameter name: unionType

```
open FsCheck
open FsCheck.Xunit

module Foo =
    type Bar = private Bar of string
    let create bar = Bar bar

module DataTests =
    [<Property>]
    let ``empty = generated nonEmpty`` (bars: Map<Foo.Bar, string>) =
        not (bars.IsEmpty) ==> lazy
        let emptyMap : Map<Foo.Bar, string> = Map.empty
        emptyMap = bars
```
When the map is created inside the test it fails correctly without the exception:
```
    [<Property>]
    let ``empty = nonEmpty``() =
        let bar = Foo.create "bar"
        let nonEmptyMap = Map [ bar, "bar" ]
        let emptyMap : Map<Foo.Bar, string> = Map.empty
        emptyMap = nonEmptyMap
```

> map [] = map [(Bar "bar", "bar")]
false
Expected: True
Actual:   False

**Comment by ploeh** [comment]
That seems like reasonable behaviour to me. Since you're reporting this, I suppose your expectation was different. What do you think should happen instead?

**Comment by ploeh** [comment]
That seems like reasonable behaviour to me. Since you're reporting this, I suppose your expectation was different. What do you think should happen instead?

**Comment by jbezak** [comment]
I expected that the ``empty = generated non-empty`` test would produce a failing test, not a test throwing an exception, same as the non-generated example.

**Comment by kurtschelfthout** [comment]
FsCheck does not generate private union/record types.  See #186.

The idea is that those are private for a reason, and so it can't just generate arbitrary data, there are some preconditions that need to be satisfied.

**Comment by jbezak** [comment]
If I understand the pull request you've mentioned correctly it actually adds the functionality to generate private DU. That is also what I am seeing when debugging the tests.

I realized that the exception does not occur during the generation but during shrinking for failed tests.
This test is passing but when it fails, shrinking will not help me to find the failing values.
  ```
    [<Property>]
    let ``generating nonEmpty`` (bars: Map<Foo.Bar, string>) =
        not (bars.IsEmpty) ==> lazy
        not bars.IsEmpty
```

**Comment by kurtschelfthout** [comment]
Let's say we're considering whether to add it and if yes, how to add automatic generation/shrinking for private types. Imo we can add it but we should make it opt-in.

Meanwhile I'll close this, as I don't want to duplicate the discussion here. Feel free to add any thoughts to the other discussion, or re-open if there is anything unrelated that you still have a problem with.
