### ISSUE TITLE
Q: Traverse/Sequence can be usefull for generators?

### ISSUE THREAD

**Issue by stijnmoreels** [fscheck/FsCheck#438]
Hi,

I was working on a project and needed actually the `traverse/sequence` functionality for generators.
I implemented it like this:

```fsharp
let traverseA f xs =
    let cons h t = h :: t
    let folder h t = 
        Gen.constant cons <*> f h <*> t
    Gen.constant []
    |> List.foldBack folder xs

let sequenceA xs = traverseA id xs

let traverseM (f : 'a -> Gen<'b>) xs =
    let cons h t = h :: t
    let folder head tail =
        f head >>= fun h -> 
            tail >>= fun t -> 
                Gen.constant (cons h t)
    Gen.constant []
    |> List.foldBack folder xs
            
let sequenceM xs = traverseM id xs
```

But I'm not sure that
1 it's a implemented correctly (performancewise, ...)
2 it's useful enough to be of value in the FsCheck library

Thanks in advance!

Greetings
Stijn

**Comment by kurtschelfthout** [comment]
If I'm reading that correctly, `Gen.sequence` already exists (and yes, your implementation will stackoverflow for long lists).

I think adding `Gen.traverse` in the same vein is useful enough. Should be straigghftorward by copying and slightly modifying the current implementation(s) of `Gen.sequence` (I think there are a few, specialized to collection types for perf reasons) , and then change the implementations of `Gen.sequence` to call the new implementations of `Gen.traverse`.
