### ISSUE TITLE
Question : why hidden Gen functions?

### ISSUE THREAD

**Issue by Chadehoc** [fscheck/FsCheck#440]
Why are `Gen.where`, `Gen.sized` (and other functions) hidden from code hints in Visual Studio using the `EditorBrowsableState.never` annotation?

I rely on hints to remind me of the possibilities. Those are costly, I suppose it is the reason, but why hide them instead of adding for example a warning in the doc string?

**Comment by kurtschelfthout** [comment]
Are you using C#?

**Comment by Chadehoc** [comment]
No, this was from F# (VS 2017). Completion (Ctrl-Space) after typing `Gen.` just does not propose some useful functions.

**Comment by kurtschelfthout** [comment]
Hm, I guess the F# intellisense has caught up a little bit. It used to be only C# that honored those attributes, and so it was a trick to hide methods from C# users while keeping them visible for F# users. 

I guess we can't use that trick anymore, as a first step I agree the attributes should be removed then.

**Comment by kurtschelfthout** [comment]
Yeah, thanks for the idea…I was taking this as a lesson to avoid those kinds of tricks though ;)
