### ISSUE TITLE
Cannot add package to Linqpad query

### ISSUE THREAD

**Issue by ddewaleffe** [fscheck/FsCheck#446]
A while back, I have been able to use fscheck in a linqpad query. (www.linqpad.net)

Now I cannot anymore. There is an exception "'FSCheck' already has a dependency for 'FSharp.Core'"
The list of dependencies indeed lists 2 versions of FSharp.Core.

![image](https://user-images.githubusercontent.com/1861106/44001189-791aaa66-9e2d-11e8-9ef6-f41d0a50fe8b.png)

**Comment by kurtschelfthout** [comment]
This is likely a Linqpad problem. FsCheck depends on different versions of FSharp.Core depending on what framework it targets: https://www.nuget.org/packages/FsCheck/2.11.0 

Then again not sure if that is really the problem; I was able to install FsCheck 2.9.2 into Linqpad and that also has this conditional dependency. So I think LinqPad is somehow getting confused.

**Comment by ddewaleffe** [comment]
Submitted this issue to Linqpad team. Hope this can be resolved...

**Comment by kurtschelfthout** [comment]
Ok, me too :) Please re-open if this does somehow have anything to do with FsCheck. (Or if there's something we can avoid in the package definition that Linqpad doesn't like)

**Comment by kurtschelfthout** [comment]
http://forum.linqpad.net/discussion/1697/system-invalidoperationexception-fscheck-already-has-a-dependency-defined-for-fsharp-core

Seems like they fixed this.
