### ISSUE TITLE
Unable to generate Arbitrary of a ArrayList with its elements as Arbitraries 

### ISSUE THREAD

**Issue by gayatrihimthani** [fscheck/FsCheck#447]
I am using FsCheck in C#, I want to generate Arbitrary of an ArrayList to do PropertyBasedTesting by having 100's of ArrayList. I have this ArrayList with defined Arbitraries (they cannot be changed) for each element in it -
E.g. `System.Collections.ArrayList` a = new System.Collections.ArrayList();
            a.Add(Gen.Choose(1, 55));
            `a.Add(Arb.Generate<int>());`
            `a.Add(Arb.Generate<string>());` `
How do I get an Arbitrary of this ArrayList?

**Comment by kurtschelfthout** [comment]
Easiest to understand is to use Linq syntax, approximate example, assuming a helper method `MakeNewArrayList(params object[] elements)` with the straightforward implementation:

    from e1 in Gen.Choose(1,55)
    from e2 in Arb.Generate<int>()
    from e3 in Arb.Generate<string()
    select MakeNewArrayList(e1, e2, e)

That will give you something of type `Gen<ArrayList>` which you can make into an `Arbitrary<ArrayList>` by calling `ToArbitrary()` on it.

Hope that helps.

**Comment by ploeh** [comment]
Cross-posted from https://stackoverflow.com/q/51899653/126014
