### ISSUE TITLE
FsCheck.NUnit does not work with NUnit v3.10.1

### ISSUE THREAD

**Issue by GennadyGS** [fscheck/FsCheck#450]
When using FsCheck.NUnit of version 2.11.0 along with NUnit of version 3.10.1 in Visual studio 15.8.5, tests are not executed.

Expected behavior: tests are discovered and executed.

Actual behavior: tests are discovered but not executed without any failure messages and without change of status. At the same time everything works as expected with NUnit 3.9.0.

**Comment by kurtschelfthout** [comment]
This is probably because of version confusion. I've just released FsCheck v2.12.0 to NuGet, which updates its NUnit dependency to 3.10.1. That should fix your problem.

Please re-open if it doesn't.

**Comment by GennadyGS** [comment]
After update it works.
Thanks a lot!
