### ISSUE TITLE
FsCheck.Xunit.CheckExtensions.QuickCheckThrowOnFailure(Property, ITestOutputHelper) doesn't throw on failure

### ISSUE THREAD

**Issue by WalkerCodeRanger** [fscheck/FsCheck#451]
I'm using FsCheck with XUnit from C#. When I use `QuickCheckThrowOnFailure` and *don't* pass the `ITestOutputHelper` it throws an exception on failure and XUnit marks the test failed. However, when I *do* pass the `ITestOutputHelper` it doesn't throw on failure. The output text says there is a failure, but XUnit doesn't mark it a failure. Sample code:
```
[Fact]
public void Does_Not_Throw()
{
	Prop.ForAll<string>(input =>
	{
		return false;
	}).QuickCheckThrowOnFailure(testOutput);
}
````

I'm not experienced in F#, but it looks like the problem is that this replaces the runner, but it is the runner that is responsible for throwing the exception.

**Comment by ploeh** [comment]
Is there a particular reason you don't use the `[Property]` attribute?

**Comment by ploeh** [comment]
Are you using `Arb.Register`?

**Comment by kurtschelfthout** [comment]
Think you're right. See the PR, should help.

**Comment by WalkerCodeRanger** [comment]
@ploeh I've opened issue #453 for the problem I was having when using `Arb.Register`. I've since stumbled across your [StackOverflow answer](https://stackoverflow.com/a/32843204/268898) where you recommend a different style. I agree that it combining the `Property` attribute with `Prop.ForAll` is a much better way to do it and have switched to that style for all my tests.
