### ISSUE TITLE
Mapping seemingly degrades performance

### ISSUE THREAD

**Issue by Savelenko** [fscheck/FsCheck#462]
I have the following definitions using 2.13.0 (somewhat pseudo-notation):
~~~fsharp
// Custom generators

// Gen<Tree<Box<'a>>>
let genTree () = TreeGenerator.tree Arb.generate<Box<'a>>

type T<'a> = T of Tree<Box<'a>>

// Gen<T<'a>>, so basically a packaged tree
let genWrappedTree () = T <!> genTree ()

// Registrations and tests

type Generators () =
   static member T () = Arb.fromGen ^ genWrappedTree ()
   static member Tree () = Arb.fromGen ^ genTree ()

// Takes 5 minutes to complete with huge input data
let prop1 (tree : T<int>) = predicate tree

// Takes 2 seconds to complete with good looking input data
let prop2 (tree : Tree<Box<int>>) = predicate (T tree)
~~~

Generator `TreeGenerator.tree` recursively generates a rose tree (with elements generated by the given generator) taking current size into account and distributing it among the sub-trees. `Box<'a>` is a record type. Generators `genTree` and `genWrappedTree ` differ only in mapping over the box tree generator.

It would seem that mapping in `genWrappedTree ` considerably affects performance: `prop1` is wildly slower than `prop2`, where `T` is applied inside the test. Besides running times, I made the following observations:

- Input generated in `prop1` is _much_ larger than in `prop2`. 300000 lines vs 7000 when using the verbose configuration.
- Not registering `genWrappedTree` makes `prop1` and `prop2` comparable, both in terms of running time and generated input.
- `T <!> Gen.resize 1 (genTree ())` helps, but
- `Gen.sized (fun s -> T <!> Gen.resize s (genTree ()))` does not.

I am especially puzzled by the second observation. This example is but a simple wrapper which could be applied inside a property, but my real use-case is working with another tree type, which is the result of applying a catamorphism to `Tree<Box<..>>` instead of `T`. So I would like to have a `genWrappedTree `-like generator, but this seems out of reach for the moment.

Am I doing something wrong and is there an explanation for this performance drop and size behavior?

**Comment by kurtschelfthout** [comment]
Hm, interesting. I will take a look. Thanks for the details writeup.

**Comment by kurtschelfthout** [comment]
It is hard to say much more without having working code (in particular `TreeGenerator`) but it seems to me that the tree generator is generating very large trees, and perhaps something is wrong with registration so that in some cases FsCheck's default reflection based generators kick in. I can likely be more specific if you can give a full repro (also with the generator registration code etc).

As for

> T <!> Gen.resize 1 (genTree ()) helps, but
> Gen.sized (fun s -> T <!> Gen.resize s (genTree ())) does not.

this seems normal to me; the second line is essentially a no-op. You're passing whatever size `s` you have in the T generator to the `Tree` generator unchanged; this is also what `map` does by default. The first line sets the size to 1 for the tree generator which will make your tree generator generate very small trees.

**Comment by Savelenko** [comment]
I managed to make a simple reproduction. First, here is the tree and `TreeGenerator.tree` (without its module):
~~~fsharp
type Tree<'a> = TreeNode of 'a * List<Tree<'a>>

let tree dataGenerator =
    let rec go s = gen {
        let! d = dataGenerator
        if s = 0 then return TreeNode (d, [])
        else
        // Determine a random branching degree and generate a node with this degree.
        let! deg = Gen.choose (1, s)
        let! subtrees = Gen.piles deg (s - deg) >>= Gen.collect go
        return TreeNode (d, subtrees)
    }
    Gen.sized go
~~~

The actual reproduction with annotated experiments:
~~~fsharp
type Box<'a> = {
    // The type of this field appears to make a difference: try 'a and List<'a>.
    Contents : List<'a>
}

(*--------------------------------------------------------------------------------------------------------------------*)

type T<'a> = T of Tree<Box<'a>>

(*--------------------------------------------------------------------------------------------------------------------*)

let genTree () = TreeGenerator.tree Arb.generate<Box<'a>>

let genWrappedTree () = T <!> genTree ()

(*--------------------------------------------------------------------------------------------------------------------*)

type Generators () =
   // Registering this or not also appears to make a difference.
   static member T () = Arb.fromGen ^ genWrappedTree ()
   static member Tree () = Arb.fromGen ^ genTree ()

(*--------------------------------------------------------------------------------------------------------------------*)

[<TestClass>]
type ``Tree mapping tests`` () =

    [<TestMethod>]
    member t.Fast () : unit =
        let prop (_ : Tree<Box<int>>) = true
        Check.verboseThrowOnFailure [with'<Generators>] prop

    [<TestMethod>]
    member t.Slow () : unit =
        let prop (_ : T<int>) = true
        Check.verboseThrowOnFailure [with'<Generators>] prop

(*
Experiment 1: Contents : 'a, both generators registered : Slow is OK, but still slower than Fast with slightly larger
generated inputs.

Experiment 2: Contents : 'a, "wrapped" generator not registered : Slow is fast.

Experiment 3: Contents : List<'a>, both generators registered : Slow is 13x slower than Fast.

Experiment 4: Contents : List<'a>, "wrapped" generator not registered : Slow is fast.

Experiment 5: Contents : List<'a>, both generators registered, additionally explicit sizing of the contents of the tree
(Gen.resize s dataGenerator): outcome comparable to that of Experiment 1.
*)
~~~

Experiment 3 seems most interesting: changes the structure of `Box` somehow causes the structure of the tree itself to become much larger. Along the other dimension, not registering the `T`-generator seems to always help. Could this somehow be related to the discussion about nested complex types I read in another issue?..

**Comment by kurtschelfthout** [comment]
Yes, it is related to size and nested complex types. Unfortunately I'm a bit short on time to look into this all the way to the bottom, but I have the shape of the problem pretty much isolated. Do feel free to ask for more help if the following does not lead you on the right path...

If you look at the implementation of your `Tree` generator, you can see that you (sensibly) apply size constraints to the subtrees. But, crucially, you do not apply the same size constraint to the _values_ in each node, like so:

```fsharp
let tree dataGenerator =
    let rec go s = gen {
        let! d = Gen.resize s dataGenerator
        // identical
    }
```
The reflective generator (basically what you're using if you _don't_ register a custom generator) on the contrary does apply this size constraint to the entire nested type, including the value. So by making the change above you should see similar behavior whether you register the generators or not.

This also explains why making `Box` a list or not makes a difference; it's it's just a simple value like say an `int` it doesn't really slow down the generation much even for larger sizes (time should be constant no matter what the size). But a `list` generator is generally much slower and time is linear in the size; so it's much more affected by the absence of a size constraint in your custom `Tree` generator.

Hope that makes some sense, like I said feel free to keep asking questions if it doesn't.
