### ISSUE TITLE
Shrunk sequence of float is already distinct

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#473]
Currently, in the implementation of the float and float32 default shrinkers, there is call of Seq.distinct as the last operation. But there is no need of it:
* If the input is Nan || Infinity then the shrunk seq consists of single element
* If the input is normal and >= 0 or is already truncated then the shrunk seq consists of single element
* Even if the input is normal and <0 and isn't truncated then the shrunk seq {-input, truncated_input} is distinct (-input isn't truncated, so it can't be equal to smth truncated)

Am I right? Though the call of Seq.distinct is very cheap, the code may be simplified. Is PR with simple test and removing those calls necessary?

**Comment by kurtschelfthout** [comment]
Sounds right, but I can't be certain. I don't remember why the `distinct` is there to be honest. Remove it, test, see what happens?

**Comment by Kharacternyk** [comment]
I've already writen test, it passes. Should I create a pull request?

**Comment by Kharacternyk** [comment]
I've changed my mind. If shrinker is changed and the Seq.distinct call is removed then duplicates may occur. Maybe, it should be kept as it is.
