### ISSUE TITLE
Trivial default arbitraries

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#474]
FsCheck doesn't have default arbitraries for quite a lot types from std library (StringBuilder, concurent collections, etc.), though they are very trivial to implement, 'cause they are just wrappers (in some way) of types that FsCheck can generate. So, is it by-design? For example, is explicity creating the StringBuilder instance via string by user is better way? Does creating default arbitraries make sense?

**Comment by Kharacternyk** [comment]
TL;DR: Do default arbitraries that don't require special generating/shrinking logic worth implementing?

**Comment by kurtschelfthout** [comment]
I think creating default arbitraries generally makes sense to improve user convenience. One must be a bit careful with generating mutable types though - esp. if they get mutated in the test itself things could get a bit hairy. But I don't think there is much to do about that in the generator/shrinker, besides making sure you don't mutate the instances yourself of course. Always copy.

I would be likely to say no to adding a type that is not in the .NET Framework (or standard or whatever the target is) and so would require FsCheck itself to take on a new dependency.
