### ISSUE TITLE
Fresh mutable types and default arbitraries

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#477]
Though generating mutable types may cause problems while shrinking, FsCheck provides default arbitraries for ICollection and IDictionary types with implemented shrinkers. Thus, if I got it right, we just hope that user won`t change instance, or, if so, will "reset" it. My proposal is introducing a bunch of Fresh[MutableTypeNameHere] types among with default arbitraries for them. These types will have only  public method Construct, intended to be used at the begining of the property. I see using scenario like this: 
```f#
[<Property>]
let MyCollectionProperty (value : FreshCollection) =
    let collection : ICollection = value.Construct()
    //do whatever you want with your collection
```
And the implementation looks like this:
```f#
type FreshCollection =
    internal _freshCollection of list<`a>
    member this.Construct() = match this with | _freshCollection l -> FsListToCollection l

type Default =
//...
    static member FreshCollection() =
        let generator = Defalut.List().Generator |> Gen.map (fun l -> _freshCollection l)
        let shrinker (c : FreshCollection) = 
            match c with 
            | _freshCollection l -> 
                shrink l 
                |> _freshCollection
        fromGenShrink(generator, shrinker)
//...
```
Of course, prefix "Fresh" and other details of API may be changed.

**Comment by kurtschelfthout** [comment]
I see. Interesting idea. I wonder if it’s worth adding this - in a sense just generating an immutable collection type or even an array and then passing that to the constructor of the featured mutable type yields very similar - maybe even simpler - code and needs no changes to FsCheck?

Whereas adding the mutable types directly as arbitraries makes things a bit more convenient, but at the cost of some potential confusion (although presumably not more than with mutable types in general)

**Comment by Kharacternyk** [comment]
I agree, it isn't much suitable for collections. Explicit way is much simpler. I think Fresh wrappers may improve convenience for complex reference types, that require a lot of params in constructor or values for setters:
1) We incapsulate all of these params in Fresh type
2) We encapsulate non-trivial shrinker, that is suitable for this class
3) We override ToString() for pretty displaying class instance in property failure message

**Comment by Kharacternyk** [comment]
But, to be fair, I haven't found such types in std library:)
