### ISSUE TITLE
"Zero" item in shrunk sequences

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#479]
Why generic zero is yielded at second place? It is ok for trivial tests, because we rapidly find the simplest counter-example. But most of the tests are not that trivial, and testing zero each iteration of shrinking looks inefficient to me. What about make zero the last element of sequence?

**Comment by kurtschelfthout** [comment]
It's a heuristic that in my experience works well in practice, also for real-life tests.

**Comment by Kharacternyk** [comment]
Should shrinker for flags also yield None in first place?

**Comment by kurtschelfthout** [comment]
> Should shrinker for flags also yield None in first place?

Yeah, maybe. Would be consistent. But to be honest I hardly ever use flags so hard to really opine...would be fine with leaving as is.

**Comment by Kharacternyk** [comment]
Maybe, this trick should be used more frequently? It isn't clear to me why default shrinkers of array (non-fixed length) and string (which is just array of characters) don't yield empty array.

**Comment by kurtschelfthout** [comment]
Yeah...that's probably at the whim of whoever implemented the shrinker first. Perhaps in some cases for good reason, in others not so much.

I do agree it is inefficient to do this as "zero" will be tried repeatedly if it's not a good shrink. But on the other hand if it is a good shrink we try it immediately and so we have a lot fewer shrink attempts in that case. It's possible to make a convincing argument either way.

**Comment by Kharacternyk** [comment]
It's weird that float shrinker doesn't yield 0.0 at all (if input isn't NaN or infinity).

**Comment by kurtschelfthout** [comment]
> It's weird that float shrinker doesn't yield 0.0 at all (if input isn't NaN or infinity).

Agreed.
