### ISSUE TITLE
Make float generator unsized

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#483]
Since there are Double.MaxValue, Double.MinValue, infinities, NaN and epsilon, what is the reason to generate other values within range determined by size? I think NormalFloat is better for sized scenario.

**Comment by kurtschelfthout** [comment]
Hm, don't know about this. The whole float range is pretty big, this way there's a better chance to find counterexamples that are smaller or special. There is also the `DoNotSize` constructor to easily take the size constraints off (though to be honest I'm not a 100% it works with floats, it should).

**Comment by Kharacternyk** [comment]
The problem is `Default.fraction` function. It just can't generate floats bigger than `2 * Int32.MaxValue` even when sizing is turned of. Though I agree that we should produce most of the numbers small (maybe via sizing, not via gen function constraint), but there should be way to produce values in whole range (as I mentioned, `Default.fraction` is restricted by nature, so `DoNotSize` won't help).

**Comment by Kharacternyk** [comment]
So, after some research, here is my proposal:
* `Float`: we generate `DoNotSize<uint64>` and via BitConverter create float
* `NormalFloat`: we generate `DoNotSize<uint64>` and use [this algorithm](http://xoshiro.di.unimi.it) (see "Generating uniform doubles in the unit interval") to create double in range [0, 1) and then   multiply it by size parameter

Thus, we would get real uniform distribution in both cases. Also, the size parameter in `NormalFloat` generator would get some sense — it would be the biggest possible value. I think present shrinkers would be ok as they are (a little change — yield 0.0, (#479)).

**Comment by kurtschelfthout** [comment]
> Though I agree that we should produce most of the numbers small (maybe via sizing, not via gen function constraint), but there should be a way to produce values in the whole range (as I mentioned, Default.fraction is restricted by nature, so DoNotSize won't help).

Agreed.

Thanks a bunch for the research!

On your proposal, I like `NormalFloat`, but can't we generate `Float` by taking `NormalFloat` and adding the special values (NaN, infinities, etc.?)

**Comment by Kharacternyk** [comment]
I see your point. Yeah, it could be this way. Then what about the `WholeRangeFloat` type that would generate uniformly distributed float?

**Comment by Kharacternyk** [comment]
Hah, I just realized that `WholeRangeFloat` is just `DoNotSize<float>`, sorry :)

**Comment by Kharacternyk** [comment]
In the PR above I've left max, min and epsilon. I'll implement `DoNotSize<float>` later.

**Comment by kurtschelfthout** [comment]
Good stuff!

**Comment by Kharacternyk** [comment]
As I described in PR, I don't think `DoNotSize<float>` is helpful anymore. Closing it :)
