### ISSUE TITLE
Standardize docs in Arb.Default

### ISSUE THREAD

**Issue by Kharacternyk** [fscheck/FsCheck#492]
Some current issues:
* Mention uniform distribution in sized integer (float, decimal) gens?
* Add info about shrinkers of number types?
* Mention that `Byte` gen is unrestricted by size?
* Mention probability of `null` (1/10 currently) in string gen?
* Mention that `Array` and other collections (`Set`, `Map`) length is determined by size?

Issues above are important because xml docs are the only source of information about Default arbs. 
Also, minor issue about style: *Generate* or *Generates*?

**Comment by kurtschelfthout** [comment]
I think more clarity and info generally is definitely a Good Thing. So yes to all of the above!

> Also, minor issue about style: Generate or Generates?

I suggest "generates", because "generate" sounds like a command :)

As a template:

Generates `<type>` values `<size or other restrictions>`
`<other notes>`

For example
Generates uint16 values between 0 and size.


And I don't think we need to repeat "uniform distribution" every time, but just assume it unless we mention something else. Also lots of the comments seem to contain "arbitrary" like "Generates arbitrary uint16 values..." which I think we can also omit.

**Comment by kurtschelfthout** [comment]
For info about shrinkers I'm less sure. Perhaps something like:

Shrinks values towards 0.

Or 

Shrinks values towards the empty list, and shrinks elements.

Suggestions welcome.

**Comment by Kharacternyk** [comment]
I'm not sure how to properly describe integer shrinker. Maybe it is too complex to sumarize it in xml docs. It may be a paragraph on github.io docs. Collections as well.

About floats I think `Shrinker yields zero, absolute value of input and truncated input` will be fine.

**Comment by Kharacternyk** [comment]
> `Shrinker yields zero, absolute value of input and truncated input`

Or use `origin` instead of `input`

**Comment by Kharacternyk** [comment]
> And I don't think we need to repeat "uniform distribution" every time, but just assume it unless we mention something else.

Should it be written anywhere? Or it is already mentioned and I haven't noticed? To be honest, I thought output is concentrated on smaller values even when size is large when I used FsCheck first times.

**Comment by kurtschelfthout** [comment]
> Should it be written anywhere? Or it is already mentioned and I haven't noticed? To be honest, I thought output is concentrated on smaller values even when size is large when I used FsCheck first times.

It's a relatively complicated topic. The best you can say is that _for a given size_, the values are uniformly distributed in a range. But during the test - by default - FsCheck will increase the size gradually and linearly. So if you look at 100 tests certainly the distribution will focused on the smaller size elements.

**Comment by Kharacternyk** [comment]
> The best you can say is that for a given size, the values are uniformly distributed in a range.

This is what I suggest to mention. It is important trait of the default integer gens. Increasing size during the test running is already described in the docs.

**Comment by Kharacternyk** [comment]
Fixed in #497.
