### ISSUE TITLE
DivideByZeroException in Gen.Choose

### ISSUE THREAD

**Issue by ekvVN** [fscheck/FsCheck#499]
Hello. I'm started trying to use FsCheck in C# Project. And I use simple example in test to generate any number from all range of int values:

```csharp
    [Test]
    public void Test_MinMax()
    {
        var generator = Gen.Choose(int.MinValue, int.MaxValue);
        foreach (var val in generator.Sample(10, 10))
            Console.WriteLine(val);
    }
```

And I got exception in test output in FsCheck:
```csharp
System.DivideByZeroException : Attempted to divide by zero.
   at FsCheck.Random.stdRange(Int32 l, Int32 h, StdGen rng)
   at FsCheck.Random.range@74-1.Invoke(StdGen rng)
   at FsCheck.Gen.Choose@178.Invoke(Int32 _arg1, StdGen r)
   at FsCheck.Gen.sample@170[a](Int32 size, Gen`1 generator, Int32 i, StdGen seed, FSharpList`1 samples)
   at FsCheck.Gen.Sample[a](Int32 size, Int32 n, Gen`1 generator)
   at FsCheck.GenExtensions.Sample[a](Gen`1 generator, Int32 size, Int32 numberOfSamples)
```

Is this a bug? Or, i'm doing something wrong?

**Comment by ekvVN** [comment]
I viewed in source code of [stdRange](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Random.fs). 
And I think, this happens in this line of code:
`let k = h - l + 1`

and in stacktrace argumens 'h' and 'l' have an 'Int32' type:
k = (int) (2147483647 - (-2147483648) + 1) = (int)(4294967296) = 0
because value 4294967296 can hold in 33 bit, but 'int' hold only 32 bit

PS: maybe i'm wrong, because a'm only view the code

**Comment by Kharacternyk** [comment]
> I viewed in source code of stdRange.
And I think, this happens in this line of code:
let k = h - l + 1

Yeah, you're right. Because of this problem the source code of the `DoNotSize<int>` use a trick:
```f#
        ///Generates int32 values that are unrestricted by size.
        static member DoNotSizeInt32() =
            //let gen = Gen.choose(Int32.MinValue, Int32.MaxValue) doesn't work with random.fs, 
            //so using this trick instead
            let gen =
                Gen.two generate<DoNotSize<uint16>>
                |> Gen.map (fun (DoNotSize h,DoNotSize l) -> int ((uint32 h <<< 16) ||| uint32 l))
            fromGenShrink(gen, shrink)
            |> convert DoNotSize DoNotSize.Unwrap
```
If you want to generate ints in the whole range, you should use `Arb.Default.DoNotSizeInt32` or implement a generator that uses a bit shifting yourself.

AFAIK FsCheck 3.0 uses a new random algorithm and has got rid of this problem. There is already a preview version of v3.0 and you can take a look at it.

**Comment by ekvVN** [comment]
Thanks. I tried `DoNotSizeInt32 `, and seem's it's works as I planned.

**Comment by ekvVN** [comment]
```fsharp
        ///Generates int32 values that are unrestricted by size.
        static member DoNotSizeInt32() =
            //let gen = Gen.choose(Int32.MinValue, Int32.MaxValue) doesn't work with random.fs, 
            //so using this trick instead
            let gen =
                Gen.two generate<DoNotSize<uint16>>
                |> Gen.map (fun (DoNotSize h,DoNotSize l) -> int ((uint32 h <<< 16) ||| uint32 l))
            fromGenShrink(gen, shrink)
            |> convert DoNotSize DoNotSize.Unwrap
```

I try to understand F# code. Is in C# code of generator looks like this, or it's wrong?

 ```csharp
       public static Arbitrary<DoNotSize<int>> CSharpDoNotSizeInt32()
        {
            var gen = Gen.Two(Arb.Generate<DoNotSize<ushort>>())
                .Select(tuple =>
                {
                    var h = (int)tuple.Item1.Item;
                    var l = (int)tuple.Item2.Item;
                    return h << 16 | l;
                })
                .Select(DoNotSize<int>.NewDoNotSize);
            // fromGenShrink(gen, shrink)   <----- How write this in C# ?
            return Arb.From(gen);
        }
```

and what equivalent of `fromGenShrink(gen, shrink)` in C#?

**Comment by Kharacternyk** [comment]
It seems right, except that F# version firstly create an arbitrary for `int` and then uses Arb.convert to create an arbitrary for `DoNotSize<int>`. I think shrinking wouldn't work in your version because `Arb.Shrink` tries to find an `Arbitrary<DoNotSize<int>>` that doesn't exist yet. The F# version is closer to
```c#
//your code
return Arb.From(gen, i => (Arb.Shrink i.Item).Select(DoNotSize<int>.NewDoNotSize));
```

**Comment by ekvVN** [comment]
I yet don't understant how and where to use `DoNotSize<T>`, and did this function simpler.
And yet I need uniform distribution and used Gen.Choose for range [0, ushort.MaxValue]:
```csharp
        /// <summary>
        /// Генератор для получения значений из диапазона [int.MinValue, int.MaxValue]
        /// с равномерным распределением (Gen.Choose)
        /// </summary>
        public static Arbitrary<int> GenMinMaxInt32()
        {
            var gen = Gen.Two(Gen.Choose(0, ushort.MaxValue))
                .Select(tuple =>
                {
                    var h = tuple.Item1;
                    var l = tuple.Item2;
                    return h << 16 | l;
                });
            return Arb.From(gen, Arb.Shrink);
        }
```
and for uint:
```csharp
        /// <summary>
        /// Генератор для получения значений из диапазона [uint.MinValue, uint.MaxValue]
        /// с равномерным распределением (Gen.Choose)
        /// </summary>
        public static Arbitrary<uint> GenMinMaxUInt32()
        {
            return GenMinMaxInt32().Convert(x => (uint) x, x => (int) x);
        }
```

In this function Arb.Shrink is correct used (for 'int' value)? 
Or for it need's not uniform distribution?

**Comment by Kharacternyk** [comment]
> In this function Arb.Shrink is correct used (for 'int' value)?

Yes. You'll get uniform distribution.

> What are the advantages of type DoNotSize<T> over raw T?

DoNotSize<T> is useful when FsCheck choose an arbitrary implicitly. For example
```c#
[Property]
public void TestDoNotSize (DoNotSize<int> i)
{
    TestYourInteger(i.Item);
}
```
FsCheck sees `DoNotSize<int>`, so it uses the `Arb.Dedault.DoNotSizeInt32` arbitrary and generate ints in the full range.

**Comment by Kharacternyk** [comment]
`DoNotSize<T>` types are just a way to tell FsCheck that you want `T` in the whole range. They are wrappers around `T` without any additional behaviour.

I see you are an Russian speaker, so you may contact me on The Telegram if you have additional questions (I think issues on GitHub should be readable for everyone and using English here is the right way).

http://t.me/Kharacternyk

Удачи!
