### ISSUE TITLE
Running FsCheck.NUnit doesn't show number of tests

### ISSUE THREAD

**Issue by afucher** [fscheck/FsCheck#515]
I'm running the tests with command line `dotnet test -v n` and it shows only that the test was executed, but not how many times:

```
NUnit Adapter 3.16.1.0: Test execution complete
  √ DeveDiminuirDificuldadeQuandoAcertarAResposta [1s 91ms]

Execução de Teste Bem-sucedida.
Total tests: 1
     Passed: 1 
```

If I run it inside VS4Mac, it shows the information: `Ok, passed 100 tests.`

**Comment by kurtschelfthout** [comment]
Related to this? https://github.com/fscheck/FsCheck/issues/508

**Comment by afucher** [comment]
Yeah, thanks @kurtschelfthout 

Just in case anyone be here for the same issue, this solve the issue:
run `dotnet test --logger:"console;verbosity=detailed"`
