### ISSUE TITLE
uInt generator doesn't respect StartSize

### ISSUE THREAD

**Issue by afucher** [fscheck/FsCheck#516]
I'm starting to use FsCheck in a C# project. I need to test a property and the input is a _uint_, that represents a percentage between 1 and 100.
I was checking and by default the `EndSize` is 100, so it always generate a percentage that is less than 100. I changed to test, if I put the `EndSize` equals to 200, it starts to generate numbers greater than 100.

So I was expecting that the `StartSize` will limit the min limit to 1, since is the default. But is not working like this, even if I force and set the `StartSize` to 1 in the test.

Am I wrong?

Here is the test code:

```[Property(StartSize = 1)]
public Property DeveDiminuirDificuldadeQuandoAcertarAResposta(uint porcentagem)
{
  var estratégia = new SuperMemo2Estratégia();
  var cartão = new  CartãoBuilder().ComPorcentagemDeDificuldade(porcentagem).Generate();

   var novaPorcentagem = estratégia.AdjustDifficulty(cartão, ResultadoEnum.Acertou);

   return (novaPorcentagem < porcentagem).ToProperty().Collect(porcentagem);
}  
```  

And here is the output when I run it:
  ```
 AstroCards.UnitTests.Specs.EstrategiasRevisao.SuperMemo2EstratégiaTestes.DeveDiminuirDificuldadeQuandoAcertarAResposta

Falsifiable, after 2 tests (0 shrinks) (StdGen (256983759,296734197)):
Original:
0u
```
```

**Comment by kurtschelfthout** [comment]
Correct, the `StartSize` and `EndSize` are upper bounds for generators. So e.g. for uints, the size is an upper bound on the value, but the generator can still generate a  smaller uint. The sizes are generally meant to tune efficiency vs test coverage, i.e. larger values typically represent points in the wider "search space" but take longer to generate.

Better to introduce a type `Percentage` and write a generator for it using e.g. `Arb.Default.UInt32().Filter(...)` to generate just the values you want.

**Comment by kurtschelfthout** [comment]
Closing this, feel free to reopen if you have further questions.
