### ISSUE TITLE
Workaround for C# query syntax's SELECT only allowing expressions

### ISSUE THREAD

**Issue by dharmaturtle** [fscheck/FsCheck#523]
F# has the `gen` computation expression which allows us to to "pin" a property on a record to a constant or a value from a custom generator, e.g.:

```
gen {
    let! aValue = aGen
    let! myRecord = Arb.Generate<MyRecord>()
    return { myRecord with SomeProp = aValue }
}
```

C#'s query syntax is more limited. Combined with the lack of `with`, and it becomes more complex to replicate the above behavior. It isn't impossible however, if you add a very simple helper method:

```
public static T SideEffect<T>(T input, Action<T> action) {
    action(input);
    return input;
}

// ...

var gen =
    from aValue in aGen
    from myRecord in Arb.Generate<MyRecord>()
    select SideEffect(myRecord, x => x.SomeProp = aValue)
```

Other C# solutions are to call a local function, or add a `.With()` method to each relevant class and property, but I found those impractical.

This isn't really an issue - more like reporting a solution to a problem I was having with "pinning" values. Is it reasonable to update the docs with this workaround?

**Comment by kurtschelfthout** [comment]
> This isn't really an issue - more like reporting a solution to a problem I was having with "pinning" values. Is it reasonable to update the docs with this workaround?

I'm kind of doubtful because I'm not sure how a workaround for C#'s lack of `with` is particularly relevant for FsCheck? Plus who knows when that situation changes - they seem to be adding quite a few functional features to C# these days.

**Comment by dharmaturtle** [comment]
Sure. I just thought it was a common thing to do with randomized tests, to fix a property to a known value before asserting against it.
