### ISSUE TITLE
Consider removing the restriction that the generator is public.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fscheck/FsCheck#525]
Consider a library like this:

```
[<assembly:InternalsVisibleTo("MyLibraryTests")>]

type internal MyDataStructure = ...

type LibraryAPI = ...
```

This library contains an internal data structure class, which despite being an implementation detail (as opined in the fourth bullet of https://github.com/fscheck/FsCheck/issues/152#issuecomment-141634952), but it's still a type whose behavior is worth verifying by itself, but irrelevant to the purpose of the library to warrant making it public.

Now, let's write a generator:

```
// We are at the MyLibraryTests assembly.

type Generators() =
    static member MyDataStructure() = Arb.generate |> ...
```

The code above raises a compiler error because `Generators` is public but one of its methods returns an internal type. We could make `Generators` internal but FsCheck would complain, forcing us to make `MyDataStructure` internal.

---

The best way to actually solve such problems is to make FsCheck allow nonpublic generator classes. It might be done with [a single-line change in `Runner.fs`](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Runner.fs#L284) but I'm not sure whether it would suffice.

**Comment by kurtschelfthout** [comment]
See https://github.com/fscheck/FsCheck/issues/401

**Comment by kurtschelfthout** [comment]
Closed as dup.
