### ISSUE TITLE
Consider allowing the FsCheck.XUnit.PropertiesAttribute to be applied to an assembly.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fscheck/FsCheck#526]
It would easily allow an assembly-wide property test configuration.

**Comment by kurtschelfthout** [comment]
Yes, don't see any particular problems with allowing that.

**Comment by LaurenceJKing** [comment]
I'd like to take a look at this one. But I have a couple of clarifying questions:

1. Do we want to allow the property attribute to be applied at a class/module level as well?
2. Do we /can we also do this for the NUnit version? (I'm happy to investigate, but I thought I'd raise the question in case anyone happened to know off the top of their heads)

**Comment by kurtschelfthout** [comment]
Thanks @LaurenceJKing!

> Do we want to allow the property attribute to be applied at a class/module level as well?

There is `PropertiesAttribute` for that purpose: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L152 

The most reasonable way to proceed would be to allow `PropertiesAttribute` on assembly level as well (and make it work, of course)

> Do we /can we also do this for the NUnit version? (I'm happy to investigate, but I thought I'd raise the question in case anyone happened to know off the top of their heads)

It'd be nice to have parity, yes. I don't know enough about NUnit extensibility to answer how to do that though!

**Comment by LaurenceJKing** [comment]
I've just noticed that NUnit has it's own [Property attribute](https://docs.nunit.org/articles/nunit/writing-tests/attributes/property.html#:~:text=Custom%20Property%20Attributes,the%20'Attribute'%20suffix%20removed.). The purpose of this attribute seems to be to add tags to your test classes and test methods. Are we happy with this naming clash?

**Comment by kurtschelfthout** [comment]
> Are we happy with this naming clash?

Hm, didn't know about that one. Happy or not, I think we're "stuck" with it definitely for v2.

I'm also generally a bit hesitant to rename things on the FsCheck side, it's such a often used term in this context it's hard to avoid. People will just have to qualify I guess - not the end of the world?

**Comment by LaurenceJKing** [comment]
I agree. It's easy enough to qualify.

**Comment by kurtschelfthout** [comment]
Opened a new issue for the NUnit counterpart, closing this as it's been added.
