### ISSUE TITLE
netstandard2.0 minimum

### ISSUE THREAD

**Issue by brettrowberry** [fscheck/FsCheck#529]
Our security scanning tool flagged the following issues with the FsCheck.Xunit@2.14.3.

NETStandard.Library@1.6.1 has some associated security issues due to:
System.Net.Http@4.3.0, fixed in 4.3.4
- Denial of Service
- Improper Certificate Validation
- Information Exposure
- Privilege Escalation
- Authentication Bypass

NETStandard.Library@1.6.0 has some associated security issues due to:
System.IO.Compression.ZipFile@4.0.1, fixed in 4.3.0
- Arbitrary File Write via Archive Extraction (Zip Slip)

I believe making netstandard2.0 the lowest supported version will resolve these issues.

**Comment by kurtschelfthout** [comment]
I don’t follow. 

FsCheck also targets .NET Standard 2.0 so if you don’t or can’t use 1.6, well, just don’t.

**Comment by bartelink** [comment]
netstandard only dictates a minimum so you can reference higher versions of packages
Also, test code should not be subject to the same security scanning stringency as stuff that actually runs in a prod environment

**Comment by brettrowberry** [comment]
All of your points are correct. It sounds like we can just ignore these warnings. The scanner probably evaluates FsCheck in a netstandard1.6 context no matter how it’s used in our test project.
