### ISSUE TITLE
Option to disable parallelism

### ISSUE THREAD

**Issue by NickLydon** [fscheck/FsCheck#532]
I'm using version 3.0.0-alpha4 of FsCheck.Xunit and in my test I'm using the method `Prop.ForAll`. The test relies on a database context that isn't thread-safe (please hold your judgement 😅). 
Is there a way to disable parallelism in this method? At the moment I've limited it with a `SemaphoreSlim`, but it's very messy.

**Comment by kurtschelfthout** [comment]
If in the config `ParallelConfig` is set to `None` which is the default it won't parallelize.

**Comment by NickLydon** [comment]
I'm slightly embarrassed. The test is async, and I'd used an assertion, rather than return a boolean, which is why it used the overload of the method that takes an Action, and didn't await the result 🤦 
Thanks for your help!
