### ISSUE TITLE
Breaking change: use C# ValueTuple instead of Tuple

### ISSUE THREAD

**Issue by WesToleman** [fscheck/FsCheck#533]
In some cases this is a breaking change so I'd like to raise it for the next major version.

I'm using FsCheck in a C# project. FsCheck uses the [`System.Tuple`](https://docs.microsoft.com/en-us/dotnet/api/system.tuple) type but I would prefer the [`System.ValueTuple`](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-2).

For example `Gen.Zip` is defined as `public static Gen<System.Tuple<a, b>> Zip<a, b>(Gen<a> f, Gen<b> g);`. I would like it to be `public static Gen<System.ValueTuple<a, b>> Zip<a, b>(Gen<a> f, Gen<b> g);`. From what I've seen `ValueTuple` seems to be more common; Linq's [`Enumerable.Zip`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip#System_Linq_Enumerable_Zip__2_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___1__) produces a `ValueTuple` for example.

Is this a possibility for the next major version?

**Comment by kurtschelfthout** [comment]
Yes, it's possible, but I don't think adding overloads for `ValueTuple` would be a breaking change? Can you elaborate on that?

**Comment by jzabroski** [comment]
FsCheck doesn't have interfaces that depend on `System.ITuple`, so I don't think there is any breaking changes here.

**Comment by jzabroski** [comment]
BTW, 

> From what I've seen `ValueTuple` seems to be more common; Linq's [`Enumerable.Zip`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip#System_Linq_Enumerable_Zip__2_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___1__) produces a `ValueTuple` for example.

The other overload of Zip effectively allows you to materialize a System.Tuple.  It's just that nobody did this prior to C# 8.0 unless they're integrating with F# code, since it is quite painful to read System.Tuple from C#.  We would just create classes instead of System.Tuple, because it was a relatively pointless abstraction.

cf https://github.com/dotnet/runtime/issues/20167#issue-558150394

**Comment by WesToleman** [comment]
> Yes, it's possible, but I don't think adding overloads for `ValueTuple` would be a breaking change? Can you elaborate on that?

Only a few functions are overloadable, the rest would need new names.

## Overloadable

```cs
public static Gen<a> Frequency<a>(IEnumerable<System.Tuple<int, Gen<a>>> xs);
public static Gen<a> Frequency<a>(params System.Tuple<int, Gen<a>>[] weightedValues);
public static System.Tuple<Gen<a>, Gen<b>> Unzip<a, b>(Gen<System.Tuple<a, b>> g);
public static System.Tuple<Gen<a>, Gen<b>, Gen<c>> Unzip<a, b, c>(Gen<System.Tuple<a, b, c>> g);
```

## Needs a new name

```cs
public static Gen<System.Tuple<a, a>> Two<a>(Gen<a> g);
public static Gen<System.Tuple<a, a, a>> Three<a>(Gen<a> g);
public static Gen<System.Tuple<a, a, a, a>> Four<a>(Gen<a> g);
public static Gen<System.Tuple<a, b>> Zip<a, b>(Gen<a> f, Gen<b> g);
public static Gen<System.Tuple<a, b, c>> Zip<a, b, c>(Gen<a> f, Gen<b> g, Gen<c> h);
```

**Comment by kurtschelfthout** [comment]
I see, agreed, can't overload based on return type only.

**Comment by kurtschelfthout** [comment]
This was addressed in https://github.com/fscheck/FsCheck/pull/543 in the fscheck3 branch. Not released to NuGet yet, but you should be able to pick it up soon from the AppVeyor feed. 

It'll be in 3.0.0-alpha6 on NuGet when I release it.

As you'll see I've split the APIs for F# and C#, so now the F# API has `Tuple` everywhere and C# `ValueTuple`. Perhaps both APIs need to be "completed" at some point, but then at least we can give the methods returning the non-idiomatic type alonger name in both places (e.g. `twoValue` in F#, `TwoRefTuple` in C#).

**Comment by WesToleman** [comment]
Thanks @kurtschelfthout. On the topic of completing splitting off the C# api there's a few parameters that take `FSharpFunc<>` but should probably take `System.Func<>` instead.

**Comment by kurtschelfthout** [comment]
I should've done those as well in the aforementioned API (only for `Gen`, not the rest yet), but let me know if I missed any!

**Comment by WesToleman** [comment]
Here are all the places the current C# API contains a type with `FSharp` in the name. The types are `FSharpFunc`, `ThrowingFSharpFun`, `FSharpList`, `FSharpMap`, `FSharpOption`, and `FSharpSet`. Strangely I haven't encountered issues with `FSharpFunc` in `Prop.ForAll` but I had to use a third-party library to convert a `System.Func` before I could pass it into `Gen.Collect`. Positively, `System.Func` supports multiple parameters which will simplify the `MapN` interfaces.

## Prop

- `public static FSharpFunc<Testable, Property> Classify<Testable>(bool b, string name);`
- `public static FSharpFunc<Testable, Property> Collect<CollectedValue, Testable>(CollectedValue v);`
- `public static Property ForAll<Value, Testable>(Arbitrary<Value> arb, FSharpFunc<Value, Testable> body);`
- `public static FSharpFunc<Testable, Property> Label<Testable>(string l);`
- `public static FSharpFunc<Testable, Property> Trivial<Testable>(bool b);`

## Arb

- `public static Arbitrary<b> Convert<a, b>(FSharpFunc<a, b> convertTo, FSharpFunc<b, a> convertFrom, Arbitrary<a> a);`
- `public static Arbitrary<a> Filter<a>(FSharpFunc<a, bool> pred, Arbitrary<a> a);`
- `public static Arbitrary<Value> From<Value>(Gen<Value> gen, FSharpFunc<Value, IEnumerable<Value>> shrinker);`
- `public static Arbitrary<a> MapFilter<a>(FSharpFunc<a, a> mapper, FSharpFunc<a, bool> pred, Arbitrary<a> a);`
- `public static FSharpFunc<Value, IEnumerable<Value>> toShrink<Value>(Arbitrary<Value> arb);`
- `public static Arbitrary<FSharpFunc<a, b>> Arrow<a, b>();`
- `public static Arbitrary<FSharpFunc<a15, a16>> FSharpFun<a15, a16>();`
- `public static Arbitrary<FSharpList<a>> FsList<a>();`
- `public static Arbitrary<FSharpMap<l, m>> Map<l, m>();`
- `public static Arbitrary<FSharpOption<a>> Option<a>();`
- `public static Arbitrary<FSharpSet<n>> Set<n>();`
- `public static Arbitrary<ThrowingFunction<a13, a14>> ThrowingFSharpFun<a13, a14>();`
- `public static Arbitrary<ThrowingFunction<a, b>> ThrowingFSharpFun<a, b>(IEnumerable<Exception> exceptions);`

## Gen

- `public static Gen<b> Apply<a, b>(Gen<FSharpFunc<a, b>> f, Gen<a> gn);`
- `public static Gen<IEnumerable<b>> Collect<a, b>(FSharpFunc<a, Gen<b>> f, IEnumerable<a> l);`
- `public static Gen<b[]> CollectToArray<a, b>(FSharpFunc<a, Gen<b>> f, params a[] xs);`
- `public static Gen<FSharpList<b>> CollectToList<a, b>(FSharpFunc<a, Gen<b>> f, IEnumerable<a> l);`
- `public static Gen<a> Filter<a>(FSharpFunc<a, bool> predicate, Gen<a> generator);`
- `public static Gen<a> Fresh<a>(FSharpFunc<Unit, a> fv);`
- `public static Gen<FSharpList<a>> ListOf<a>(Gen<a> gn);`
- `public static Gen<FSharpList<a>> ListOf<a>(int n, Gen<a> arb);`
- `public static Gen<b> Map<a, b>(FSharpFunc<a, b> f, Gen<a> gen);`
- `public static Gen<c> Map2<a, b, c>(FSharpFunc<a, FSharpFunc<b, c>> f, Gen<a> a, Gen<b> b);`
- `public static Gen<d> Map3<a, b, c, d>(FSharpFunc<a, FSharpFunc<b, FSharpFunc<c, d>>> f, Gen<a> a, Gen<b> b, Gen<c> c);`
- `public static Gen<e> Map4<a, b, c, d, e>(FSharpFunc<a, FSharpFunc<b, FSharpFunc<c, FSharpFunc<d, e>>>> f, Gen<a> a, Gen<b> b, Gen<c> c, Gen<d> d);`
- `public static Gen<f> Map5<a, b, c, d, e, f>(FSharpFunc<a, FSharpFunc<b, FSharpFunc<c, FSharpFunc<d, FSharpFunc<e, f>>>>> f, Gen<a> a, Gen<b> b, Gen<c> c, Gen<d> d, Gen<e> e);`
- `public static Gen<g> Map6<a, b, c, d, e, f, g>(FSharpFunc<a, FSharpFunc<b, FSharpFunc<c, FSharpFunc<d, FSharpFunc<e, FSharpFunc<f, g>>>>>> f, Gen<a> a, Gen<b> b, Gen<c> c, Gen<d> d, Gen<e> e, Gen<f> g);`
- `public static Gen<FSharpList<a>> NonEmptyListOf<a>(Gen<a> gn);`
- `public static Gen<FSharpOption<a>> optionOf<a>(Gen<a> g);`
- `public static FSharpList<a> Sample<a>(int size, int n, Gen<a> generator);`
- `public static Gen<a> ScaleSize<a>(FSharpFunc<int, int> f, Gen<a> g);`
- `public static Gen<FSharpList<a>> SequenceToList<a>(IEnumerable<Gen<a>> l);`
- `public static Gen<a> Sized<a>(FSharpFunc<int, Gen<a>> fgen);`
- `public static Gen<FSharpList<a>> SubListOfToList<a>(IEnumerable<a> l);`
- `public static FSharpFunc<FSharpFunc<a, bool>, FSharpFunc<Gen<a>, Gen<a>>> SuchThat<a>();`
- `public static FSharpFunc<FSharpFunc<a, bool>, FSharpFunc<Gen<a>, Gen<FSharpOption<a>>>> SuchThatOption<a>();`
- `public static Gen<FSharpOption<a>> TryFilter<a>(FSharpFunc<a, bool> predicate, Gen<a> generator);`
- `public static Gen<FSharpOption<a>> TryWhere<a>(FSharpFunc<a, bool> predicate, Gen<a> generator);`
- `public static Gen<a> Where<a>(FSharpFunc<a, bool> predicate, Gen<a> generator);`

**Comment by kurtschelfthout** [comment]
Great, thanks for the list!

I think you listed `FsCheck.FSharp.Gen` methods there, which are the F# specific ones so the `FSharpFunc`s in there are very much intentional. The extension methods on `Gen<'T>` in `FsCheck.Fluent` are the ones that have no F# types, as well as `ValueTuple` instead of `Tuple`.

I'm working my way through Prop and Arb for a similar namespace-split into appropriate types soon-ish. It was really the only way to offer an idiomatic interface to both types of users. It will as a side effect also make the internal implementation of FsCheck nicer - as when I'm done with the refactor I can pretty much move all of the `FsCheck.Fluent` classes together at the end of the project.

**Comment by WesToleman** [comment]
Sorry, I should have been more clear, that's the list taken from viewing the 2.14.3 class definitions that are generated from metadata within Visual Studio.

I've just grabbed alpha6 from AppVeyor and had a quick play. It's looking nice so far but I'll see how it integrates with my project when it's available on NuGet. What's the motivation for splitting `Gen` and `GenExtensions`? It makes some functions a little less discoverable and I tend to write `Zip(a, b)` rather than `a.Zip(b)` which is now a little more verbose.

Nit, but personally I'd call `CollectToSequence` just `Collect`.

I'm guessing `GenExtensions.ToArbitrary<a>(this Gen<a> generator, FSharpFunc<a, IEnumerable<a>> shrinker);` will use `Func` when you're finished with `Arb` too?

**Comment by kurtschelfthout** [comment]
> Sorry, I should have been more clear, that's the list taken from viewing the 2.14.3 class definitions that are generated from metadata within Visual Studio.

Right, got it.

> What's the motivation for splitting Gen and GenExtensions? It makes some functions a little less discoverable and I tend to write Zip(a, b) rather than a.Zip(b) which is now a little more verbose.

I simply hadn't considered that :) I think it's fine to define the extension methods on `Fluent.Gen` instead - doesn't hurt to give people the option of using static methods or extension methods.

> Nit, but personally I'd call CollectToSequence just Collect.

Also a reasonable suggestion.

> I'm guessing GenExtensions.ToArbitrary<a>(this Gen<a> generator, FSharpFunc<a, IEnumerable<a>> shrinker); will use Func when you're finished with Arb too?

Yes, I'm not through that one yet.
