### ISSUE TITLE
building docs - readme might be wrong

### ISSUE THREAD

**Issue by snuup** [fscheck/FsCheck#537]
The Readme says

    To generate the html files, run build.[cmd|sh] -t GenerateDocs

I think this is no longer correct. Neither does it work on my side, nor can I see such target in build.cmd or build.sh.

**Comment by kurtschelfthout** [comment]
Indeed it's just Docs now, I'll fix

https://github.com/fscheck/FsCheck/blob/7cd379d7afee8b168d5fba4ff127a926834eb7bd/build.fsx#L436

**Comment by snuup** [comment]
bingo, that works.
build time for docs is surprisingly shockingly long.

Performance:
 - Cli parsing: 193 milliseconds
 - Packages: 54 milliseconds
 - Script compiling: 4 seconds
 - Script analyzing: 177 milliseconds
 - Script running: 1 minute, 9 seconds
 - Script cleanup: 7 milliseconds
 - Runtime: 1 minute, 13 seconds

first run. same for second run. but thats another story.
thank you kurt

**Comment by kurtschelfthout** [comment]
Yeah, that's because it actually runs all the F# code samples via fsi and collects the output to put in the examples.

**Comment by snuup** [comment]
ok, in this case its not a slow but a rigorous build ;)
