### ISSUE TITLE
FsCheck.Xunit: ITestoutputhelper.WriteLine() is not written to test output.

### ISSUE THREAD

**Issue by danthe74** [fscheck/FsCheck#554]
When using FsCheck.Xunit, the output via ITestOutputHelper.WriteLine() is not written to the test output.

Example

````
using FsCheck;
using FsCheck.Xunit;

using Xunit;
using Xunit.Abstractions;

namespace UProfile.Lib.PropertyBasedTest
{
    public class DummyTest
    {
        private readonly ITestOutputHelper _outputHelper;

        public DummyTest(ITestOutputHelper outputHelper)
        {
            _outputHelper = outputHelper;
        }

        [Property]
        public Property SomeTest(int a, int b)
        {
            int real = Calculate(a, b);
            int expected = a + b;

            if (real != expected)
            {
                _outputHelper.WriteLine($"Failed! {real} != {expected}, given {a} and {b}"); // this is _not_ written!
            }

            return (real == expected).ToProperty();
        }

        [Fact]
        public void OtherTest()
        {
            int a = 3;
            int b = 4;
            int real = Calculate(a, b);
            int expected = 7;

            if (real != expected)
            {
                _outputHelper.WriteLine($"Failed! {real} != {expected}, given {a} and {b}"); // this is written!
            }

            Assert.Equal(expected, real);
        }

        public int Calculate(int a, int b)
        {
            return a + b + 1;
        }
    }
}
````

Output in Testpane: 
<pre>
---------- Starting test run ----------
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 5.0.3)
[xUnit.net 00:00:00.32]   Starting:    UProfile.Lib.PropertyBasedTest (parallel test collections = on, max threads = 8)
[xUnit.net 00:00:00.38]     UProfile.Lib.PropertyBasedTest.DummyTest.OtherTest [FAIL]
[xUnit.net 00:00:00.38]       Assert.Equal() Failure
[xUnit.net 00:00:00.38]       Expected: 7
[xUnit.net 00:00:00.38]       Actual:   8
[xUnit.net 00:00:00.38]       Stack Trace:
[xUnit.net 00:00:00.39]         C:\Source\UProfile\UProfile.Lib.PropertyBasedTest\DummyTest.cs(45,0): at UProfile.Lib.PropertyBasedTest.DummyTest.OtherTest()
[xUnit.net 00:00:00.39]       Output:
[xUnit.net 00:00:00.39]         Failed! 8 != 7, given 3 and 4
[xUnit.net 00:00:00.52]     UProfile.Lib.PropertyBasedTest.DummyTest.SomeTest [FAIL]
[xUnit.net 00:00:00.52]       FsCheck.Xunit.PropertyFailedException : 
[xUnit.net 00:00:00.52]       Falsifiable, after 1 test (0 shrinks) (StdGen (2001807671,296858772)):
[xUnit.net 00:00:00.52]       Original:
[xUnit.net 00:00:00.52]       (0, 0)
[xUnit.net 00:00:00.52]       
[xUnit.net 00:00:00.53]   Finished:    UProfile.Lib.PropertyBasedTest
========== Test run finished: 2 Tests run in 939,7 ms (0 Passed, 2 Failed, 0 Skipped) ==========
</pre>

In case the test fails, it would be great to know what the result of the test was without running the test again.

**Comment by kurtschelfthout** [comment]
Thanks for the report. This will be fixed shortly. 

Note you can also use the `Label` method (as shown in #555)  to display some output on test failure if you wish.

**Comment by kurtschelfthout** [comment]
Released in https://www.nuget.org/packages/FsCheck.Xunit/2.15.1

**Comment by danthe74** [comment]
@kurtschelfthout: Thanks for the quick fix. 👍
