### ISSUE TITLE
Generating Func<> and Action<> for Property-Tests in C#

### ISSUE THREAD

**Issue by FreeApophis** [fscheck/FsCheck#557]
# `Func`s
In the Tips and Tricks section of the documentation it is documented that you can create arbitray functions and actions, and this is a very nice feature:

```cs
// Maybe we are unicorns, but we use FsCheck with C# and xUnit
[Property]
public Property CurriedFunctionsGiveTheSameResult(Func<int, string, string> f, int number1, string text1)
{
    var functionForm = f(number1, text1) == Curry(f)(number1)(text1);
    var extensionForm = f(number1, text1) == f.Curry()(number1)(text1);

    return (functionForm && extensionForm).ToProperty();
}
```

This works great for `Func`'s with 1, 2 and 3 parameters, if I want to generate a function with 4 parameters however it throws an unusual exception: 

```
System.Exception : The type System.IntPtr is not handled automatically by FsCheck.
Consider using another type or writing and registering a generator for it.
```

Is this intended behaviour? The limitation to 3 parameters strikes me as unusual, I could understand 1,2 or 4 :) - but since the same limitation applies to`Action`s, it looks like this is intentional, maybe you should document that somewhere. And why is it reproting the type as `System.IntPtr`?

# `Action`s

Function properties are obviously easy to check. However for obvious reasons, I cannot check `Action`s the same way. In a test I would write by hand I would usually define a local variable which would be set by an action to check if the behaviour is as intended.

Is there any way I could do that with an `Action`? 

If not, why does FsCheck support `Action`s in the first place, if I cannot check for some kind of sideEffect from it, I could just use an empty `Action`.

The documentation says, that it creates a random action, but while writing this issue, i took a peek in the debugger: it looks different than a `Func `object from FsCheck which shows different state: It looks like `Action`s are always `Void(r,s,t)`, which would indicate that I really could use an empty Action.

**Comment by kurtschelfthout** [comment]
Indeed FsCheck currently supports up to `Func'4` https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Arbitrary.fs#L809

Easy enough to expand by creating your own `Arbitrary` - also happy to take PRs that add more parameters.

> Is there any way I could do that with an Action?

Not at the moment no. That sort of functionality is more typical of a mocking framework. That said, probably something similar to https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Arbitrary.fs#L106 can be done, i.e. wrapping the `Action` in another type which records the calls made to it. (In the case of `Function` it's to allow shrinking)

> If not, why does FsCheck support Actions in the first place, if I cannot check for some kind of sideEffect from it, I could just use an empty Action.

Mostly for completeness, it'd be pretty surprising if FsCheck could generate `Func` but not `Action`. And it allows you to generate values which have `Action` as a generic type parameter, for example. Indeed, if your testing is better served by creating a recording `Action` or so then nothing is really stopping you.

**Comment by kurtschelfthout** [comment]
Closing, feel free to re-open if you have any more questions or comments.
