### ISSUE TITLE
Question on parameters in model based testing

### ISSUE THREAD

**Issue by casha17** [fscheck/FsCheck#561]
I'm trying to set up a test suite for an API with fscheck and model-based testing with the experimental package.
But, I do find I hard to get the methods to accepts parameters, and since this is not included in the documentation I'm asking here. How do I make the Setup and Next method accepts my types and methods. 

    type fileList = {
        directoryVersions: list<directoryVersion>
        files : list<file>
        file: string
    }

    type Counter(?initial:fileList) =
        member __.uploadFile(content) = fileupload content
        member __.getFile() = file
        override __.ToString() = sprintf "Counter 

    let testSuite =
        let uploadFile content = 
            { new Operation<Counter,fileList>() with
                member __.Run m = m.file = content; m
                member __.Check (c,m) = 
                    let res = c.uploadFile content 
                    m.file = res 
                    |@ sprintf "Inc: model = %A, actual = %A" m res
                override __.ToString() = "upload"}
        let getFile = 
            { new Operation<Counter,fileList>() with
                member __.Run m = m.file; m
                member __.Check (c,m) = 
                    let res = c.getFile()
                    m.file = res 
                    |@ sprintf "Dec: model = %A, actual = %A" m res
                override __.ToString() = "getFile"}
        let create initialValue = 
            { new Setup<Counter,fileList>() with
                member __.Actual() = new Counter(initialValue)
                member __.Model() = initialValue }
        { new Machine<Counter,fileList>() with
            member __.Setup = ?? 
            member __.Next _ = Gen.elements [  uploadFile; getFile ] }

Since uploadFile takes a parameter I don't know how to generate input for that method. Also, how to I set the setup to method.

**Comment by kurtschelfthout** [comment]
There's an extended example at https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Script.fsx#L112 which will be helpful I think.

Basically `Next` returns a `Gen` so you can use the `Gen` API to create an `uploadFile` operation for a random string, e.g. something like `generate<string> |> Gen.map uploadFile`. Something similar for `Setup` should also work - I can't see what type `file` is so hard to give some example code there.

**Comment by kurtschelfthout** [comment]
Assuming this is dealt with - feel free to reopen if you have more questions.
