### ISSUE TITLE
Is it possible to change what is being printed out in model-based experimental

### ISSUE THREAD

**Issue by casha17** [fscheck/FsCheck#565]
Hi. I have a question regarding the print statements when running a model-based test in Verbose. My model is quite large, and for every step/action my whole in-memory model is being printed out and makes it hard to see the things relevant to that action. Is it possible to change the default bahavior of what is being printed?

**Comment by kurtschelfthout** [comment]
Should be possible, though I can't remember doing it: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/StateMachine.fs#L120 shows that models are printed using `%A` (this should perhaps become `%O`). To override what is printed there, you can use the `StructuredFormatDisplayAttribute` on your model class.

**Comment by casha17** [comment]
But, since i have to return a fresh instance of the model for every test, I'm just returning a record. How can I apply the  structuredFormatDisplayAttribute

`let create = 
            { new Setup<apiModel,Model>() with
                member __.Actual() = apiModel()
                member __.Model() = {} <- "Some big model"`

**Comment by kurtschelfthout** [comment]
You apply it to the type, ie your record type. 

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-structuredformatdisplayattribute.html

**Comment by casha17** [comment]
Thanks, that makes sense.
