### ISSUE TITLE
Question about resetting state on API

### ISSUE THREAD

**Issue by casha17** [fscheck/FsCheck#568]
HI. I'm making a test suite for an API, which is running in a docker container and I don't have access to the code. 
For now, every time have a new test run, I need to start and stop the container in order to get a fresh instance. 
I'm thinking about making a pool of containers because stopping and starting takes forever. 
It works fine until fscheck starts shrinking. I want to be able to make a fresh instance for the shrinking steps, is that possible somehow? 
I tried overriding the ShrinkOperations, but it seems like it doesn't work. Or is there any better approach to this example?

**Comment by kurtschelfthout** [comment]
Sorry you closed this earlier before I could answer so I figured it was solved.

The way I would expect this to work is that in `Setup.Actual()` you create a fresh instance every time, i.e. restart the container - is that what you are doing? That's definitely supposed to work with shrinking also but perhaps something is awry - a repro would be helpful. I can't try right now but might have a bit more time later today.

**Comment by casha17** [comment]
I Have this right now where I start and stop the docker container on actual as you suggested. 
But, when fscheck starts shrinking, it gives an error that it cannot connect to the API (inside the docker) because it is being restarted. It seems like the shrinking steps is happening too fast per say. 

```
let r = Docker.executeShellCommand "Docker stop orbit" |> Async.RunSynchronously
                    let r = Docker.executeShellCommand "docker run -d --name orbit --rm -p8085:8085" |> Async.RunSynchronously
                    Thread.Sleep 2000
                    apiModel()
```

The repo can be found here 
https://github.com/casha17/OrbitTestSuite

**Comment by kurtschelfthout** [comment]
There's nothing asynchronous or multi-threaded happening in the FsCheck implementation, so I don't see how it can be somehow "too fast" during shrinking - the only thing I can think of is that it's somehow not calling `Actual` at all. I'll double-check that on my end - perhaps if you have a pretty small repro like the above try debugging into it and see what it's doing, aka set a breakpoint or print in your `Actual()`?

**Comment by kurtschelfthout** [comment]
I checked and it's definitely calling `Actual()` at the start of each run. Did you check the exit code and logs of those docker commands? Probably something went wrong there.

**Comment by casha17** [comment]
I tried to check all logs and exit codes for docker. 
The thing is, the tests and the shrinking steps run good, when resetting docker container in Actual(), but the last shrink steps fail because it cant get connection to the API. I don't quite understand how it can run tests and shrink end then fail in the last shrinking step. The docker container doesn't produce any error. 

```
0:
(files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22,
 Setup apiModel)
DirStructure for user=100  -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Delete file for user=100 fileId=4 fileVersion =1 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:2 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
uploadFile: content: a toUser:100 fileId:3 fileVersion:1 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:2 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
DirStructure for user=100  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
listfiles for user=100 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Create file for user=101 dirId=28 filename=test2.txt -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
listfiles for user=101 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:3 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Nothing
shrink:

```

```
shrink:
(files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22,
 Setup apiModel)
listfiles for user=101 -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:3 for user: 101  -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Nothing
length2shrink:
(files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22,
 Setup apiModel)
Downloaded file:3 for user: 101  -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Nothing
Falsifiable, after 1 test (9 shrinks) (StdGen (1867048523, 296886635)):
Original:
(files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22,
 Setup apiModel)
DirStructure for user=100  -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Delete file for user=100 fileId=4 fileVersion =1 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:2 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
uploadFile: content: a toUser:100 fileId:3 fileVersion:1 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:2 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
DirStructure for user=100  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
listfiles for user=100 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Create file for user=101 dirId=28 filename=test2.txt -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
listfiles for user=101 -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Downloaded file:3 for user: 101  -> files:[id:2 version:1][id:3 version:1] - currentFileId:5 - currentDirId:22
Nothing
Shrunk:
(files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22,
 Setup apiModel)
Downloaded file:3 for user: 101  -> files:[id:2 version:1][id:3 version:1][id:4 version:1] - currentFileId:5 - currentDirId:22
Nothing
with exception:
System.Exception: Exception raised by job
 ---> System.Exception: Failed to get response
 ---> System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.

```

**Comment by kurtschelfthout** [comment]
I don’t quite understand why you think the tests themselves run well - FsCheck only shrinks if the test fails in the first place. So something is going wrong without shrinking.

**Comment by kurtschelfthout** [comment]
Going to close this after inactivity - please feel free to re-open if you have more questions or better indication of a bug.
