### ISSUE TITLE
Design guidelines for defining custom arbitraries

### ISSUE THREAD

**Issue by dgrozenok** [fscheck/FsCheck#593]
Based on the example for C# API here
https://github.com/fscheck/FsCheck/blob/f52f46c979c132339bd2f2985db7800e5705a3c4/examples/FsCheck.CSharpExamples/Program.cs#L208-L214
What if have a type `IEnumerable<long>`? Due to the reference to `ArbMap.Default` I believe the custom implementation of the `ArbitraryLong` will not be used. What is the general recommendation for cases like this when an arbitrary is defined for the generic type? I am currently solving it by creating a merged map and using it everywhere instead. Is it how it's supposed to be? Something like that:
```csharp
 public class MyArbitraries 
{
    private static readonly IArbMap ArbMapAll = ArbMap.Default.Merge<DomainArb>();

    public static Arbitrary<long> Long { get; } = new ArbitraryLong(); 
  
    public static Arbitrary<IEnumerable<T>> Enumerable<T>() { 
        return ArbMapAll.ArbFor<T[]>().Convert(x => (IEnumerable<T>)x, x => (T[])x); 
    }
...
```

**Comment by kurtschelfthout** [comment]
Ah yes I should really update that example. 

Basically the way to do that now is to take an `Arbitrary<T>` argument, which FsCheck will automatically find the right instance for, and pass to the method. Like a sort of dependency injection I guess. 

Example: https://github.com/fscheck/FsCheck/blob/f52f46c979c132339bd2f2985db7800e5705a3c4/src/FsCheck/Internals.DefaultArbs.fs#L288

**Comment by dgrozenok** [comment]
This is great! I knew there must have been a better way of handling that case. Now the new design finally clicks for me. I understand how I can define multiple independent classes with arbitraries responsible for different groups of types with this approach and they will work nicely together when provided as an array to the Property attribute. Thank you!
