### ISSUE TITLE
On failure of a property, the seed displayed should be the one to reproduce the error on the 1st run, not the Nth.

### ISSUE THREAD

**Issue by rca22** [fscheck/FsCheck#596]
If I have a property that fails, I'll get an error message something like
```
    FsCheck.Xunit.PropertyFailedException : 
    Falsifiable, after 10 tests (0 shrinks) (StdGen (1087234922, 296960347)):
    Original:
```
Why is it not possible to work out how many random numbers have been generated in the 9 tests which passed and use that to adjust the pair of numbers returned, so that we get the correct values for a seed which will fail on the first test, so I don't have to step through 9 passing tests / configure conditional breakpoints to investigate?
This would make the tool much more efficient than it currently is by saving time getting to the source of the problem.

**Comment by kurtschelfthout** [comment]
That's implemented in 3.0, you get something like:

```
Falsifiable, after 1 test (0 shrinks) (7641666117553255575,12524720631387418965)
Last step was invoked with size of 2 and seed of (2347712061667596058,14956437915246910851):
```

Note the size is also part of the input as it affects generation.

Backporting to 2.0 would require changing some public types, so semver doesn't allow that.

Closing as done.
