### ISSUE TITLE
Test values generated incorrectly outside of [StartSize, EndSize] range

### ISSUE THREAD

**Issue by Hermholtz** [fscheck/FsCheck#597]
FsCheck.xUnit version 2.16..3.

I need to test my class using varying values in the range from int.MinValue to int.MaxValue. I wrote the following test:
```csharp
    [Property(MaxTest = 1000, StartSize = int.MinValue, EndSize = int.MaxValue, Verbose = true)]
    public Property TestValueRange(long value)
    {
        // just for the purpose of the repro
        return true.ToProperty();
    }
```

Unfortunately the test output contained 1000 repetitions of number `-2147483648L`.

I then changed `StartSize` to `-2_000_000_000` and `EndSize` to `2_000_000_000`. The output was a bit more varying, but all values were negative, and some were less than `-2_000_000_000` which was unexpected. I then tried with `-1_500_000_000` and `1_500_000_000`. Similar (buggy) result.

After changing `StartSize` to `-1_000_000_000` and `EndSize` to `1_000_000_000` it started working as expected.

As the `StartSize` and `EndSize` are quite poorly documented, it is possible that I'm using them not for the purpose they were created (I need something like `MinValue` and `MaxValue`). If I'm doing it right, then this behavior is a bug.

For now I will use -1_000_000_000 to 1_000_000_000, but I think it needs fixing.

I also miss the ability to specify these values as `long` data type. `int` is not always enough.

Please see the attachments for test outputs. Thank you.

Not okay:
[fscheck-output_Min-to-Max.testlog.txt](https://github.com/fscheck/FsCheck/files/7613977/fscheck-output_Min-to-Max.testlog.txt)

Not okay:
[fscheck-output_2000.testlog.txt](https://github.com/fscheck/FsCheck/files/7613978/fscheck-output_2000.testlog.txt)

Not okay:
[fscheck-output_1500.testlog.txt](https://github.com/fscheck/FsCheck/files/7613979/fscheck-output_1500.testlog.txt)

This one is okay:
[fscheck-output_1000.testlog.txt](https://github.com/fscheck/FsCheck/files/7613980/fscheck-output_1000.testlog.txt)

**Comment by kurtschelfthout** [comment]
Size is intended to be positive. Try not changing size, but using `DoNotSize<long>` instead, that should give you longs in the full range.

**Comment by Hermholtz** [comment]
Thank you. I think it then warrants bound checking and throwing with an appropriate message.

With your advice it seems that it's not possible to use a simple `[Property]` test method anymore, but instead I have to use the xUnit's `[Fact]` and configure FsCheck myself. It makes it much more complicated, I've mostly figured it out, but I have one more issue - there's no `Check` overload that would accept the Configuration and ITestOutputHelper at the same time. So either I cannot adjust the number of tests or the test console is empty.

```csharp
    private readonly ITestOutputHelper _TestOutputHelper;
    public VarIntTests(ITestOutputHelper testOutputHelper)
    {
        _TestOutputHelper = testOutputHelper;
    }

    [Fact(DisplayName = "Property test using FsCheck")]
    public void PropertyCheckWithCustomGen()
    {
        var generator = Arb.Generate<DoNotSize<long>>();
        var arb = Arb.From(generator);
        var property = Prop.ForAll<DoNotSize<long>>(arb, value => value.Item >= long.MinValue);

        var configuration = Configuration.Verbose;
        configuration.MaxNbOfTest = 1234;

        // With these extension methods I cannot pass the Configuration,
        // so unable to adjust number of tests.
        FsCheck.Xunit.CheckExtensions.VerboseCheckThrowOnFailure(property, _TestOutputHelper);

        // With this invocation I can pass the configuration, but cannot pass
        // the ITestOutputHelper, so the xUnit console is empty.
        FsCheck.CheckExtensions.Check(property, configuration);
    }
```

**Comment by kurtschelfthout** [comment]
You could simply:

```
[Property(MaxTest = 1000, Verbose = true)]
    public Property TestValueRange(DoNotSize<long> value)
    {
        // just for the purpose of the repro
        return true.ToProperty();
    }
```

**Comment by Hermholtz** [comment]
Wow, thank you, FsCheck needs much more examples to showcase all its great features.
In the meantime I also figured it out how to solve the above issue of having custom test configuration and output in test explorer, posting it here so that people looking for solution can benefit from it.

```csharp
    private readonly ITestOutputHelper _TestOutputHelper;
    public VarIntTests(ITestOutputHelper testOutputHelper)
    {
        _TestOutputHelper = testOutputHelper;
    }

    [Fact(DisplayName = "Property test using FsCheck")]
    public void PropertyCheckWithCustomGen()
    {
        var property = ...

        var configuration = Configuration.Verbose;
        configuration.MaxNbOfTest = 1234;

        // Here's the way of converting ITestOutputHelper to IRunner accepted by the Configuration...
        configuration.Runner = new TestOutputRunner(_TestOutputHelper);

        property.Check(configuration);
    }
```
