### ISSUE TITLE
Documentation not available in C# and/or VB.net

### ISSUE THREAD

**Issue by martijnhoekstra** [fscheck/FsCheck#61]
Though the documentation indicates it should be possible to write specifications in C# and/or VB, all documentation assumes F# throughout, making it difficult to work with for people with little or no experience with F#.

**Comment by kurtschelfthout** [comment]
Ping! See #63 and the docs I just uploaded for some progress on this. Let me know what you think.

**Comment by kurtschelfthout** [comment]
Going to close this, as the bulk of the docs now have side by side examples in F# and C#. Please open a separate issue or even better, a PR, if you think docs are lacking somewhere. It should be relatively straightforward to add C# snippets to the CSharp.Snippets project, and reference from the FSharp.Formatting fsx files.
