### ISSUE TITLE
NUnit PropertyAttribute name conflict

### ISSUE THREAD

**Issue by lucasteles** [fscheck/FsCheck#622]
NUnit already has an attribute called [PropertyAttribute](https://docs.nunit.org/articles/nunit/writing-tests/attributes/property.html) which conflicts with FsCheck.NUnit attribute name

Workarounds:
    - Use full qualified attribute name `[FsCheck.NUnit.Property]`
    - Create an alias or global alias `global using PropertyTestAttribute = FsCheck.NUnit.PropertyAttribute;`

Maybe we could consider having an attribute called `[PropertyTest]` to avoid this conflict

**Comment by kurtschelfthout** [comment]
Somewhat unfortunate, but that's what fully qualified names and aliases are for imo.
