### ISSUE TITLE
Recursive C# models

### ISSUE THREAD

**Issue by TrickyCat** [fscheck/FsCheck#626]
Hello 👋.

I have a project with existing C# models which come from some Nuget package (thus it's out of my control to change it). And then I try to use some types from that package as an input in my tests the test process fails with the StackOverflowException. And that's for a reason: it turned out that some of those models have cyclic dependencies on each other, and FsCheck enters the infinite loop while attempting to generate any single instance.

So, I wonder whether there's a way to generate the instances of `A` and `B`

```csharp
public class A {
    public B PropB { get; set; }
}
public class B {
    public A PropA { get; set; }
}
```

Which would point to each other?

![Untitled Diagram](https://user-images.githubusercontent.com/855874/209474793-25e2ad16-c2c3-4911-a7a3-fb735744004e.jpg)

---

Or an instance of `V` with some limited number of `W`'s created? 🤔

```csharp
public class V {
    public W PropW { get; set; }
}
public class W {
    public ICollection<X> PropX { get; set; }
}
public class X {
    public W PropW { get; set; }
    public Y PropY { get; set; }
}
public class Y {
    public W PropW { get; set; }
}
```

---

Do I miss some well-known features of FsCheck?

**Comment by kurtschelfthout** [comment]
The automatically derived generators indeed do not support recursive record-like types.  So you'll have to write your own generators for them. 

One way of doing that is:

- create helper generators for `A` with `A.PropB == null`, and for `B` with `B.PropA == null` to break the cycles
- In the generator for `A`, generate from both the helpers, then set properties on `A` and `B` and return `A`
- Ditto for the generator for `B`.
