### ISSUE TITLE
Revamp C#/VB.NET API

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#63]
This is a spin off of issue #61. I've gathered my thoughts on what I think is wrong with the existing C# API and what I'd like to see changed. This issue is very much up for grabs, but I would be very supportive of anyone tackling this project; unfortunately I will not be doing this myself.

I think the idea of having a fluent API for generator building (and a little integration with LINQ) is sound. I am a little bit less sure about the same approach for properties. But haven't really thought it through.

Overall this API could at least use some maintenance and spring cleaning. It is still mostly in the same state since I first committed it.

Some things that bother me:
- the names of functions in both APIs are completely different. I mostly use the F# API, occassionally using the C# API. I get confused. (and I'm the author of this thing, so I'm not surprised folks are complaining). There is little reason for this; they should be harmonized.
- The C# API pre-dates the major refactoring of the F# API; there is no concept of Arbitrary for example. This can be limiting.
- There are no tests or documentation, hence bugs. E.g. see #5.
- It is not complete; some things like the model based checking for example I haven't tried to do from C#. May be possible but likely there is some ugliness.
- I don't think the integration with Xunit and NUnit works that well; again the API predates that integration so I think you probably have to jump through some hoops. It should just run any method that returns a Spec, I suppose, although without type inference that makes the return type look a bit ugly.
- If we keep the Spec approach, we should have some code generation so we can generate the thing for higher arities.

Overall, I would like the whole thing revamped and think it's worth breaking all users of the C# API to do the revamp. I would very much appreciate a dedicated volunteer to work on this with me.

**Comment by kurtschelfthout** [comment]
I'm short volunteers, so have started on this myself for the v2.0 release. See e.g https://github.com/fsharp/FsCheck/commit/7378493cadb3166b16ca91a1f7e8e7326be37efc and preceding commits. If you have opinions, go.

Making the names more or less the same (modulo casing) will also help a lot with #61.

**Comment by mausch** [comment]
I might be able to help with this today during the fsharpex hackday. Is there anything pending to do, or is this done and you're simply looking for feedback about this? Tests, maybe?

**Comment by kurtschelfthout** [comment]
Thanks a lot for asking!

It is certainly not done - there are a few aspects which are mostly implemented but with not so glamorous but important tasks remaining (feedback, docs and testing). This is the Gen and Command API as on head today. I have started writing documentation - so the general pattern for side by side F# and C# code examples is there. See the CSharp.DocSnippets and QuickStart.fsx. What can to be done is add to TestData.fsx and StatefulTesting.fsx. (The rest may change, see below). Also testing the new extension methods and overloads, and just general feedback on the API (as in, a review) would be useful.

The property API (Prop module) is more in limbo , hence don't think it's currently worth writing tests or docs for it. I am contemplating getting rid of the custom fluent API because I am running into some limitations with the overloading, and also the number of overloads is getting a bit ridiculous. So in some local changes, I have made Property a real type instead of a type alias, so that I can try applying the same pattern as for Gen. I'll push this to a branch today, but it doesn't even build at all at the moment nor do I know it's a good idea. This may be more interesting to hack on - I am open to different approaches here. Ideally, I would like something that is very usable from C#, but doesn't require a totally separate API to maintain.

**Comment by kurtschelfthout** [comment]
Just pushed the branch - very experimental, as I said. https://github.com/fsharp/FsCheck/tree/property-csharp

**Comment by kurtschelfthout** [comment]
By the way, most of the patterns for SxS F#/C# API I have looked a lot at Deedle for inspiration, which seemed to me pretty successful at it.

**Comment by mausch** [comment]
I've been staring at this now for hours and not getting anywhere, things sure are getting hairy!

To be honest I'm not even sure I see the entire goal you have in mind. I agree with you about getting rid of `Specification`. But I don't see any changes around `Gen`, and AFAICT `Property` is a real type in master too, I don't see any change there either (other than not being any `PropBuilder`).

**Comment by kurtschelfthout** [comment]
Sorry! There were not very many changes needed around Gen, I most implemented the missing overloads and hid them from c or f sharp as appropriate. That part is on master and I think mostly done. 

property did use to be a type alias - changing it to a real type was pretty easy and I think I put on master already. Now the question is can the functionality of specbuilder be replicated from csharp using similar techniques as for gen. 

Hope that clarifies a bit! Feel free to move on didn't want to cause frustration.

**Comment by kurtschelfthout** [comment]
2.0.0-alpha just released, still a ways to go.

The API is more or less complete - but could use some real world usage. I'll give it a go too.

Documentation I've added side by side F#/C# examples to QuickStart and Properties. The rest needs to be done.

Tests for the C# part are non-existent at the moment, that said it's all very straightforward wrappers.

Feedback, documentation, tests and fixes welcome.
