### ISSUE TITLE
xUnit analyzer emits errors on Property tests

### ISSUE THREAD

**Issue by voroninp** [fscheck/FsCheck#636]
https://github.com/xunit/xunit/issues/2748

so every method which returns `Property` causes analyzer to emit error.

**Comment by ploeh** [comment]
What are the implications for FsCheck? Does the analyser also emit errors for the `Property` attribute? If so, what can we do about it?

Should we have this discussion here? Or would it be more appropriate to have it at https://github.com/xunit/xunit/issues/2748?

**Comment by ploeh** [comment]
> Or did you mean something else?

No, that's a fine example, thank you.

Can we do anything about this in FsCheck? As far as I can tell, this looks as though the xUnit.net analyser produces a false positive.

I suggest continuing the discussion there, or perhaps open a new xUnit.net issue. I'll be happy to jump in over there if my presence is desired.

**Comment by voroninp** [comment]
I am not very familiar with xUnit architecture, but currently it looks like FsCheck can do nothing.

IMO, the set of allowed types should be defined by `TestCaseDiscovererAttribute`.

Maybe it's indeed worth that you commen in the original issue.

**Comment by ploeh** [comment]
OK, comment added: https://github.com/xunit/xunit/issues/2748#issuecomment-1629408107

Please consider joining the discussion.

**Comment by kurtschelfthout** [comment]
Looks like this was fixed in xunit's analyzers.
