### ISSUE TITLE
XUnit tests marked with [Property] fail to run on .NET Framework

### ISSUE THREAD

**Issue by mahalex** [fscheck/FsCheck#639]
I created a new XUnit test project in VS2022 that multi-targets net472 and net6.0, added package reference to `FsCheck.Xunit` version `3.0.0-rc1`, and added the following tests
```csharp
using Xunit;
using FsCheck.Xunit;

namespace TestFsCheck
{
    public class UnitTest1
    {
        [Fact]
        public void TestFact()
        {
            Assert.True(true);
        }

        [Property(MaxTest = 100)]
        public bool TestProperty(int x)
        {
            return true;
        }
    }
}
```

Trying to run the tests in VS Test Explorer, I can see that both `TestFact` and `TestProperty` run successfully on net6.0, but the net472 run contains only `TestFact`; `TestProperty` is not run and is completely ignored. The same happens when running `dotnet test` from the command line:
```
PS C:\git\TestFsCheck> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  TestFsCheck -> C:\git\TestFsCheck\TestFsCheck\bin\Debug\net472\TestFsCheck.dll
  TestFsCheck -> C:\git\TestFsCheck\TestFsCheck\bin\Debug\net6.0\TestFsCheck.dll
Test run for C:\git\TestFsCheck\TestFsCheck\bin\Debug\net472\TestFsCheck.dll (.NETFramework,Version=v4.7.2)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration:  - TestFsCheck.dll (net472)
Test run for C:\git\TestFsCheck\TestFsCheck\bin\Debug\net6.0\TestFsCheck.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 171 ms - TestFsCheck.dll (net6.0)
```
`FsCheck.Xunit` is supposed to target `netstandard2.0`, so I expected it to work on `net472`. Is the old .NET Framework not supported anymore? Am I missing something?

**Comment by kurtschelfthout** [comment]
It's compatible, but that only means you can load the assembly and compile against it from a net472 runtime and sdk via "normal" means.

Tests usually gets loaded in the test runner (`dotnet test`) via some reflection magic, and xunit plugging something into dotnet test via mechanisms I frankly don't know much about. It's strange that the runner (which seems to be the problem here) does not recoginze `Property` as it uses a similar mechanism to `Fact` afaik.

You may have more luck asking the xunit folks.

**Comment by mahalex** [comment]
Thanks for the quick answer! No, using `public void TestProperty()` leads to the same result.
I found some XUnit issues that seem to be relevant and have not been fixed since 2018. I guess I'll use another test framework.

**Comment by kurtschelfthout** [comment]
closing this as it does not seem to be an FsCheck problem

feel free to re-open if that's incorrect
