### ISSUE TITLE
FsCheck not registering a static method that takes Arbitrary<TType> in C#

### ISSUE THREAD

**Issue by BennieCopeland** [fscheck/FsCheck#640]
When using FsCheck in a C# project, I wanted to register the `Maybe` type from CSharpFunctionalExtensions. I followed the F# example code for creating a `Box<>` type, but when it came to registering the generator and shrinker, FsCheck is ignoring the static method. I receive an exception "No instances found on type Maybe. Check that the type is public and has public static members with the right signature.

```csharp
using FsCheck;

namespace FooBar;

public class Foo<TBar>
{
    public Foo(TBar bar)
    {
        Bar = bar;
    }

    public TBar Bar { get; }
}

public class FooGenerator<TBar>
{
    public static Gen<Foo<TBar>> Generator(Arbitrary<TBar> contents)
    {
        return contents.Generator.Select(v => new Foo<TBar>(v));
    }

    public static Func<Foo<TBar>, IEnumerable<Foo<TBar>>> Shrinker(Arbitrary<TBar> contents)
    {
        return foo => contents.Shrinker(foo.Bar).Select(v => new Foo<TBar>(v));
    }
}

public static class MyGenerators
{
    public static Arbitrary<Foo<TBar>> ArbitraryFoo<TBar>(Arbitrary<TBar> contents)
    {
        return Arb.From(
            FooGenerator<TBar>.Generator(contents),
            FooGenerator<TBar>.Shrinker(contents)
        );
    }
}

public class MyPropertyAttribute : PropertyAttribute
{
    public MyPropertyAttribute()
    {
        Arbitrary = new[] { typeof(MyGenerators) };
    }
}

public class MyTests
{
    [MyProperty]
    public void FooTest(Foo<string> foo) // throws exception
    {
        
    }
}
```

If I change the generator registration to remove the `Arbitrary<TBar>` and move it inside the method block, it works.

```csharp
public static class MyGenerators
{
    public static Arbitrary<Foo<TBar>> ArbitraryFoo<TBar>()
    {
        var contents = Arb.From<TBar>();
        return Arb.From(
            FooGenerator<TBar>.Generator(contents),
            FooGenerator<TBar>.Shrinker(contents)
        );
    }
}
```

**Comment by kurtschelfthout** [comment]
Which version?On 25 Aug 2023, at 04:44, Bennie Copeland ***@***.***> wrote:﻿
When using FsCheck in a C# project, I wanted to register the Maybe type from CSharpFunctionalExtensions. I followed the F# example code for creating a Box<> type, but when it came to registering the generator and shrinker, FsCheck is ignoring the static method. I receive an exception "No instances found on type Maybe. Check that the type is public and has public static members with the right signature.
using FsCheck;

namespace FooBar;

public class Foo<TBar>
{
    public Foo(TBar bar)
    {
        Bar = bar;
    }

    public TBar Bar { get; }
}

public class FooGenerator<TBar>
{
    public static Gen<Foo<TBar>> Generator(Arbitrary<TBar> contents)
    {
        return contents.Generator.Select(v => new Foo<TBar>(v));
    }

    public static Func<Foo<TBar>, IEnumerable<Foo<TBar>>> Shrinker(Arbitrary<TBar> contents)
    {
        return foo => contents.Shrinker(foo.Bar).Select(v => new Foo<TBar>(v));
    }
}

public static class MyGenerators
{
    public static Arbitrary<Foo<TBar>> ArbitraryFoo<TBar>(Arbitrary<TBar> contents)
    {
        return Arb.From(
            FooGenerator<TBar>.Generator(contents),
            FooGenerator<TBar>.Shrinker(contents)
        );
    }
}

public class MyPropertyAttribute : PropertyAttribute
{
    public MyPropertyAttribute()
    {
        Arbitrary = new[] { typeof(MyGenerators) };
    }
}

public class MyTests
{
    [MyProperty]
    public void FooTest(Foo<string> foo) // throws exception
    {
        
    }
}
If I change the generator registration to remove the Arbitrary<TBar> and move it inside the method block, it works.
public static class MyGenerators
{
    public static Arbitrary<Foo<TBar>> ArbitraryFoo<TBar>()
    {
        var contents = Arb.From<TBar>();
        return Arb.From(
            FooGenerator<TBar>.Generator(contents),
            FooGenerator<TBar>.Shrinker(contents)
        );
    }
}

**Comment by BennieCopeland** [comment]
Dotnet Core 7 XUnit test project with `FsCheck` and `FsCheck.Xunit` at version 2.16.6

**Comment by kurtschelfthout** [comment]
Arbitrary methods with Arbitrary arguments are only supported in 3.x if I remember correctly.On 25 Aug 2023, at 09:18, Bennie Copeland ***@***.***> wrote:﻿
Dotnet Core 7 XUnit test project with FsCheck and FsCheck.Xunit at version 2.16.6

**Comment by BennieCopeland** [comment]
According to the [Docs](https://github.com/fscheck/FsCheck/blame/bf0d5707ba7590e83e51d72329e0ef861f2414fc/docs/TestData.fsx#L603) it was supported as of three years ago. I'll check and see if it works in F#. But I also see you're working on 3.0 again, which may make this whole issue moot anyway.

**Comment by BennieCopeland** [comment]
So I checked in F#, and it works just like the docs says it should, so seems like a C# only issue. My workaround works, so if you prefer to close this as "won't fix" to prioritize 3.0, I won't be upset about it.

**Comment by kurtschelfthout** [comment]
Those docs are for version 3.x though. Suspect you just happened to use 3.x for your F# test. This is all done via reflection, so not expecting a C# vs F# difference.

**Comment by kurtschelfthout** [comment]
This should all work in 3.x...with the usual caveat of "docs updates needed"
