### ISSUE TITLE
feat(FsCheck.Xunit): Support xUnit >= 2.5, < 3

### ISSUE THREAD

**Issue by bartelink** [fscheck/FsCheck#647]
Atm [FsCheck.Xunit 3.0.0-rc.1 insists on a 2.4.x of `xunit.extensibility.execution`](https://www.nuget.org/packages/FsCheck.Xunit/3.0.0-rc1#dependencies-body-tab) via a `(>= 2.4.1 && < 2.5.0)` constraint.

In practice, this means that `2.4.2` (Released Aug 2022) is the only compatible xunit version unless you override the dependency rules.

The problem is that this implicitly constrains the versions of other xunit packages used in an overall solution.

----

### Paket

The workaround (necessary if using Paket) is to ignore the restriction by putting this disambiguation/override in the `paket.dependencies` file:

    nuget xunit.extensibility.execution == 2.5.2

### PackageReference

The best known workaround for normal `PackageReference`s is to place an override (with warning suppression) alongside the FsCheck reference. [It's no oil painting](https://github.com/jet/equinox/commit/46e9c9fa75f7ac0e513690e89cf1bbf457f6501b):
```
    <PackageReference Include="FsCheck.xUnit" Version="3.0.0-rc1" />
    <!-- HACK re https://github.com/fscheck/FsCheck/issues/647 required for FsCheck rc1 -->
    <PackageReference Include="xunit.extensibility.execution" Version="2.7.0">
      <NoWarn>NU1608</NoWarn>
    </PackageReference>
```

----

Of course, the main problem then is manually maintaining such an override - the 2.7.0 / 2.5.2 in the above needs to remain in sync with your xunit references (and e.g. integrated package updates tooling such as Rider may choke if you don't)

----

I note there's a related PR, but as it stands, it does not actually resolve the overall problem https://github.com/fscheck/FsCheck/pull/645

**Comment by kurtschelfthout** [comment]
Done in rc2 (even somewhat too loose now, my bad, will fix in next release after some infra issues are resolved)
