### ISSUE TITLE
Expose `Gen.choose64`

### ISSUE THREAD

**Issue by corsinpfister** [fscheck/FsCheck#649]
I'd find it very useful to have a version of `Gen.choose` that works with `int64` instead of `int`. I've had a quick look at the source code, and it looks like [there already is a `Gen.choose64` function](https://github.com/fscheck/FsCheck/blob/f1bd17add9fc8ac82e58b59ef3b09e522973e83e/src/FsCheck/FSharp.Gen.fs#L177). It's just not exposed due to the `internal` access modifier.

What's the reason for keeping it `internal`? Couldn't it be exposed?

One use case for me would be that it would allow me to work more easily with the ticks of a `DateTimeOffset`; something along the lines of

```f#
let dateTimeOffsetGenerator(min: DateTimeOffset, max: DateTimeOffset) =
    gen {
        let maxTicksToAdd = (max - min).Ticks
        let! ticksToAdd = Gen.choose64(0, maxTicksToAdd)
        return min.AddTicks(ticksToAdd)
    }
```

**Comment by kurtschelfthout** [comment]
Sure, no objection.
