### ISSUE TITLE
feat(FsCheck.NUnit): Support NUnit >= 4.0.0

### ISSUE THREAD

**Issue by lucasteles** [fscheck/FsCheck#650]
Today FsCheck.NUnit relies on a `< 4.0.0` version of NUnit.

**Comment by kurtschelfthout** [comment]
Indeed. There seem to be quite a few changes. FsCheck.NUnit has generally been "community-maintained" as I don't use it myself....hint hint.

**Comment by Crown0815** [comment]
@kurtschelfthout what kind of tests would need to be run? We have been using FsCheck.NUnit with NUnit 4.0.1 and it worked fine for us. We have been mostly using the [FsCheck.NUnit.Property] Attribute.
