### ISSUE TITLE
FsCheck 3.0.0 RC1 dependency on xunit.extensibility.execution is out of date by three minor versions.

### ISSUE THREAD

**Issue by BennieCopeland** [fscheck/FsCheck#658]
Current XUnit version is 2.7.0, but I am unable to use any version higher than 2.4.2 due to a version mismatch with the xunit.extensibility.execution package.

**Comment by BennieCopeland** [comment]
Just noticed there is a PR for this already: #645

**Comment by bartelink** [comment]
Duplicate of https://github.com/fscheck/FsCheck/issues/647
There's a paket-based workaround there; if not using that, it should be possible to do the equivalent by having an explicit override
(But yes, obviously the answer is for #645 to relax the versioning)
And, _technically_ it's *minor* versions (I'll get my coat!)

**Comment by BennieCopeland** [comment]
I'm not using paket. How do you do an explicit override?

**Comment by bartelink** [comment]
Have not tried, so I'd need to google - pretty sure there's an equivalent way in which you can override to request 2.7 (but I guess you'd need one alongside every FsCheck package reference, which would be annoying). If you do find a workaround, can you post it on #645 please?

**Comment by bartelink** [comment]
@BennieCopeland hack found https://github.com/jet/equinox/commit/46e9c9fa75f7ac0e513690e89cf1bbf457f6501b
Will doc in #645

**Comment by BennieCopeland** [comment]
@bartelink That's great news, thank you! I'll go ahead and close this out since it's a duplicate.
