### ISSUE TITLE
Fallout from Paket and FAKE deletion

### ISSUE THREAD

**Issue by Smaug123** [fscheck/FsCheck#663]
(For after https://github.com/fscheck/FsCheck/pull/662 because it will conflict.)

- [x] It would make sense for appveyor on branches to additionally check that `dotnet pack` will succeed. This should be a simple matter of adding the dependency from `CI` on `Pack`.
- [x] Fix up the logo. Currently we're using the deprecated PackageLogoUrl. (logo file is here: https://github.com/fscheck/FsCheck/blob/master/docs/img/logo.png)
- [x] Look at moving to NerdBank.GitVersioning; either way, get rid of the NuGet dep in build.fsx that make the script take multiple seconds to start. (wontfix: https://github.com/fscheck/FsCheck/issues/663#issuecomment-1962973922)
- [x] Stop `WatchDocs` from printing out empty stdout every 10s
- [x] Error output from subprocesses is space-separated but it should be newline-separated
- [ ] Delete the commented-out bits of Paket that still litter `build.fsx`
- [x] `dotnet pack` release notes need to be escaped or passed via other means (see latest AppVeyor builds)

**Comment by kurtschelfthout** [comment]
```
// I *believe* it is impossible to have a fixed (not floating) version number from a source reference
// via `dotnet pack`. Without this next bit, FsCheck.Xunit vA.B.C depends on >= FsCheck vA.B.C, not
// on FsCheck exactly at vA.B.C.
```

Have we also lost the `NUnit (>= 3.13.1 && < 4.0.0)` now? It seems to have turned into `NUnit (>= 3.13.1)`. Is there something in dotnet pack that can specify that like paket.template?

**Comment by Smaug123** [comment]
Are you observing that? I see the correct bound.
![Uploading Screenshot 2024-02-25 at 10.54.57.png…]()

**Comment by kurtschelfthout** [comment]
Ah, is it the line in `Directory.packages.props` that does it?

```
    <PackageVersion Include="NUnit" Version="[3.13.1,4.0.0)" />
```

That's alirght then.

Push worked btw, I just pushed rc2. But I think I messed up the xunit dependency restriction. Luckily there is no v3 of xunit so no harm no foul, I hope.

**Comment by Smaug123** [comment]
That's the line, yep. You'll want this:
```
    <PackageVersion Include="xunit.extensibility.execution" Version="[2.4.1, 3.0.0)" />
```
in Directory.Packages.props.

**Comment by kurtschelfthout** [comment]
This always fails with "Forbidden". I've regenerated my token. It has I think the right permissions (see below). I set the token as env variable in exactly the same way as NUGET_KEY, which works.

Clearly either my token is missing some permissions, or it's somehow not being passed correctly. I've checked the header and it looks fine, compared to the docs. https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

Any ideas?

```
    use client = new HttpClient ()
    client.DefaultRequestHeaders.Add ("Accept", "application/vnd.github+json")
    client.DefaultRequestHeaders.Add ("X-GitHub-Api-Version", "2022-11-28")
    client.DefaultRequestHeaders.Authorization <- AuthenticationHeaderValue ("Bearer", pat)
    let postData = JsonSerializer.Serialize releaseSpec
    use content = new StringContent (postData, Encoding.UTF8, "application/json")
    use response = client.PostAsync($"https://api.github.com/repos/%s{gitOwner}/%s{gitName}/releases", content).Result.EnsureSuccessStatusCode()
    let response = response.Content.ReadAsStringAsync().Result
    let output = JsonSerializer.Deserialize<GitHubReleaseResponse> response
``` 

![image](https://github.com/fscheck/FsCheck/assets/164917/b76acf67-db31-412b-a885-a8b7e40e6bc3)

**Comment by Smaug123** [comment]
Let me set up a toy repo and try it.

**Comment by kurtschelfthout** [comment]
Worked just now with a curl. So my token must be ok, it's just not being set in the header correctly somehow.

**Comment by Smaug123** [comment]
Currently you're setting Authorization twice (`client.DefaultRequestHeaders.Add ("Authorization", "2022-11-28")`) - that's my bad, you need to delete that line. Haven't worked out if that's the only problem yet.

**Comment by kurtschelfthout** [comment]
Yeah, did that, with that it didn't work at all. (See my commit on master just now). After that I get the Forbidden error.

**Comment by kurtschelfthout** [comment]
Fixed up the release manually for now, no rush. Stepping away from computer now for a while.

**Comment by Smaug123** [comment]
Got it - I need to learn never to use anything other than `SendAsync`, because it's liable to hide crucial information. The problem is https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#user-agent ("you need a user agent").

Recommend the following as the body of `githubRelease`:

```fsharp
    Console.WriteLine "Tagging new version and performing GitHub release... "

    let pat =
        match Environment.GetEnvironmentVariable "GITHUB_PAT" with
        | null ->
            [
                "Obtain a GitHub personal access token from https://github.com/settings/tokens?type=beta ."
                $"Scope it to at least %s{gitOwner}/%s{gitName} and write access to Repository Permissions -> Contents."
            ]
            |> List.iter Console.WriteLine
            getUserInput "GitHub PAT"
        | s -> s
    let remote =
        let matchingRemotes =
            runProcessWithOutput Map.empty "git" ["remote" ; "-v"]
            |> fun stdout -> stdout.Split '\n'
            |> Seq.choose (fun line ->
                let line = line.Trim ()
                if line.EndsWith ("(push)", StringComparison.Ordinal) then
                    if line.Contains $"%s{gitOwner}/%s{gitName}" then
                        Some line
                    else None
                else None
            )
            |> Seq.toList
        match matchingRemotes with
        | [] -> $"%s{gitHome}/%s{gitName}"
        | [x] -> x.Split().[0]
        | _ ->
            let remotes =
                matchingRemotes
                |> String.concat " "
            failwith $"Multiple matching push remotes found for %s{gitOwner}/%s{gitName}: %s{remotes}"

    runProcess "git" ["commit" ; "--all" ; "--allow-empty" ; "--message" ; $"Bump version to %s{releaseNotes.NugetVersion}"]
    let gitBranch =
        runProcessWithOutput Map.empty "git" ["symbolic-ref" ; "--short" ; "HEAD"]
    Console.WriteLine $"Branch: '%s{gitBranch}'; remote: '%s{remote}'"
    runProcess "git" ["push" ; remote ; gitBranch]
    runProcess "git" ["tag" ; "-f" ; releaseNotes.NugetVersion]
    runProcess "git" ["push" ; "-f" ; remote ; releaseNotes.NugetVersion]

    Console.WriteLine "Creating GitHub release... "

    let releaseSpec =
        {
            TagName = releaseNotes.NugetVersion
            TargetCommitish = "" // if empty, uses the default branch
            Name = releaseNotes.NugetVersion
            Body = releaseNotes.Notes |> String.concat "\n"
            IsDraft = true
            IsPreRelease = releaseNotes.SemVer.PreRelease.IsSome
        }

    use client = new HttpClient ()
    use message = new HttpRequestMessage (Method = HttpMethod.Post, RequestUri = Uri $"https://api.github.com/repos/%s{gitOwner}/%s{gitName}/releases")
    message.Headers.Add ("Accept", "application/vnd.github+json")
    message.Headers.Add ("X-GitHub-Api-Version", "2022-11-28")
    message.Headers.Add ("Authorization", $"Bearer %s{pat}")
    message.Headers.Add ("User-Agent", "build-fsx-release")
    let postData = JsonSerializer.Serialize releaseSpec
    use content = new StringContent (postData, Encoding.UTF8, "application/json")
    message.Content <- content
    use response = client.SendAsync(message).Result
    let response = response.Content.ReadAsStringAsync().Result
    printfn "%s" response
    let output = JsonSerializer.Deserialize<GitHubReleaseResponse> response

    Console.WriteLine $"GitHub response: %+A{output}"

    Console.WriteLine "done."
```

**Comment by kurtschelfthout** [comment]
> Look at moving to NerdBank.GitVersioning; 

From a quick look, this doesn't do what we want (i.e. read the release notes and pick up the version from there). It seems to require a separate json file with the verison in it. If that's the case, I'd prefer just keeping the fake dependency for this, I don't think it'll get in the way much.

**Comment by Smaug123** [comment]
Fair enough!

**Comment by Smaug123** [comment]
Oh nooooo, it looks like `dotnet pack` interprets commas in `-p:PackageReleaseNotes=`:

The failed process call:
```
Process 'dotnet' failed with nonzero exit code 1. Args: pack --configuration Release -p:Version=3.0.0-rc2 --output bin -p:PackageReleaseNotes=Breaking change: confusingly named `StringNoNnulls` is renamed to `StringNoNullChar`.
Breaking change: The operators `|@`, `@|` and `%>` are removed. Please use `Prop.label` instead.
Negative decimals are now also generated. (by Stephen Smith)
Relaxed FsCheck.Xunit's restriction on xUnit versions. (by Tom Rijnbeek)
Made `Gen.choose64` public.
Removed dependency on FAKE and paket in favor of standard .NET tools. (by Patrick Stevens)
Added more `ForAll` overloads for various `Task` types.
The collections types `NonEmptySet`, `NonEmptyArray` and `FixedLengthArray` now implemented `IEnnumerable` to avoid a call to `Get` in common scenarios..
```

Stdout of `dotnet pack`:
```
  MSBuild version 17.8.3+195e7f5a3 for .NET
MSBUILD : error MSB1006: Property is not valid.
Switch:  `@|` and `%>` are removed. Please use `Prop.label` instead.
Negative decimals are now also generated. (by Stephen Smith)
Relaxed FsCheck.Xunit's restriction on xUnit versions. (by Tom Rijnbeek)
Made `Gen.choose64` public.
Removed dependency on FAKE and paket in favor of standard .NET tools. (by Patrick Stevens)
Added more `ForAll` overloads for various `Task` types.
The collections types `NonEmptySet`
For switch syntax, type "MSBuild -help"
```

**Comment by Smaug123** [comment]
I'll put it in an env var instead.

**Comment by kurtschelfthout** [comment]
I can try to avoid commas in the release notes ;)

**Comment by Smaug123** [comment]
On the plus side, Appveyor does now catch that error! https://ci.appveyor.com/project/kurtschelfthout/fscheck/builds/49266851

**Comment by Smaug123** [comment]
Oh my *god*, MsBuild itself appears to perform XML escaping on the ampersands I am trying to use to perform XML escaping. If we can get XML-escaped lines in there then they will correctly be shown in the release notes:
<img width="905" alt="Screenshot 2024-02-25 at 20 36 41" src="https://github.com/fscheck/FsCheck/assets/3138005/7d4363d2-2ce9-4079-bd6e-5aec17993669">
https://github.com/jstedfast/MimeKit/blob/4315487b9b469efd93d53c998f145b501e6d55f4/nuget/MimeKit.nuspec#L29

But I can't get them in there.

**Comment by Smaug123** [comment]
Gone with some truly amazing hacks (https://github.com/fscheck/FsCheck/pull/672)
