### ISSUE TITLE
Support for running async tests in parallel?

### ISSUE THREAD

**Issue by polytypic** [fscheck/FsCheck#83]
I would like to test timing properties of concurrent code.  The tests take very little CPU time, but lots of wall-clock time if you run them sequentially.  The tests are such that it should be possible to run tens of thousands of tests&mdash;several orders of magnitude more than the number of cores&mdash;in parallel without problems.  Have there been attempts to allow FsCheck to run async tests in parallel?

**Comment by kurtschelfthout** [comment]
I did a half-hearted attempt a long time ago. Requires a bit of admin to shuffle things around, don't think it's fundamentally hard. I probably made a bit of a mess with the whole runner setup, to be honest. (I mean, the code in Runner.fs specifically, which would need to be modified) It looks more convoluted than its worth, e.g. using the IEnumerable to run the tests. But never got round to cleaning it up.

I think fundamentally it's in decent shape to do this kind of thing; the random seed can be split (though the random properties of these split seeds have never been proven afaik...) and the code should be mostly pure.

**Comment by VesaKarvonen** [comment]
Ok.  I can't promise anything, but I might take a look into implementing "async in parallel" support as I could use the functionality.

**Comment by kurtschelfthout** [comment]
Promises not necessary, thanks for taking a look.

2015-01-27 11:05 GMT+00:00 Vesa Karvonen <notifications@github.com>:

**Comment by VesaKarvonen** [comment]
I'm going to add some notes related to parallelizing FsCheck here.

The `Gen.variant` combinator does not appear to be safe for concurrent/parallel use: https://github.com/fsharp/FsCheck/blob/master/src/FsCheck/Gen.fs#L304

**Comment by amazingant** [comment]
Sorry for a spurious comment, but +1 on this issue. I've found a decent handful of odd bugs by setting FsCheck to run my tests on the order of millions of times. Of course that means I've left my tests running overnight more than a few times. With parallelization, FsCheck would be an awesome use of any (currently) unused servers, because who doesn't love burning up 32 cores with F#?

**Comment by amazingant** [comment]
And another random comment from the newcomer: For a quick hacky solution, I changed `Array.iter` to `Array.Parallel.iter` at [line 304 of Runner.fs][1]. I know this is not a good solution for running a single test with a large `MaxTest` value, but it's an easy change that gives me a very nice speed-up with my test suite.

Ran 46 tests in fsi with `#time "on"` in Windows 7 x64 on an iMac (with Parallels) with an i7-3770. Running 100 test iterations with config = `{ FsCheck.Config.Quick with Replay = Some(FsCheck.Random.StdGen(2085572967,295982475)) }`, I got the following two timings with and then without the change to `Array.Parallel.iter`:
```
Real: 00:00:07.166, CPU: 00:00:35.084, GC gen0: 753, gen1: 23, gen2: 1
Real: 00:00:17.333, CPU: 00:00:17.362, GC gen0: 768, gen1: 9, gen2: 1
```
Same tests, machine, etc., but with `MaxTest` overridden to 10,000, also with then without the change:
```
Real: 00:08:36.049, CPU: 00:43:51.799, GC gen0: 59867, gen1: 2379, gen2: 103
Real: 00:21:34.761, CPU: 00:21:36.149, GC gen0: 61227, gen1: 1058, gen2: 30
```

My notes:

* CPU time went up by just over 100% (slightly more than double) by parallelizing in this way, which seems odd, but wall-clock time also dropped by about 60% in both cases -- (yes, I will now be running a custom build of FsCheck until parallelized tests become a feature)
* For the sake of honesty, using this StdGen, two of my tests fail at 5823 and 1791 tests respectively, but they fail at the same point regardless of parallelization
* My CPU usage always hovers around 110-150% for official FsCheck off NuGet; building and running from master matched this
* My CPU usage running my modified copy of FsCheck from master (with just that change to`Array.Parallel.iter`) ran around 450-500%, dropping to around 200% when five tests were left, and finally running at the 110-150% range for the last two tests

[1]: https://github.com/fsharp/FsCheck/blob/3da7f339bb83240e603b13962d82545247c15a5a/src/FsCheck/Runner.fs#L304

**Comment by kurtschelfthout** [comment]
@amazingant embarrassingly, I have totally overlooked your two comments until now - or perhaps even worse, took note but promptly forgot. Apologies. I blame early onset Alzheimer.

I'll take a look at your suggestion, it looks very interesting.

**Comment by eiriktsarpalis** [comment]
(Bump)

I would also be highly interested in adding such a feature. Currently using FsCheck to drive spec tests against web api. The sequential nature of the current implementation makes running large numbers of tests impractical. Default shrinking behaviour is also problematic in certain cases.

I believe that an async-parallel FsCheck could be developed as an orthogonal extension, that only reuses the random generation components of the main library. Thread safety of the random generators shouldn't be an issue of concern.

**Comment by kurtschelfthout** [comment]
This is now in pre-release in NuGet in 3.0-alpha1: https://www.nuget.org/packages/FsCheck/3.0.0-alpha1

Please try it out and open new issues in case of problems.
