### ISSUE TITLE
Add generator that generates nasty functions instead of pure functions

### ISSUE THREAD

**Issue by forki** [fscheck/FsCheck#93]
At the fsharpex hackday I thought about ways to "break" the FSharp.Core.dll.
I thought it might be interesting to verify behaviour of things like List.map when it gets nasty functions as parameter.

With nasty I mean things like throwing exceptions.

**Comment by forki** [comment]
BTW: I'm not sure how such a property would look, but I think it would be a useful addition to investigate in that direction.

**Comment by kurtschelfthout** [comment]
Initial though would be to have a ``Nasty<'a>`` type wrapper which would throw exceptions in addition to generating ``'a`` with some probability.

**Comment by forki** [comment]
yes. and maybe a way to restrict the exceptions.

**Comment by mausch** [comment]
What nasty stuff would this generator do other than throwing exceptions? Surely not writing to disk? Maybe that could be an `Evil<'a>` wrapper :)

**Comment by forki** [comment]
> Surely not writing to disk? 

yeah I'm not completely sure. that would be bad for the dev if fscheck messes with IO, but I think in general we should try to do something like that. 
FsCheck evolved from quickcheck, but quickcheck doesn't need to test for such nasty properties.

**Comment by forki** [comment]
checking file locking issues might actually a nice thing ;-)

**Comment by kurtschelfthout** [comment]
Hm, yes, maybe there should be a way to parametrize with a sequence of sideffects like ``fun inp -> ()``  and the function generator would pick 0 or more of those to run them when the function is called. 

This is kind of orthogonal to throwing exceptions. I guess another thing Nasty<'a> could do besides throwing exceptions is to return Unchecked.defaultof<'a>.

**Comment by kurtschelfthout** [comment]
Thoughts on this ThrowingFunction? I decided to keep the function pure, but not total, so you wouldn't get weird effects during shrinking. So basically it only throws exceptions.

**Comment by kurtschelfthout** [comment]
This was released in 2.4.0.
